### ISSUE TITLE
建议：关于女仆火把模式

### ISSUE THREAD

**Issue by TuanziRice** [TartaricAcid/TouhouLittleMaid#102]
最近玩的时候发现，女仆这个火把模式只支持插火把啊，如果想要使用其他照明方块就不行了，但是火把实在太脆弱了，希望可以支持放置其他的照明方块，比如说原版的南瓜灯萤石，或者一些其他MOD的灯具之类的。

**Comment by Jedidiah-Zhang** [comment]
这个要求一听就要改一堆算法

**Comment by TartaricAcid** [comment]
那倒不至于改一堆算法，难点在于，如何让游戏逻辑知道什么物品是可以放置的“灯”

**Comment by Jedidiah-Zhang** [comment]
加个矿物词典，然后放配置文件里？

**Comment by TuanziRice** [comment]
我记得以前女仆mod可以用书打开一个配置界面，然后手动标注物品属于剑，弓，火把什么的。可以参考一下吗

**Comment by lone-wolf-akela** [comment]
加个配置文件让玩家自己填哪些是照明用物品也行

**Comment by Simba98** [comment]
> 那倒不至于改一堆算法，难点在于，如何让游戏逻辑知道什么物品是可以放置的“灯”

直接让玩家设定女仆要插什么是否可行？我不太确定Forge有没有获取某个方块类型亮度的API，有的话就挺好。

**Comment by TartaricAcid** [comment]
暂时无较好的解决方法，关闭此问题
