### ISSUE TITLE
几个问题，主要是跟随距离的问题

### ISSUE THREAD

**Issue by 15so42** [TartaricAcid/TouhouLittleMaid#105]
1.看见作者大佬又更新了，真想立马玩到新版，想问一下我怎么更新这个模组啊？直接替换旧版的jar文件就行吗？
2.我发现开启女仆的拾取物品后有些物品拾取不到的话女仆就会卡在那个位置一直看着，跟随的时候容易跟丢。
3.有什么办法修改女仆的跟随距离吗？之前也下了个女仆酱mod，但是那个女仆只能跟随十几格还不能传送，在矿洞转个弯女仆就没了，我才又下了这个女仆mod，两个mod我都很喜欢，感觉自己就像个父亲一样要好好照顾他们，玩的很开心。不过这个女仆虽然跟的比较紧了，但是我航海的时候女仆根本跟不过来，女仆只能传送到陆地上，我每次都是每隔一段距离从海底搭一个陆地上来，我要是不搭陆地直接拉开距离到另一个岛上，女仆直接就不会过来了，我希望能无论何处女仆都能传过来能行吗？
4.给女仆装的盾牌真的有用吗？好像没有防御的样子。
5.关于队友伤害，我有两个女仆，一个近战一个射箭，我发现他们老是误伤对方，希望能改善一下。
6.我是联机玩的，女仆要是误伤了队友召唤的宠物就会打起来，基本上还打不过，有啥办法吗，很容易发生
7.支持作者大大，真的好玩。都是些小问题，只要能解决第三条我就很满足了(´▽`ʃƪ)

**Comment by Jedidiah-Zhang** [comment]
1. 直接替换原文件
2. 找943
3. 你可以用相机拍照然后带着照片航海
4. 我这测试没啥用
5. 以后会增加友方免伤的饰品
6. 之前好像有过类似的问题，我没认真看，你可以找找

**Comment by TartaricAcid** [comment]
1. 除了这种方法还能找到第二种方法更新模组么.jpg
2. 这是一个小 bug，我后续想办法解决（未解决前，此 Issues 保持开启状态）
3. 我用的原版的传送 ai，这一块我不打算做修改，因为你无法判定有效的传送环境，相机系统就是为方便携带女仆设计的，我觉得已经足够了。而且现在的船不是可以带一个生物的么？
4. 并没有用，但是后续也许会设计用处
5. 旗指物系统就是为此设计的
6. 一样，旗指物系统

**Comment by 15so42** [comment]
明白了，谢谢作者了，还有个新问题，我把女仆安置在一个村庄里然后出去干事，回来就找不到了。。有没有什么办法找到她啊，或者是新增一个物品可以指向女仆的位置之类的

**Comment by TartaricAcid** [comment]
没有
