### ISSUE TITLE
我寻思我好像召唤不了女仆了，好像是个bug

### ISSUE THREAD

**Issue by 15so42** [TartaricAcid/TouhouLittleMaid#115]
今天更新了1.16，之前我是有两个女仆的，然后今天我按照之前的方法在御柱上摆好钻石，青金石，铁锭，金锭，红石，煤炭(没错吧？，我还有1.07的p点，确认了好多遍顺序)。结果没反应。当时我就蒙了，然后我试着把神社拆了用御币重新激活再合成也没用，重启游戏也没用，搞了半小时没召唤出来，大家试试能不能召唤出来吧

**Comment by Jedidiah-Zhang** [comment]
查了一下，没有女仆蛋的合成表了，只有村民交易

**Comment by 15so42** [comment]
真的诶，还涨价了还=-=感觉有点太贵了，我村庄都找不到，好不容易找到两个村庄，村名还干我，就被我全杀了，不干我的村庄也全变成僵尸了。原来的召唤方式是特意移除的吗

**Comment by TartaricAcid** [comment]
麻烦查下 JEI，里面有祭坛的合成表……

**Comment by TartaricAcid** [comment]
![001](https://upload.cc/i1/2019/10/09/tdBDSe.png)
