### ISSUE TITLE
女仆骑着扫帚时的AI问题

### ISSUE THREAD

**Issue by Jedidiah-Zhang** [TartaricAcid/TouhouLittleMaid#116]
骑着扫帚时女仆用弹幕模式攻击时，会卡住不动，直到目标被打死或者女仆被打死
后者是更常见的现象，完全没有体现出女仆的空中优势

**Comment by TartaricAcid** [comment]
女仆的飞行模式目前仅供玩赏，暂时不作为主要模式使用
