### ISSUE TITLE
希望增加在神社召回女仆的功能

### ISSUE THREAD

**Issue by 15so42** [TartaricAcid/TouhouLittleMaid#122]
刚才打一堆怪，十几只，女仆打着打着好像没箭了，我也没太在意，继续打怪，打完怪后找不到女仆了，死是没有死的，绀珠之药都还没用，但是就是全地图找不到了？？也不会传送过来，很奇怪？？

**Comment by 15so42** [comment]
找了一个小时，发现女仆掉暮色森林传送门里了=-=不过还是建议增加这个功能，之前有只女仆不见了就再也没找回来，幸好她身上没有特别重要的东西

**Comment by Jedidiah-Zhang** [comment]
原来说过要禁女仆跟传送门的互动，但是还没做

**Comment by TartaricAcid** [comment]
在卸载的所有地图存档中全搜索寻找一个实体，而且还要高效率，并且搜索后删除此实体。

我目前还没接触过这方面的代码，不保证实现的可能性。

**Comment by TartaricAcid** [comment]
> 原来说过要禁女仆跟传送门的互动，但是还没做

我禁用了女仆在骑着扫帚时的传送，因为这一块存在一些奇怪的问题。并没有禁用女仆本身的传送行为，因为这一块并没有问题。

**Comment by 15so42** [comment]
> 在卸载的所有地图存档中全搜索寻找一个实体，而且还要高效率，并且搜索后删除此实体。
> 
> 我目前还没接触过这方面的代码，不保证实现的可能性。

不能把所有女仆存在一个数组里吗，我感觉应该是很简单的啊。在女仆诞生之时就加入一个专门存储女仆信息的数组，包括位置

**Comment by TartaricAcid** [comment]
@15so42 有点没太明白，如果可以的话，希望能发一个 Pull Request 实现下
