### ISSUE TITLE
关于女仆交互面板自动合成的问题。

### ISSUE THREAD

**Issue by TuanziRice** [TartaricAcid/TouhouLittleMaid#126]
最近在使用的时候发现一些问题。
![2019-11-09_08 49 37](https://user-images.githubusercontent.com/53082959/68519755-f75f7180-02cd-11ea-9ee0-0e6ad68bd45c.png)
如图，这里尝试使用女仆自动合成纸张，从左边拿取甘蔗，中间合成，最后放进右边箱子。
实际操作的时候发现了很多问题。
首先小箱子容量是37格而女仆加上双手才17格，如果甘蔗太多，就会导致像图那样女仆背包被甘蔗塞满而无法进行合成。
其次，无论是什么模式，女仆大多时候都在做其他工作和闲逛，即使设置成空闲，也很少回到绑定坐标点。这样在自动化的时候箱子里往往就会堆积大量的甘蔗，而堆积的大量甘蔗又导致了上面的问题，等女仆回来的时候，背包又一下子塞满了。
![2019-11-09_09 11 33](https://user-images.githubusercontent.com/53082959/68520241-fed44a00-02d0-11ea-852c-d2f7ca22e630.png)
最后，我发现女仆对合成兴趣不是很大，即使将其放在固定位置，它也只是无情的拿东西和把东西塞进箱子，就是不合成物品。

希望可以添加一个专门合成的模式，让女仆专心合成物品，而且拿东西不会塞满背包。
熔炼模式，炼药模式还有巡逻模式啥时候有啊。

**Comment by TartaricAcid** [comment]
女仆面板已经被移除了
