### ISSUE TITLE
魔理沙的扫帚bug

### ISSUE THREAD

**Issue by Moshang666** [TartaricAcid/TouhouLittleMaid#128]
单人游戏生存当玩家乘坐魔理沙的扫帚飞行到空中时突然强行退出存档，然后显示连接已丢失,此服务器未启用飞行(这还是单人游戏...)。

**Comment by TartaricAcid** [comment]
此问题无法复现

**Comment by lone-wolf-akela** [comment]
引用自https://www.mcmod.cn/class/1796.html

> 坂本龙马
> 1月前
> QQ酱74409: 飞天扫帚有bug，玩家飞起来就会提示“此服务器..
> 扫帚表示不愿意背锅
> 
> 你可能是装了“简单联机”mod（Server.Properties for LAN）
> 
> 解决方法：
> 
> 找到存档文件下的“server.properties”文件，
> 
> 将“allow-flight=”这一项后面的“false”改成“true”
