### ISSUE TITLE
关于农场模式中的寻路问题

### ISSUE THREAD

**Issue by Fz-summer** [TartaricAcid/TouhouLittleMaid#133]
如果两片农田靠的太近，两个女仆的寻路会互相干扰，经常会看到一个女仆隔着栅栏盯着对面的作物
就算换成大块的方块做成一整面墙都无法改善这种寻路，导致一边直接不动了

**Comment by TartaricAcid** [comment]
已在 https://github.com/TartaricAcid/TouhouLittleMaid/commit/74720bd7dc8e4353b77271399beefd358e610650 中修复

**Comment by TartaricAcid** [comment]
我会在完成自定义符卡设计后发布新版本，可能需要等待半个月至一个月时间

**Comment by Fz-summer** [comment]
943流批，注意休息哈




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "tartaric_acid"<notifications@github.com&gt;; 
发送时间: 2019年11月29日(星期五) 晚上7:36
收件人: "TartaricAcid/TouhouLittleMaid"<TouhouLittleMaid@noreply.github.com&gt;; 
抄送: "_summer_"<2188186289@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [TartaricAcid/TouhouLittleMaid] 关于农场模式中的寻路问题 (#133)




我会在完成自定义符卡设计后发布新版本，可能需要等待半个月至一个月时间
