### ISSUE TITLE
挖矿与砍杀Mod的血条挡住了P值显示

### ISSUE THREAD

**Issue by ddaodan** [TartaricAcid/TouhouLittleMaid#137]
手持御币的时候，左上角被挖矿与砍杀的血条挡住了
![image](https://user-images.githubusercontent.com/40017293/69940979-8141d980-151e-11ea-9a2a-18b6a6643003.png)

**Comment by TartaricAcid** [comment]
后续添加自定义功能，支持玩家随意设置 P 点位置
