### ISSUE TITLE
建议和bug

### ISSUE THREAD

**Issue by Ishtar31116** [TartaricAcid/TouhouLittleMaid#152]
1.**能否增加去掉“女仆”的旗指物和罗盘设置的坐标点的功能**，在某些时候，感觉还是需要女仆攻击其他玩家；罗盘在设置了坐标点过后，“女仆”仅有两种行动模式，跟随玩家或者围绕设置的坐标点行动，某种程度上来说，“女仆”在没有设置坐标点的时候比较“自由”，没有设置点的时候开启home模式的“女仆”是自由（漫无目的）行动的，把“女仆”用方块栅栏之类的围起来也是能够达到和设置坐标点相似的效果。

2.**“女仆”在某些时候模式会自动变为空闲模式**，个人推测是“女仆”所在的区块在被重新加载，玩家打开“女仆”的GUI的时候有观察到过模式的变更（这里仅观察到过由农场模式变为空闲模式，因为有发现“女仆”不收获作物，因此发现了这个问题）。

3.不知道是否有设“女仆”的目标的优先级，我发现交互面板的优先级似乎大于其他的目标的优先级（例如：拾取掉落物，收获作物，种地）。和之前的版本相比较（之前游玩的版本是1.14），正式版的“女仆”好像不喜欢收菜种地了，尤其不喜欢收甘蔗，多数时候是两个“女仆”你望着我，我望着你，能这样很久，完全不理会附近的掉落物、成熟的作物这些。之前版本游玩的时候有将每种作物都分开种，交互面板分开放置，这一次使用的是一大块地，把各种作物全部种在一起，交互面板全部放在菜地中心位置，“女仆”喜欢收了菜之后就直接通过交互面板存放到箱子之中，而不是种地，甘蔗很多时候不收。

4.AI问题，攻击模式不知道是不是使用僵尸的AI，弓箭和弹幕使用骷髅，我观察到是非常相似。目前三种攻击模式（攻击，弓箭，弹幕），弓箭应该是最强，**弓箭模式“女仆”使用的弓有无限附魔的时候不消耗背包的药水箭**，不知道是有意为之还是？**攻击模式移动速度过于缓慢**，相对于其他时候的移动速度（捡经验球跑得飞快）。**弓箭模式“女仆”会经常打到玩家**，原版的骷髅在射击的时候会后退，“女仆”后退的时候就有可能会退到玩家身后，给玩家来几下，我被“女仆”射中很多次，所以“女仆”也变成手办很多次。AI希望可以做一些优化吧，不能我带着“女仆”打怪，我要想着怎么不被“女仆”射到吧，打怪的时候不是应该想不被怪打到吗？

5.**“女仆”有时候上不了一格高的方块
具体参考这个反馈，这个反馈中有图片：https://github.com/TartaricAcid/TouhouLittleMaid/issues/117
和这个问题或许有相同的地方：
https://github.com/TartaricAcid/TouhouLittleMaid/issues/146**
这个问题存在很久了，我最开始游玩这个mod的时候就有发现（当时游玩的版本号记不住了，不过我记得那个版本才有的魔理沙的皮肤，所以我才开始玩的），上一次的反馈可能我没说清楚这个问题。

6.关于“女仆”的技能，每个“女仆”（一个皮肤算一个“女仆”）有自己独有的技能是否可以增加一些多样性，这样这个mod会不会更耐玩？我知道你的设计理念是高自由度，高自由度是沙盒游戏的核心理念。这样的不妨把技能设计成一个单独的系统，每个技能对应特定的道具，对“女仆”使用特定道具可以获得特定技能，每个“女仆”可以获得的技能数量做一个限制，3到5个左右，而对应道具的技能可以有很多个，玩家可以自己选择给“女仆”获得什么样的技能，这样自定义“女仆”的技能不知道算不算自由。**技能系统可以像现在的饰品系统一样**。“女仆”生成的时候随机自带一个技能或许也不错？

最后说一下，不知道这个mod算是什么类型的，用做观赏吗还是什么，或许多数玩家在进行游戏的时候，“女仆”是作为工具人而存在的。

**Comment by TartaricAcid** [comment]
1 已经添加此类功能
2 你的推测是错的，打开 GUI 模式改变为空闲是我们**专门设计**的功能，为的是避免在打开 GUI 时女仆触发模式乱跑。          
而且我测试后女仆模式并没有因为区块卸载变为空闲。
3 暂不做修改
4 暂不做修改
5 已修复
6 暂无计划

mod 类型？观赏为主
