### ISSUE TITLE
Crashing

### ISSUE THREAD

**Issue by LegendaryCrystalFox** [TartaricAcid/TouhouLittleMaid#153]
Game crashes saying "The game crashed whilst there was a severe problem during mod loading that has caused the game to fail Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Minecraft Forge (forge)"
Crash Log: https://pastebin.com/SeesbVD1

**Comment by TartaricAcid** [comment]
delete `config\touhou_little_maid\custom_spell_card` folder and restart game

**Comment by LegendaryCrystalFox** [comment]
Still crashing :(

**Comment by TartaricAcid** [comment]
use this: <https://ci.covertdragon.team/job/TouhouLittleMaid/85/artifact/build/libs/touhoulittlemaid-1.12.2-jenkins-build-85.jar>

**Comment by LegendaryCrystalFox** [comment]
Didn't work either

**Comment by TartaricAcid** [comment]
@LegendaryCrystalFox Provide a new crash-report and logs

**Comment by LegendaryCrystalFox** [comment]
https://pastebin.com/jAbBxhZk

**Comment by TartaricAcid** [comment]
use this: <https://ci.covertdragon.team/job/TouhouLittleMaid/86/artifact/build/libs/touhoulittlemaid-1.12.2-jenkins-build-86.jar>

**Comment by LegendaryCrystalFox** [comment]
It worked! Thank you!

**Comment by TartaricAcid** [comment]
Can you take a screenshot of the `touhou_little_maid` folder under your game configuration folder, I always feel that the configuration file is not placed in the correct location.

**Comment by LegendaryCrystalFox** [comment]
![config](https://user-images.githubusercontent.com/34899528/71068430-b700d800-2144-11ea-9d0d-bb8bc6ba4ae0.PNG)

**Comment by TartaricAcid** [comment]
The reason is not clear at this time, but I have written it down and will see how to cause it later.

You can see if there are spell card items in the creative tab.

**Comment by LegendaryCrystalFox** [comment]
There are no spell cards items

**Comment by TartaricAcid** [comment]
Is the `custom_spell_card` folder empty?

**Comment by LegendaryCrystalFox** [comment]
No

**Comment by TartaricAcid** [comment]
Thank you very much for your feedback

**Comment by LegendaryCrystalFox** [comment]
Np and also the broom doesn't fly or let you jump

**Comment by TartaricAcid** [comment]
Sorry for forgetting an important thing, can you provide the latest game log, I think it will be helpful for me to determine the problem.

**Comment by LegendaryCrystalFox** [comment]
Where do I find game log?

**Comment by TartaricAcid** [comment]
`logs/latest.log` file

**Comment by LegendaryCrystalFox** [comment]
There's going to be a lot of text because I loaded it up with all my mods and am to lazy to load it with just your mod. I could do that in the morning if you wanted me to
[latest.log](https://github.com/TartaricAcid/TouhouLittleMaid/files/3977561/latest.log)

**Comment by TartaricAcid** [comment]
I know why. The version of java you are using is too low. You are currently using 1.8.0_51, but the latest version is 1.8.0_231.

**Comment by LegendaryCrystalFox** [comment]
Oh ok I'll be sure to change it then thanks

**Comment by TartaricAcid** [comment]
new feature: add a notice for java version
https://github.com/TartaricAcid/TouhouLittleMaid/commit/87d426f65d1d619bab760568dc75fb2dc41469cb
