### ISSUE TITLE
女仆太少和其他建议

### ISSUE THREAD

**Issue by scikirbypoke** [TartaricAcid/TouhouLittleMaid#158]
首先是皮肤的问题：作为女仆模组，皮肤里只有咲夜属于女仆，女仆数量比起模组原作少很多。强烈建议将已有的妖精女仆也加入可选皮肤中。

然后是几个建议：

1. 旧女仆模组有一个配套的[playerformlittlemaid](https://www.curseforge.com/minecraft/mc-mods/modchu_playerformlittlemaid)模组，能实现将玩家模型替换成女仆的功能，不知有没有兴趣在车万女仆中实现。

2. 计划里提到的动物宰杀模式，可以靠计划中相机拍照的功能进行筛选，而不需要加多一个模式。

3. 执行玩家选定简单指令的能力。计划中的采橡胶、挖矿等功能会面临如何辨别其他模组方块的问题，分别实现也会让模式列表变得更长。可以考虑加入黑白名单/座标+手持物品+动作的简单指令。比如手持镐挖掘范围内的白名单方块、手持木龙头与指定座标的方块互动、切换女仆工作模式、女仆移动到指定座标等。
复杂一点也可以加入服务铃等道具进行指令的触发执行，便于简单地实现需触发的动作。
更复杂一点可以加入指令清单让女仆能执行多条指令，并实现女仆、清单和特定服务铃的绑定。
这样能代替很多用于其他模组的模式，女仆巡航、岗位换班、按铃开门、定时收获等功能也可以由玩家实现。
不过由于模组名称不是叫女仆自动化，是否加入这种特性请开发者自行决定。

4. 计划里的女仆背包功能，模型方面可以参考日站的这个[LittlePorters](https://forum.civa.jp/viewtopic.php?f=3&t=57#p140)，功能方面可以参考asie的[Wearable Backpacks](https://www.curseforge.com/minecraft/mc-mods/wearable-backpacks)

**Comment by Chloe-koopa** [comment]
使用植入芯片+JavaScript来控制女仆行动（x //记得封掉Java.type

**Comment by scikirbypoke** [comment]
植入芯片太没人性了，我的想法是用女仆刷怪蛋非消耗合成机器女仆，只有机器女仆有编程接口，普通女仆只能下达简单指令
另外最近发现个叫OpenEntity的OC扩展，能部分的控制实体移动，实在想给女仆编程的可以试试

**Comment by Chloe-koopa** [comment]
> 植入芯片太没人性了，我的想法是用女仆刷怪蛋非消耗合成机器女仆，只有机器女仆有编程接口，普通女仆只能下达简单指令
> 另外最近发现个叫OpenEntity的OC扩展，能部分的控制实体移动，实在想给女仆编程的可以试试

说是植入芯片的话，其实可以用其他的设定啦，比如说以JavaScript的形式告诉女仆应该做什么。
而且可以对脚本做出限制，比如说禁止获取方块/刷物品/Java.type，只允许让脚本调用生存玩家能干的方法；调用部分方法需要消耗女仆饱食度，如果饱食度不够则抛出异常等等。

**Comment by Logic530** [comment]
> > 植入芯片太没人性了，我的想法是用女仆刷怪蛋非消耗合成机器女仆，只有机器女仆有编程接口，普通女仆只能下达简单指令
> > 另外最近发现个叫OpenEntity的OC扩展，能部分的控制实体移动，实在想给女仆编程的可以试试
> 
> 说是植入芯片的话，其实可以用其他的设定啦，比如说以JavaScript的形式告诉女仆应该做什么。
> 而且可以对脚本做出限制，比如说禁止获取方块/刷物品/Java.type，只允许让脚本调用生存玩家能干的方法；调用部分方法需要消耗女仆饱食度，如果饱食度不够则抛出异常等等。

我想要植入芯片的设定啊XD，不过说实话脚本控制女仆这种功能和OC以及类似的本来就以编程为主的Mod重叠太高了，本来用OC的无人机就可以实现的换成女仆也没什么意思，无非就是换皮。

 @Chloe-koopa ~~我看你怎么这么眼熟~~

**Comment by scikirbypoke** [comment]
我也不是想用OC那种程度搞多复杂的自动化，也就按门铃时女仆来开个门，对主人鞠个躬，按服务铃就来门口送个汉堡的程度
这么一说可以考虑用指令控制女仆动作？
不过这么简单的系统肯定没办法自动收橡胶的……真要完全把各种模式的实现扔给玩家可能要和OC联动搞个无人机套皮，反正幻想乡人均会飞

**Comment by scikirbypoke** [comment]
总结一下现在实现了多少：
1.现时间点有了资源包，更多女仆皮肤只是时间问题了
2.更换玩家模型的功能，也有其他模组实现了
3.背包女仆也已经做出来了
没实现的，我还有一些新想法：
1.动物宰杀还没有，不过也许能用攻击模式代替，见下
2.指令系统也许并不需要。指令的目标在于适应不同模组里的各种方块和实体，但显得过于繁琐。我最近的一个想法是只实现实体和方块标记系统，使得农场模式和繁殖模式能支持模组里的内容。然后考虑方块挖掘模式和右键模式，这样普通的模组作物能通过两个女仆破坏和种植。右键模式还能用来按按钮，拉拉杆等等。考虑橡胶树这类需要木龙头的情况，应该能将手持物品锁定，当该物品用完了就会去背包、箱子里拿。最后是行动触发功能。设想中能用某种方式触发女仆的工作，还能指定次数。这样一来大部分兼容性问题都能由玩家自己实现，不需要单独开发了。

**Comment by TartaricAcid** [comment]
2 的实现可没那么简单
