### ISSUE TITLE
1.1.8甘蔗模式女仆不收甘蔗，或者只收几个

### ISSUE THREAD

**Issue by wandaren** [TartaricAcid/TouhouLittleMaid#159]
![2019-12-18_22 32 36](https://user-images.githubusercontent.com/42760894/71095707-05b37e00-21e8-11ea-82f8-9eac3ac74c69.png)

**Comment by TartaricAcid** [comment]
我这边测试没发现这种问题，而且看你这图也看不出来有啥问题
