### ISSUE TITLE
驯服的女仆跑到工业先锋的屠宰机的范围被杀死了

### ISSUE THREAD

**Issue by wandaren** [TartaricAcid/TouhouLittleMaid#163]
![TIM图片20191222174321](https://user-images.githubusercontent.com/42760894/71320209-224eff00-24e3-11ea-9c77-d04da261c66b.png)

**Comment by StarsDeath2938** [comment]
这种兼容的问题...很难说的，我个人认为应该不是这个Mod的问题。
工业先锋的屠宰机是对范围内 _非玩家生物_ 造成高额伤害。
（这让我想起了我py的女仆试图捡起IE粉碎机传送带的矿石结果差点被粉碎机绞死

被屠宰机杀死的话坟墓应该会正常生成，个人认为勉强可以接受。
我的女仆不知道怎么被另一位朋友送进TiC2的冶炼炉里了，我只在容器里找到了280ml的血，把冶炼炉拆了也没有见到女仆的坟墓...只有女仆身上的匠魂装备仍然健在。
（于是不久后我在家里又找到了我朋友的坟墓，但是...他身上真的没有。

**Comment by TartaricAcid** [comment]
这算哪门子 bug……
