### ISSUE TITLE
模组冲突

### ISSUE THREAD

**Issue by XDFJHXUNGHDS** [TartaricAcid/TouhouLittleMaid#164]
---- Minecraft Crash Report ----
// Everything's going to plan. No, really, that was supposed to happen.

Time: 2019-12-23 23:47:32 CST
Description: Ticking entity

java.lang.IllegalArgumentException: Cannot get property PropertyEnum{name=variant, clazz=class biomesoplenty.common.block.BlockBOPGrass$BOPGrassType, values=[spectral_moss, overgrown_stone, loamy, sandy, silty, origin, overgrown_netherrack, daisy, mycelial_netherrack]} as it does not exist in BlockStateContainer{block=minecraft:water, properties=[level]}
    at net.minecraft.block.state.BlockStateContainer$StateImplementation.getValue(BlockStateContainer.java:209)
    at biomesoplenty.common.block.BlockBOPGrass.canSustainPlantType(BlockBOPGrass.java:227)
    at biomesoplenty.common.block.BlockBOPGrass.canSustainPlant(BlockBOPGrass.java:270)
    at com.github.tartaricacid.touhoulittlemaid.internal.task.VanillaNormalFarmHandler.canPlant(VanillaNormalFarmHandler.java:72)
    at com.github.tartaricacid.touhoulittlemaid.entity.ai.EntityMaidFarm.shouldMoveTo(EntityMaidFarm.java:161)
    at net.minecraft.entity.ai.EntityAIMoveToBlock.searchForDestination(SourceFile:83)
    at com.github.tartaricacid.touhoulittlemaid.entity.ai.EntityMaidFarm.shouldExecute(EntityMaidFarm.java:85)
    at net.minecraft.entity.ai.EntityAITasks.onUpdateTasks(SourceFile:94)
    at net.minecraft.entity.EntityLiving.updateEntityActionState(EntityLiving.java:888)
    at net.minecraft.entity.EntityLivingBase.onLivingUpdate(EntityLivingBase.java:2359)
    at net.minecraft.entity.EntityLiving.onLivingUpdate(EntityLiving.java:678)
    at net.minecraft.entity.EntityAgeable.onLivingUpdate(EntityAgeable.java:178)
    at net.minecraft.entity.passive.EntityAnimal.onLivingUpdate(SourceFile:43)
    at com.github.tartaricacid.touhoulittlemaid.entity.passive.EntityMaid.onLivingUpdate(EntityMaid.java:260)
    at net.minecraft.entity.EntityLivingBase.onUpdate(EntityLivingBase.java:2179)
    at net.minecraft.entity.EntityLiving.onUpdate(EntityLiving.java:377)
    at net.minecraft.world.World.updateEntityWithOptionalForce(World.java:1996)
    at net.minecraft.world.WorldServer.updateEntityWithOptionalForce(WorldServer.java:832)
    at net.minecraft.world.World.updateEntity(World.java:1958)
    at net.minecraft.world.World.redirect$updateEntity$zbc000(World.java:4123)
    at net.minecraft.world.World.updateEntities(World.java:1762)
    at net.minecraft.world.WorldServer.updateEntities(WorldServer.java:613)
    at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:767)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668)
    at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:279)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
    at java.lang.Thread.run(Thread.java:748)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Entity being ticked --
  Entity Type: touhou_little_maid:entity.passive.maid (com.github.tartaricacid.touhoulittlemaid.entity.passive.EntityMaid)
  Entity ID: 1369199
  Entity Name: 西行寺幽幽子
  Entity's Exact location: 299.28, 64.94, 139.51
  Entity's Block location: World: (299,64,139), Chunk: (at 11,4,11 in 18,8; contains blocks 288,0,128 to 303,255,143), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
  Entity's Momentum: 0.00, -0.08, 0.00
  Entity's Passengers: []
  Entity's Vehicle: ~~ERROR~~ NullPointerException: null
  Entity NBT: {HurtByTimestamp:0,BaubleInventory:{Size:8,Items:[]},ForgeData:{},Sitting:0b,Attributes:[{Base:20.0d,Name:"generic.maxHealth"},{Base:0.0d,Name:"generic.knockbackResistance"},{Base:0.4d,Name:"generic.movementSpeed"},{Base:0.0d,Name:"generic.armor"},{Base:0.0d,Name:"generic.armorToughness"},{Base:1.0d,Name:"forge.swimSpeed"},{Base:16.0d,Name:"generic.followRange"},{Base:0.5d,Name:"generic.flyingSpeed"},{Base:2.0d,Name:"generic.attackDamage"}],MaidHome:1b,Invulnerable:0b,FallFlying:0b,ForcedAge:0,PortalCooldown:0,AbsorptionAmount:0.0f,HomePos:
[I;298,65,139],FallDistance:0.0f,InLove:0,DeathTime:0s,StruckByLightning:0b,SasimonoCRC32:0L,ForgeCaps:{"twilightforest:cap_shield":{permshields:0,tempshields:0}},HandDropChances:[0.085f,0.085f],PersistenceRequired:0b,ShowSasimono:0b,Age:0,ModelId:"touhou_little_maid:saigyouji_yuyuko",Motion:[0.0d,-0.0784000015258789d,0.0d],Leashed:0b,UUIDLeast:-9200446614219166741L,Health:20.0f,LeftHanded:0b,Air:300s,OnGround:1b,Dimension:0,Rotation:[268.14902f,0.0f],UpdateBlocked:0b,HandItems:[{},{}],ArmorDropChances:[0.085f,0.085f,0.085f,0.085f],OwnerUUID:"e36aa20f-af43-3f09-9305-8d59213b6a6d",MaidExp:0,UUIDMost:2509363829862451658L,Pos:[299.28012950477836d,64.9375d,139.513998992171d],MaidInventory:{Size:15,Items:[{Slot:0,id:"minecraft:carrot",Count:1b,Damage:0s}]},Fire:-1s,ArmorItems:[{},{},{},{}],MaidTask:"touhou_little_maid:farm",CanPickUpLoot:0b,IsPickup:1b,HurtTime:0s}

-- Affected level --
  Level name: 孤岛
  All players: 1 total; [EntityPlayerMP['匿名'/1369020, l='孤岛', x=306.46, y=65.00, z=125.53]]
  Chunk stats: ServerChunkCache: 289 Drop: 0
  Level seed: 8123034357587916766
  Level generator: ID 06 - BIOMESOP, ver 0. Features enabled: true
  Level generator options: {"diamondSize":8,"lapisCenterHeight":16,"lavaLakeChance":80,"redstoneMaxHeight":16,"diamondMaxHeight":16,"coalMaxHeight":128,"coalMinHeight":0,"seaLevel":63,"graniteCount":10,"riverSize":4,"gravelMinHeight":0,"graniteSize":33,"redstoneSize":8,"fixedBiome":-1,"waterLakeChance":4,"dioriteMinHeight":0,"andesiteCount":10,"graniteMaxHeight":80,"redstoneMinHeight":0,"lapisSize":7,"dirtCount":10,"ironMinHeight":0,"dioriteMaxHeight":80,"coalCount":20,"gravelCount":8,"coalSize":17,"gravelSize":33,"ironMaxHeight":64,"lapisSpread":16,"dioriteCount":10,"andesiteSize":33,"biomeSize":4,"graniteMinHeight":0,"goldCount":2,"diamondCount":1,"dirtSize":33,"gravelMaxHeight":256,"goldSize":9,"ironCount":20,"diamondMinHeight":0,"ironSize":9,"redstoneCount":8,"andesiteMinHeight":0,"dioriteSize":33,"goldMaxHeight":32,"dungeonChance":8,"andesiteMaxHeight":80,"dirtMinHeight":0,"lapisCount":1,"goldMinHeight":0,"dirtMaxHeight":256,"lowerLimitScale":512.0,"biomeDepthOffset":0.0,"upperLimitScale":512.0,"heightScale":684.412,"biomeScaleWeight":1.0,"biomeDepthWeight":1.0,"mainNoiseScaleZ":80.0,"mainNoiseScaleY":160.0,"depthNoiseScaleX":200.0,"mainNoiseScaleX":80.0,"baseSize":8.5,"depthNoiseScaleZ":200.0,"stretchY":12.0,"depthNoiseScaleExponent":0.5,"biomeScaleOffset":0.0,"coordinateScale":684.412,"useStrongholds":true,"useMineShafts":true,"useTemples":true,"useLavaOceans":false,"useCaves":true,"useWaterLakes":true,"useLavaLakes":true,"useMonuments":true,"useRavines":true,"useDungeons":true,"useVillages":true}
  Level spawn location: World: (202,64,42), Chunk: (at 10,4,10 in 12,2; contains blocks 192,0,32 to 207,255,47), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
  Level time: 246567 game time, 65982 day time
  Level dimension: 0
  Level storage version: 0x04ABD - Anvil
  Level weather: Rain time: 12999 (now: false), thunder time: 42860 (now: false)
  Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true

-- System Details --
  Minecraft Version: 1.12.2
  Operating System: Windows 10 (amd64) version 10.0
  Java Version: 1.8.0_231, Oracle Corporation
  Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
  Memory: 554923288 bytes (529 MB) / 2147483648 bytes (2048 MB) up to 2147483648 bytes (2048 MB)
  JVM Flags: 11 total; -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M -XX:-UseAdaptiveSizePolicy -XX:-OmitStackTraceInFastThrow -Xmn128m -Xmx2048m -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
  IntCache: cache: 0, tcache: 0, allocated: 3, tallocated: 104
  FML: MCP 9.42 Powered by Forge 14.23.5.2847 Optifine OptiFine_1.12.2_HD_U_F5 30 mods loaded, 30 mods active
       States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
       
       | State  | ID                   | Version           | Source                                        | Signature                                |
       |:------ |:-------------------- |:----------------- |:--------------------------------------------- |:---------------------------------------- |
       | LCHIJA | minecraft            | 1.12.2            | minecraft.jar                                 | None                                     |
       | LCHIJA | mcp                  | 9.42              | minecraft.jar                                 | None                                     |
       | LCHIJA | FML                  | 8.0.99.99         | forge-1.12.2-14.23.5.2847.jar                 | None                                     |
       | LCHIJA | forge                | 14.23.5.2847      | forge-1.12.2-14.23.5.2847.jar                 | None                                     |
       | LCHIJA | jei                  | 4.15.0.291        | jei_1.12.2-4.15.0.291.jar                     | None                                     |
       | LCHIJA | quark                | r1.6-177          | Quark-r1.6-177.jar                            | None                                     |
       | LCHIJA | autoreglib           | 1.3-32            | AutoRegLib-1.3-32.jar                         | None                                     |
       | LCHIJA | baubles              | 1.5.2             | Baubles-1.12-1.5.2.jar                        | None                                     |
       | LCHIJA | biomesoplenty        | 7.0.1.2441        | BiomesOPlenty-1.12.2-7.0.1.2441-universal.jar | None                                     |
       | LCHIJA | bookshelf            | 2.3.590           | Bookshelf-1.12.2-2.3.590.jar                  | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LCHIJA | botania              | r1.10-362         | Botania+r1.10-362.jar                         | None                                     |
       | LCHIJA | ctm                  | MC1.12.2-1.0.1.30 | CTM-MC1.12.2-1.0.1.30.jar                     | None                                     |
       | LCHIJA | chisel               | MC1.12.2-1.0.1.44 | Chisel-MC1.12.2-1.0.1.44.jar                  | None                                     |
       | LCHIJA | crafttweaker         | 4.1.20            | CraftTweaker2-1.12-4.1.20.jar                 | None                                     |
       | LCHIJA | ctgui                | 1.0.0             | CraftTweaker2-1.12-4.1.20.jar                 | None                                     |
       | LCHIJA | crafttweakerjei      | 2.0.3             | CraftTweaker2-1.12-4.1.20.jar                 | None                                     |
       | LCHIJA | cyclicmagic          | 1.19.18           | Cyclic-1.12.2-1.19.18.jar                     | None                                     |
       | LCHIJA | eplus                | 5.0.176           | EnchantingPlus-1.12.2-5.0.176.jar             | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LCHIJA | instantlava          | 1.1.1             | InstantLava_1.10.2-1.1.1.jar                  | None                                     |
       | LCHIJA | ironchest            | 1.12.2-7.0.67.844 | ironchest-1.12.2-7.0.72.847.jar               | None                                     |
       | LCHIJA | patchouli            | 1.0-20            | Patchouli-1.0-20.jar                          | None                                     |
       | LCHIJA | potionfingers        | r1.0-8            | PotionFingers-r1.0-8.jar                      | None                                     |
       | LCHIJA | torohealthmod        | 1.12.2-11         | torohealth-1.12.2-11.jar                      | None                                     |
       | LCHIJA | touhou_little_maid   | 1.1.8             | touhoulittlemaid-1.12.2-1.1.8-beta-hotfix.jar | None                                     |
       | LCHIJA | treechopper          | 1.2.4             | TreeChopper-1.12.2-1.2.4.jar                  | None                                     |
       | LCHIJA | twilightforest       | 3.10.1013         | twilightforest-1.12.2-3.10.1013-universal.jar | None                                     |
       | LCHIJA | vanillafix           | 1.0.10-SNAPSHOT   | VanillaFix-1.0.10-99.jar                      | None                                     |
       | LCHIJA | waystones            | 4.0.72            | Waystones_1.12.2-4.0.72.jar                   | None                                     |
       | LCHIJA | worleycaves          | 1.5.1             | worleycaves-1.5.1.jar                         | None                                     |
       | LCHIJA | immersiveengineering | 0.12-92           | ImmersiveEngineering-0.12-92.jar              | 4cb49fcde3b43048c9889e0a3d083225da926334 |
  Loaded coremods (and transformers): Quark Plugin (Quark-r1.6-177.jar)
                                        vazkii.quark.base.asm.ClassTransformer
                                      CTMCorePlugin (CTM-MC1.12.2-1.0.1.30.jar)
                                        team.chisel.ctm.client.asm.CTMTransformer
                                      VanillaFixLoadingPlugin (VanillaFix-1.0.10-99.jar)
                                        
                                      IELoadingPlugin (ImmersiveEngineering-core-0.12-92.jar)
                                        blusunrize.immersiveengineering.common.asm.IEClassTransformer
  GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
  Suspected Mods: Biomes O' Plenty (biomesoplenty), Touhou Little Maid (touhou_little_maid)
  Profiler Position: N/A (disabled)
  Player Count: 1 / 8; [EntityPlayerMP['匿名'/1369020, l='孤岛', x=306.46, y=65.00, z=125.53]]
  Type: Integrated Server (map_client.txt)
  Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by TartaricAcid** [comment]
试试 https://ci.covertdragon.team/job/TouhouLittleMaid/lastSuccessfulBuild/artifact/build/libs/touhoulittlemaid-1.12.2-jenkins-build-90.jar
