### ISSUE TITLE
Crash on Server-side

### ISSUE THREAD

**Issue by Rongmario** [TartaricAcid/TouhouLittleMaid#165]
https://pastebin.com/YYZDfKdy

不能利用 ClientProxy on server side.

**Comment by TartaricAcid** [comment]
试试 <https://ci.covertdragon.team/job/TouhouLittleMaid/lastSuccessfulBuild/artifact/build/libs/touhoulittlemaid-1.12.2-jenkins-build-90.jar>

**Comment by Rongmario** [comment]
Doesn't crash now, thank you!
