### ISSUE TITLE
一些建议

### ISSUE THREAD

**Issue by Jedidiah-Zhang** [TartaricAcid/TouhouLittleMaid#18]
### 1. 强烈要求增加女仆用糖回血的机制

我一个生存档开暮色门的时候闪电劈了女仆一下，到现在还一直半管血（整合包里地狱贼难，所以炼药就搁置了。。。）

### 2. 种田的模式建议改算法

我的田基本上是分好区域，什么种在哪里很明确，所以可想而知我试着让她种的时候两下就把田弄得乱七八糟。。。我建议让她从这块地上收的什么就种什么，两个操作一起完成。这样不会留空地或者吧田弄乱。

我注意到现在这个版本种田的模式女仆也是跟随玩家的，这就意味着玩家必须在地里等着或者在耕地周围小范围活动。我建议弄一个“工作区域”或者“工作站点”的规划，用一个标志定位中心，然后女仆在周围一定区域内工作，或者像bc原来机器人一样。

_我知道会比较麻烦，原来女仆mod也不是这样，所以算是个愿望吧，实在不好弄就算了_

### 3. 让女仆坐下的按键加入配置文件中

我的整合包里是有carry on那个mod的，和让女仆坐下的按键冲突。我又不想改搬起的键位。

### 4. 关于喂食模式

喂食模式在女仆物品栏中的食物会顺序消耗，但当我加了平衡膳食类mod之后，比如生活调味料，就会很麻烦，如果想按照比较好的顺序吃的话，就意味着要把每种食物都摊开然后交错摆放，这样女仆背包里能放的食物就很有限。所以我建议喂食的时候可以有个算法，即当前吃背包中哪种食物浪费最少或者收益最大，就喂哪种食物。

当然简化一些也可以随机喂，也能有很大的优化。

愿望（即可有可无，不着急）：可以喂牛奶，药水；对于加了坚定意志的支持喂水。

### 5. 增加一种让女仆可以跨维度传送到你身边的方法

代价大一点没关系，这是老是各个维度游走的我急需的东西。

**Comment by Jedidiah-Zhang** [comment]
### 6. 添加捡掉落物的黑名单和白名单

**Comment by TartaricAcid** [comment]
种田模式你可以开启 Home 模式，并用罗盘为女仆设置 Home 啊，那东西就是为此设计的

**Comment by Jedidiah-Zhang** [comment]
好吧，可能觉得把干活的地方设置成“Home”有点奇怪，就没往那边想。。。

**Comment by Jedidiah-Zhang** [comment]
我又试了试种田模式，然后总结了一下。。。
1. 建议种田模式下可以关联周围某一个容器，从容器中得到种子，然后把作物再放回容器。
2. 种植，收获作物黑白名单。这样在上面说的原地种植实现后会更好管理。
3. 更换模式的按键最好列出来做选择，而不是点击后顺序变换。
4. 我还是更希望可以用个什么东西画指定的工作区域，而不是指定一个点的周边。
5. 我注意到女仆如果超出Home的范围会瞬移回中心，建议改成走回范围内。

**Comment by Snownee** [comment]
1. CarryOn 的问题目测是 EntityMaid 继承了 EntityAnimal 的关系，修改一下 CarryOn 的配置就好了
2. 种地和喂食模式 AI 优化正在计划中

**Comment by TartaricAcid** [comment]
99f284ece0715e946bf5d20b3daf7aa144ca3ad6
1. 增加了缓慢回血的机制
2. 上面已经回答
3. 暂时不做修改
4. 雪尼已经修改
5. TODO
6. TODO

**Comment by TartaricAcid** [comment]
仅有 6 计划中但未能解决，目前已经记录在 Project 中，故关闭此 Issues
