### ISSUE TITLE
[建议]请务必添加女仆扫雪无雪球掉落的config选项！！

### ISSUE THREAD

**Issue by ChromaPIE** [TartaricAcid/TouhouLittleMaid#183]
首先感谢为女仆加入了扫雪这样一个搭配永冬及静谧四季mod时极其实用又极具代入感的功能。但是，该项功能应用在forge端的，且安装有上述mod的服务器中时，由于无法安装扫地插件，将导致巨大的掉落物产出导致服务器卡顿；并且，此功能将导致玩家在扫雪区域中时莫名捡起过量雪球。建议加入女仆扫雪不产生掉落的功能和相对应的config选项

**Comment by lone-wolf-akela** [comment]
扫地用Sponge插件啊……

**Comment by dong031001** [comment]
> 扫地用Sponge插件啊……

审题吗？Forge端

**Comment by lone-wolf-akela** [comment]
> 审题吗？Forge端

就是Forge所以用SpongeForge呀……我哪儿说错了么……

**Comment by dong031001** [comment]
> > 审题吗？Forge端
> 
> 就是Forge所以用SpongeForge呀……我哪儿说错了么……

SpongeForge会引起对包括但不限于高级火箭模组在内的一系列兼容性问题，所以针对部分开启了正版验证和FTBU模组的中型服务器是没有必要，也加装不了SpongeForge的

**Comment by lone-wolf-akela** [comment]
> SpongeForge会引起对包括但不限于高级火箭模组在内的一系列兼容性问题，所以针对部分开启了正版验证和FTBU模组的中型服务器是没有必要，也加装不了SpongeForge的

和正版验证应该没啥关系吧，服务器除了登录验证之外还是有很多权限管理呀领地划分啊之类的事情要做的……兼容性确实多少有些问题，要装sponge的话得先弄清楚兼不兼容，不过总之如果有条件装个sponge对服务器管理肯定是有帮助的……
当然了增加扫雪不掉落的config也是很好的提案就是了。

**Comment by dong031001** [comment]
> > SpongeForge会引起对包括但不限于高级火箭模组在内的一系列兼容性问题，所以针对部分开启了正版验证和FTBU模组的中型服务器是没有必要，也加装不了SpongeForge的
> 
> 和正版验证应该没啥关系吧，服务器除了登录验证之外还是有很多权限管理呀领地划分啊之类的事情要做的……兼容性确实多少有些问题，要装sponge的话得先弄清楚兼不兼容，不过总之如果有条件装个sponge对服务器管理肯定是有帮助的……
> 当然了增加扫雪不掉落的config也是很好的提案就是了。

在FTBU模组下基本所有基础插件的功能，包括你所述的权限管理、领地划分等都是可以实现的，但唯独还是差了扫地功能，所以才抛出了这个Issue。

**Comment by lone-wolf-akela** [comment]
> 在FTBU模组下基本所有基础插件的功能，包括你所述的权限管理、领地划分等都是可以实现的，但唯独还是差了扫地功能，所以才抛出了这个Issue。

哦那这确实是我不知道，孤陋寡闻了。谢谢指教。

**Comment by Simba98** [comment]
> SpongeForge会引起对包括但不限于高级火箭模组在内的一系列兼容性问题，所以针对部分开启了正版验证和FTBU模组的中型服务器是没有必要，也加装不了SpongeForge的
> 
> 和正版验证应该没啥关系吧，服务器除了登录验证之外还是有很多权限管理呀领地划分啊之类的事情要做的……兼容性确实多少有些问题，要装sponge的话得先弄清楚兼不兼容，不过总之如果有条件装个sponge对服务器管理肯定是有帮助的……
> 当然了增加扫雪不掉落的config也是很好的提案就是了。
> 
> 在FTBU模组下基本所有基础插件的功能，包括你所述的权限管理、领地划分等都是可以实现的，但唯独还是差了扫地功能，所以才抛出了这个Issue。

不如我们顺便去FTBU提个issue建议增加扫地大妈？#滑稽

此外高级火箭在哪个方面不兼容SpongeForge？或许也可以贡献代码来修复它！

**Comment by ChromaPIE** [comment]
> > SpongeForge会引起对包括但不限于高级火箭模组在内的一系列兼容性问题，所以针对部分开启了正版验证和FTBU模组的中型服务器是没有必要，也加装不了SpongeForge的
> > 和正版验证应该没啥关系吧，服务器除了登录验证之外还是有很多权限管理呀领地划分啊之类的事情要做的……兼容性确实多少有些问题，要装sponge的话得先弄清楚兼不兼容，不过总之如果有条件装个sponge对服务器管理肯定是有帮助的……
> > 当然了增加扫雪不掉落的config也是很好的提案就是了。
> > 在FTBU模组下基本所有基础插件的功能，包括你所述的权限管理、领地划分等都是可以实现的，但唯独还是差了扫地功能，所以才抛出了这个Issue。
> 
> 不如我们顺便去FTBU提个issue建议增加扫地大妈？#滑稽
> 
> 此外高级火箭在哪个方面不兼容SpongeForge？或许也可以贡献代码来修复它！

以上的种种驳斥讨论完全偏离了我issue的初衷。我对我的issue已经表明了两种原因：官端问题以及**玩家背包**问题。（请不要再提起“你可以扩大背包/携带黑名单背包”之类毫无意义的言论），反而一再追究何种服务端的问题。我对于常驻于这个仓库的某些用户无时无刻不表现出来的对新建议的，或多或少的排斥性，与意图将问题复杂化扩大化的倾向，以及**帮助酒石酸菌推卸**issue中所反馈问题的意图，**表示失望和遗憾**。

这种态度的comment对于贵仓库所有issue的发展解决，都是有百害而无一利的。请诸位contributors明辨。

**Comment by lone-wolf-akela** [comment]
> 我对于常驻于这个仓库的某些用户无时无刻不表现出来的对新建议的，或多或少的排斥性，与意图将问题复杂化扩大化的倾向，以及**帮助酒石酸菌推卸**issue中所反馈问题的意图，**表示失望和遗憾**。

我们只是mod的普通用户，并没有意愿（也不认为自己有能力）决定此mod作者的开发计划，酒石酸君（及其他本mod代码贡献者）是否愿意添加代码提供您所希望加入的功能，是他们需要决定的问题。然而无论如何，新功能的加入需要时间，而我们看到您现在已经遇到了一些问题/困难。因此，我们作为同一mod的用户，希望从我们自己的使用经验上提出一些可能的问题缓解方案，希望可能首先（至少暂时地）帮助您解决/缓解部分的问题，我实在不觉得我们有做错了什么。

**Comment by Simba98** [comment]
> SpongeForge会引起对包括但不限于高级火箭模组在内的一系列兼容性问题，所以针对部分开启了正版验证和FTBU模组的中型服务器是没有必要，也加装不了SpongeForge的
> 和正版验证应该没啥关系吧，服务器除了登录验证之外还是有很多权限管理呀领地划分啊之类的事情要做的……兼容性确实多少有些问题，要装sponge的话得先弄清楚兼不兼容，不过总之如果有条件装个sponge对服务器管理肯定是有帮助的……
> 当然了增加扫雪不掉落的config也是很好的提案就是了。
> 在FTBU模组下基本所有基础插件的功能，包括你所述的权限管理、领地划分等都是可以实现的，但唯独还是差了扫地功能，所以才抛出了这个Issue。
> 
> 不如我们顺便去FTBU提个issue建议增加扫地大妈？#滑稽
> 此外高级火箭在哪个方面不兼容SpongeForge？或许也可以贡献代码来修复它！
> 
> 以上的种种驳斥讨论完全偏离了我issue的初衷。我对我的issue已经表明了两种原因：官端问题以及玩家背包问题。（请不要再提起“你可以扩大背包/携带黑名单背包”之类毫无意义的言论），反而一再追究何种服务端的问题。我对于常驻于这个仓库的某些用户无时无刻不表现出来的对新建议的，或多或少的排斥性，与意图将问题复杂化扩大化的倾向，以及帮助酒石酸菌推卸issue中所反馈问题的意图，表示失望和遗憾。
> 这种态度的comment对于贵仓库所有issue的发展解决，都是有百害而无一利的。请诸位contributors明辨。
 

@lone-wolf-akela 抄送
 此外，我们是在提出解决方案来帮助你缓解问题，或者寻求其他替代方案；943本人也比较忙；大家也不是没有讨论考虑到你的提议；另外不是所有问题都该是由这一侧解决的；943也有权利决定说，不行，我要科学，扫雪就该有雪！

**Comment by TartaricAcid** [comment]
小问题，好解决

**Comment by TartaricAcid** [comment]
完工
