### ISSUE TITLE
关于 th maid_num get 在服务器使用的问题和改进建议

### ISSUE THREAD

**Issue by Logic530** [TartaricAcid/TouhouLittleMaid#184]
在服务器使用模组时，op使用/th maid_num get [player] 指令无法获取指定玩家的信息，只有被指定玩家能看到提示消息，op和服务器后台输入指令后均没有任何响应。

同时，该命令无法获取离线玩家的信息，希望改进为可以获取离线玩家的信息。

**Comment by TartaricAcid** [comment]
问题 1 已修复
问题 2 解决办法较难，因为绝大部分模组（包括原版）都是获取在线玩家的数据的，暂不尝试进行此建议的采纳和改进
