### ISSUE TITLE
女仆无法攻击被栅栏，活板门，半砖挡住的怪物

### ISSUE THREAD

**Issue by TuanziRice** [TartaricAcid/TouhouLittleMaid#185]
![2020-01-15_13 51 30](https://user-images.githubusercontent.com/53082959/72410066-737ca680-37a2-11ea-852b-7d9efa69c9fa.png)
想让女仆帮忙刷怪来着，结果发现不行。

**Comment by TartaricAcid** [comment]
我记得原版好像就不行吧，不然为啥用半砖档怪呢

**Comment by TartaricAcid** [comment]
符合原版游戏设计，不认为是 bug
