### ISSUE TITLE
建议：扩大扭蛋机的抽奖范围

### ISSUE THREAD

**Issue by Seafon03** [TartaricAcid/TouhouLittleMaid#186]
如题，希望能够让通过一种途径让整合包作者或者腐竹去让扭蛋机抽出minecraft或者其他mod的物品，而不仅仅是女仆模型。

**Comment by TartaricAcid** [comment]
这个建议跑题了，这模组主题就是女仆，脱离女仆抽取其他模组物品，不在我的考虑之内
