### ISSUE TITLE
建议：op权限下让文文的相机支持拍摄所有实体

### ISSUE THREAD

**Issue by Chloe-koopa** [TartaricAcid/TouhouLittleMaid#187]
这样的话可以让文文的相机用于处理一些复杂的实体工作，例如快速复制NPC（NPC自带的魔杖难以快速复制）以及mod开发过程中调试实体等。
建议将"从照片中释放女仆以外的实体的功能"限制在op权限，因为某些实体（命令方块矿车，脚本NPC）等如果不限制为op的话可能会造成恶意提权漏洞。

**Comment by TartaricAcid** [comment]
实现较为复杂，暂时无法添加
