### ISSUE TITLE
光玉弹幕渲染bug

### ISSUE THREAD

**Issue by Chloe-koopa** [TartaricAcid/TouhouLittleMaid#188]
![image](https://user-images.githubusercontent.com/43518523/72600190-20475700-394e-11ea-9a2e-ba0c8783cba1.png)
如图，光玉会覆盖水的透明图层

**Comment by TartaricAcid** [comment]
渲染方面我也是初步了解，我想办法解决吧

**Comment by Logic530** [comment]
植物魔法的火花也有类似的问题呢

**Comment by TartaricAcid** [comment]
这属于 OpenGl 底层问题，很难修复（原版信标也有这种问题）
