### ISSUE TITLE
农耕存储建议

### ISSUE THREAD

**Issue by EasyRain** [TartaricAcid/TouhouLittleMaid#190]
建议增加一个至少保留一组作物种植的机制，使用接口黑名单添加种子久而久之女仆储存格子会满，不添加种子又会全部放进箱子，导致没有种子可用，也顺便建议增加设置农耕范围的道具，让女仆在范围内自动锄地

**Comment by TartaricAcid** [comment]
锄地功能可以添加，我已经添加进 Project 中

绘制范围功能已经有了
