### ISSUE TITLE
对mod敌对生物检测问题

### ISSUE THREAD

**Issue by EasyRain** [TartaricAcid/TouhouLittleMaid#191]
我的mod里面添加过少女前线mod，里面的敌对生物女仆无动于衷，只有被敌对生物攻击到了才会反击，狗在玩家被敌对生物攻击时会主动攻击攻击玩家的敌对生物，但女仆不会，至少在少女前线mod里面的敌对生物攻击玩家女仆不会理会

**Comment by TartaricAcid** [comment]
少女前线 mod（我没听过这个模组啊）？女仆行为和狗不一致？不可能啊，我直接用的就是原版狗的 AI，代码都是直接调用的。

关闭此 Issues，期待提供更加详细的信息反馈

**Comment by EasyRain** [comment]
https://www.mcbbs.net/forum.php?&mod=viewthread&tid=822226
少女前线mod在bbs上找得到的


来自 魅族 16th Plus

-------- 原始邮件 --------
发件人：tartaric_acid <notifications@github.com>
时间：2020年3月15日 15:08
收件人：TartaricAcid/TouhouLittleMaid <TouhouLittleMaid@noreply.github.com>
抄送：EasyRain <E_Rain2713245103@163.com>,State change <state_change@noreply.github.com>
主题：Re: [TartaricAcid/TouhouLittleMaid] 对mod敌对生物检测问题 (#191)

**Comment by TartaricAcid** [comment]
这模组咋玩的，敌对生物是啥啊，没找到啊？

**Comment by EasyRain** [comment]
该模组的敌对生物会自然生成，模组内的所有友好生物需要召唤，模组你去下载的话是两个zip文件不是jar，一个本体和前置。如果觉得麻烦可以就这样，也可能是模组的机制问题吧


来自 魅族 16th Plus

-------- 原始邮件 --------
发件人：tartaric_acid <notifications@github.com>
时间：2020年3月15日 15:36
收件人：TartaricAcid/TouhouLittleMaid <TouhouLittleMaid@noreply.github.com>
抄送：EasyRain <E_Rain2713245103@163.com>,State change <state_change@noreply.github.com>
主题：Re: [TartaricAcid/TouhouLittleMaid] 对mod敌对生物检测问题 (#191)

**Comment by TartaricAcid** [comment]
我已经装了这个模组了，我在测试

**Comment by TartaricAcid** [comment]
我的天，怎么这个模组的实体用的原版的命名空间，我找了半天敌对生物

**Comment by TartaricAcid** [comment]
![image](https://user-images.githubusercontent.com/19620085/76697688-0f5c5d00-66d5-11ea-9e7a-1bcdac2b4bd5.png)
我这是好的啊

**Comment by EasyRain** [comment]
机制问题？我当初玩的时候就有问题，还专门开创造试的


来自 魅族 16th Plus

-------- 原始邮件 --------
发件人：tartaric_acid <notifications@github.com>
时间：2020年3月15日 15:53
收件人：TartaricAcid/TouhouLittleMaid <TouhouLittleMaid@noreply.github.com>
抄送：EasyRain <E_Rain2713245103@163.com>,State change <state_change@noreply.github.com>
主题：Re: [TartaricAcid/TouhouLittleMaid] 对mod敌对生物检测问题 (#191)
