### ISSUE TITLE
一个小的转化bug

### ISSUE THREAD

**Issue by Yuzunyannn** [TartaricAcid/TouhouLittleMaid#192]
java.lang.ClassCastException: net.minecraft.item.ItemAir cannot be cast to net.minecraft.item.ItemBlock
at com.github.tartaricacid.touhoulittlemaid.entity.ai.EntityMaidPlaceTorch.updateTask
emmm...，简单看了下，一个小问题
torch.shrink(1)后可能为EMPTY状态
(ItemBlock) torch.getItem()这句话，getItem()如果是EMPTY状态下，get出来的是ItemAir
然后就崩了...............

**Comment by TartaricAcid** [comment]
https://github.com/TartaricAcid/TouhouLittleMaid/commit/5990a650a86a27554ac3e4950bfca2af76b24111
已修复
