### ISSUE TITLE
CrT自定义祭坛生成 脚本使用矿辞作为输入物品后预览显示空白 syntax未报错

### ISSUE THREAD

**Issue by ChromaPIE** [TartaricAcid/TouhouLittleMaid#194]

**Comment by TartaricAcid** [comment]
这 Issues 咋关了？

**Comment by ChromaPIE** [comment]
> 这 Issues 咋关了？

问题误判。现在的问题是祭坛的jei预览里从左至右的第一个槽位对应的是crt自定义祭坛的脚本里次序第二的物品；同样的，第二个槽位对应了脚本的第一个物品ID。其余槽位顺对应序正常。这可能会导致一些专注预览美观性的魔改作者不得不在发现顺序问题之后颠倒一遍首两个物品ID的顺序。另外，脚本似不支持输入物品的NBT？以植物魔法的产能花与功能花测试后，JEI预览为空NBT错误花。不确定是否为模组问题。

**Comment by TartaricAcid** [comment]
暂时先把这个 ISSUES 打开，如果可以的话，希望能提供一下有问题的 ct 脚本代码片段和具体使用的模组，我后续进行查看修复

**Comment by Snownee** [comment]
有时间我修复一下

**Comment by TartaricAcid** [comment]
新版本已经推送更新了，你在 jenkins 里下载下测试版本，看看有没有修复
