### ISSUE TITLE
文本错误

### ISSUE THREAD

**Issue by Coloryr** [TartaricAcid/TouhouLittleMaid#196]
![1](https://user-images.githubusercontent.com/26276037/72881182-3df43200-3d3b-11ea-94ee-b8f8adce9ab6.png)
![2](https://user-images.githubusercontent.com/26276037/72881183-3e8cc880-3d3b-11ea-9f9d-4a1a922f70f4.png)

**Comment by TartaricAcid** [comment]
大哥，都还没写完呢
