### ISSUE TITLE
创造标签页BUG

### ISSUE THREAD

**Issue by RainEffect** [TartaricAcid/TouhouLittleMaid#200]
RT，在游戏客户端中使用了默认设置，但进入了一个设置为扭蛋换皮的服务器时，在创造标签页无法拿取到扭蛋相关物品(创造标签页为空)。

应为：无论客户端的配置为如何，当进入了服务器之后会切换到当前服务器的配置状态。

**Comment by TartaricAcid** [comment]
可能你没接触过具体的代码，创造模式标签页是纯客户端的，所以切换服务器配置显示扭蛋本身就有问题（我客户端标签页为什么要显示服务端便签页，而且其他配置也不一样）
