### ISSUE TITLE
基础功能相关建议

### ISSUE THREAD

**Issue by RainEffect** [TartaricAcid/TouhouLittleMaid#201]
RT，这里将写上一些个人对车万女仆关于基础功能的相关建议：
## 女仆相关
- 为其加入一些枪械模组的支持，例如[“Vic's Modern Warfare Mod”](https://www.curseforge.com/minecraft/mc-mods/vics-modern-warfare-mod) (仅为个人请求)
- 修复CustomNPCs模组相关问题 #211 

## 坐垫相关
- 可对坐垫进行私/公有化设置
- 坐垫模型详情界面增加“允许/禁止坐下”设置
- 为CustomNPCs的模型列表中加入坐垫

## 配置相关
- _检查服务端内配置情况，并为客户端适配好游戏环境情况_ #200 **(已关闭)**

**Comment by TartaricAcid** [comment]
绝大部分问题已修复
NPC 坐垫：暂时不加，因为 Custom NPC 模组识别不了 EntityLivingBase
坐垫“允许/禁止坐下”设置：已经有这个功能了，只不过需要通过资源包来控制
坐垫进行私/公有化设置：坐垫不记录放置者的信息，原则上也不想这样设计
