### ISSUE TITLE
给资源包下载按钮加配置文件

### ISSUE THREAD

**Issue by Jedidiah-Zhang** [TartaricAcid/TouhouLittleMaid#208]
女仆的UI下面那两个按钮说实话有点不好看，玩的时候也没有实际的作用（做整合包的时候才需要），所以希望可以在配置文件中控制显示与否。

**Comment by TartaricAcid** [comment]
这个不打算关闭
声音素材源按钮是遵循原作者的要求，列出的感谢地址，不能删除
资源包下载这么重要的功能更不能关闭
至于美观性，这个 gui 样式倒是可以改，如果可以的话，你倒是能给个不错的图标设计方案

**Comment by Jedidiah-Zhang** [comment]
也不是关闭啊，只是隐藏而已
如果非得放在女仆的ui里的话，可以在上面加一个标签页，这样至少gui不会看着太零碎

**Comment by TartaricAcid** [comment]
样式已经更改
