### ISSUE TITLE
与抽屉同时使用的BUG

### ISSUE THREAD

**Issue by YangxiaQWQ** [TartaricAcid/TouhouLittleMaid#209]
使用交互面板让女仆从抽屉里面拿物品，抽屉里面的东西不会减少，但是女仆会从抽屉里面拿出这个物品。女仆mod版本1.1.9、抽屉mod版本5.3.4，昨天刚发现的这个bug，今天新版本就公布了，不过看酒石酸没有在视频里面说这个bug，所以来这里提交一下。

**Comment by TartaricAcid** [comment]
现在交互面板也没有了，这个问题也不存在了
