### ISSUE TITLE
NPC 女仆工具 页数BUG

### ISSUE THREAD

**Issue by RainEffect** [TartaricAcid/TouhouLittleMaid#211]
RT，车万女仆和CNPC的互通。。。出现了一个很奇怪的BUG（虽然问题不大，不需要急于维修）
## 问题概述
当使用了**NPC魔杖**新建了一个**NPC女仆**后，使用**NPC女仆工具**，可以给这个NPC更换皮肤。

但问题在于，一共11页，可页数显示是从第0页开始，并且总页数为10页。
且当翻页到最后一页时，当点击“上一页”时，会直接从第十页跳到第八页。

## MOD版本
- TouhouLittleMaid 1.1.9
- CustomNPCs 08Jan20snapshot (快照版) [[我的搬运地址]](https://www.mcbbs.net/thread-936521-1-1.html)

**Comment by TartaricAcid** [comment]
已修复
