### ISSUE TITLE
弹幕遇水转向的BUG(较为重要)

### ISSUE THREAD

**Issue by RainEffect** [TartaricAcid/TouhouLittleMaid#216]
RT，讲真，当我发现的那一刻我惊了
![2020-02-04 05-51-15](https://user-images.githubusercontent.com/14258727/73694809-d0b9a700-4713-11ea-850a-8e3ff044de6a.gif)

**Comment by lone-wolf-akela** [comment]
感觉挺有意思的啊当个特性留着呗

**Comment by Yuan-Quan** [comment]
這不是bug, 這是沒有寫在文檔裏的功能

**Comment by TartaricAcid** [comment]
配置文件里面有一条，弹幕是否会受到水流的影响，这个可以选择开启或关闭。只不过新版本还没有发布
