### ISSUE TITLE
扭蛋机BUG（特性？）

### ISSUE THREAD

**Issue by redXpanda** [TartaricAcid/TouhouLittleMaid#217]
在cfg里调整需求物品的数量后（比如调整到10个），如果手中物品不足10个，则会消耗2个然后什么都不发生；改变需求物品的种类后，使用绿宝石还会出现消耗绿宝石且无产出的情况。

**Comment by TartaricAcid** [comment]
扭蛋机现在做的太简单了，后续计划大改下，完善其游戏性

**Comment by redXpanda** [comment]
太棒了。希望可以继续增加可自定义程度和server友好程度。

**Comment by TartaricAcid** [comment]
经过测试，你所反馈的两个问题均不存在，请再次确认操作是否正确（比如修改错了配置文件，以为客户端修改的配置会自动运用到服务端）
