### ISSUE TITLE
女仆的交互面板和InstandUnify冲突

### ISSUE THREAD

**Issue by AnTengye** [TartaricAcid/TouhouLittleMaid#218]
InstandUnify是一个统一矿物词典的mod
我测试了仅装了InstandUnify和TouhouLittleMaid时
给箱子添加交互面板，并设置对应白名单物品，模式为输入，女仆物品栏中加入对应物品。
此时，女仆对面板并没有任何反应。

**Comment by dong031001** [comment]
REFER TO https://github.com/ET-Team/EnigTech2/issues/333

**Comment by Snownee** [comment]
无法理解什么是对应物品。

**Comment by Snownee** [comment]
如果你说的是同一矿词的物品的话，我无法理解这和交互面板有什么关系。InstantUnify支持漏斗输入同一矿物词典的物品吗？我想是不支持的。

另外InstantUnify是一个糟糕的主意，有雄心的整合包作者应该通过使用UniDict和修改配置，来统一所有同类的项目。

**Comment by ChromaPIE** [comment]
> 如果你说的是同一矿词的物品的话，我无法理解这和交互面板有什么关系。InstantUnify支持漏斗输入同一矿物词典的物品吗？我想是不支持的。
> 
> 另外InstantUnify是一个糟糕的主意，有雄心的整合包作者应该通过使用UniDict和修改配置，来统一所有同类的项目。

附议。在实际使用中UniDict可以应用于InstantUnify完全无法解决的问题。如调高某种特定物品的优先级而不是基于特定mod的全局优先。

**Comment by AnTengye** [comment]
> 无法理解什么是对应物品。
仅装了InstandUnify和TouhouLittleMaid时，拿出一个箱子，给箱子加上交互面板，交互面板上面设置一个圆石（换成其他物品也不行）。给女仆物品栏足够的圆石，女仆对箱子没有任何交互反应。

**Comment by AnTengye** [comment]
> 另外InstantUnify是一个糟糕的主意，有雄心的整合包作者应该通过使用UniDict和修改配置，来统一所有同类的项目。

我尝试给整合包的作者提出了这个bug，但是issues被关闭了。。。
我自己有试过用UniDict是完全OK的，但是毕竟玩的是整合包。。。
