### ISSUE TITLE
關於增加資源包的女僕模型卷

### ISSUE THREAD

**Issue by WTFTHEE3** [TartaricAcid/TouhouLittleMaid#219]
照著自定義抽卡 創建draw.csv 並寫入資源包的自定義模型ID後
雖然女僕卷開得出來  可是無法右擊女僕改變對應的模型

**Comment by TartaricAcid** [comment]
右击女仆后模型无变化还是变成了默认的灵梦模型？
如果是前者，可能有细节问题（比如女仆不是驯服的，女仆的主人不是你）
后者的话，说明对应模型材质包你没有加载

**Comment by Yurzi** [comment]
模组版本1.1.9
forge：14.23.5.2847
有同样的问题，创建了draw.csv后 添加新的模型id之后，模型券会出现相应的券，但无法右键女仆使用，使用无反应，不会变成默认，单机测试，确认女仆被驯服。

**Comment by Yurzi** [comment]
添加的是模组内自置的，由snownee制作的模型包。

**Comment by TartaricAcid** [comment]
有相关演示动画么？

**Comment by Yurzi** [comment]
已经确认开启了禁止玩家切换女仆模型的设置
不会制作演示动画（菜）,只能录个视频。
用的百度网盘（暂时想不到其他途径）。

链接: https://pan.baidu.com/s/1Tfs9Q8Bvf1QwBQYaLCqHQA   提取码: aghi

**Comment by TartaricAcid** [comment]
你视频里面用的还是 1.1.9 版本，建议更新 1.1.10 版本测试

**Comment by TartaricAcid** [comment]
已经修复此问题
