### ISSUE TITLE
寻路不正常？A problem of pathfinding ?

### ISSUE THREAD

**Issue by JuYanYan** [TartaricAcid/TouhouLittleMaid#222]
mod版本1.1.9，女仆在面前有铁轨时，不会直接跨过铁轨，而是会选择绕过它。轨道很长，所以她绕了一大段路。

---------------

Mod version: 1.1.9
When there was a track in front of the maid, she did not cross the track, but bypassed it.

**Comment by JuYanYan** [comment]
我自己的Minecraft有[Railcraft](http://www.railcraft.info/)这个mod，我测试了其中的基本轨道(_原版轨道_、_强化轨道_、_高速轨道_、_镀铁轨道_ )以及可以悬空的轨道( _废弃轨道_ )，然后随机选取了几种作改装铁轨进行同样的测试，女仆都会选择绕过它们（一种极端点的情况是，轨道把女仆围起来了，她就不会走出来）

**Comment by lone-wolf-akela** [comment]
原版的所有动物/怪物都不会跨过铁轨（为了防止堵塞交通），应该是女仆直接使用了原版的寻路逻辑导致的。

**Comment by TartaricAcid** [comment]
https://github.com/TartaricAcid/TouhouLittleMaid/issues/77

属于原版特性，请在反馈问题前对原版具有一定了解
