### ISSUE TITLE
对于超过20的装备条

### ISSUE THREAD

**Issue by Jedidiah-Zhang** [TartaricAcid/TouhouLittleMaid#223]
![image](https://user-images.githubusercontent.com/50638143/74473792-815a4000-4ea4-11ea-9741-bf96eedcf745.png)
如图，旁边会有这个白条
并且由于20就满了，20往上的护甲其实是显示不出来的。所以建议变一种颜色从头开始计，或者让最大值可配置。

**Comment by TartaricAcid** [comment]
你装了什么模组，保护值这么大

**Comment by TartaricAcid** [comment]
变色是不错的点子

**Comment by Jedidiah-Zhang** [comment]
匠魂盔甲的
