### ISSUE TITLE
女仆下载额外的模型没有加载

### ISSUE THREAD

**Issue by RGHSSS** [TartaricAcid/TouhouLittleMaid#224]
在游戏中女仆界面的下载额外的模型，下载后并没有加载在女仆的换装界面

**Comment by lone-wolf-akela** [comment]
那个下载的是资源包，要自己去游戏设置里选择加载那些资源包

**Comment by RGHSSS** [comment]
> 那个下载的是资源包，要自己去游戏设置里选择加载那些资源包
我刚刚才发现，所以赶过来准备删了这个问题，但现在有个新问题，如果我和服务器的玩家装了一样的包，并且双方都加载了包，那么更改模型对方会看得到么

**Comment by Snownee** [comment]
加个提示应该会好一点（如果有提示的话当我没说）

**Comment by TartaricAcid** [comment]
改成这样，应该会有人看到了吧

![image](https://user-images.githubusercontent.com/19620085/76698249-a3c9be00-66db-11ea-9974-4680a8482346.png)

**Comment by TartaricAcid** [comment]
> 双方都加载了包，那么更改模型对方会看得到么

会
