### ISSUE TITLE
关于女仆互动的问题

### ISSUE THREAD

**Issue by whilecraft** [TartaricAcid/TouhouLittleMaid#225]
提个建议，希望蛋糕这个物品在女仆手上也能吸引其他女仆并且歪头，这样会给女仆之间也有中互动的感觉，这样会很可爱。     另外就是女仆在坐上一些高度不同的坐垫中眼睛看向玩家的方向似乎有些问题，如果检索的是玩家的脸那么在高脚凳的坐垫上女仆的眼睛就不应该低头看，因为女仆坐上凳子的高度刚好和玩家的眼睛平视，然后我靠近却给我一种低头认错的感觉？      最后一个就是女仆在检测到周围有玩家并且有其他女仆的存在时会不知道看哪里，然后就会脑袋就是鬼畜，疯狂的往玩家和女仆不停的摆头，希望能加一个玩家优先值。         再次提这么多虽然都是些小问题，但是细节决定成败，这个女仆模组也在不断的进步着，希望作者会越做越好。

**Comment by TartaricAcid** [comment]
你这一行字都不分段的么……

> 希望蛋糕这个物品在女仆手上也能吸引其他女仆并且歪头
祈求模式时女仆会跟随的，这个无法采纳

> 女仆在坐上一些高度不同的坐垫中眼睛看向玩家的方向似乎有些问题
确实，但是不太好搞

> 女仆在检测到周围有玩家并且有其他女仆的存在时会不知道看哪里，然后就会脑袋就是鬼畜，疯狂的往玩家和女仆不停的摆头
我这咋就是好的？
