### ISSUE TITLE
红美铃的帽子有Z-fighting现象

### ISSUE THREAD

**Issue by RisingInIris2017** [TartaricAcid/TouhouLittleMaid#226]
Forge 版本: 14.23.5.2847
Touhou Little Maid 版本：1.1.10
如题，这个不是模组本身的Bug，可能更好的做法是向模型作者反馈。
![TIM截图20200217164321](https://user-images.githubusercontent.com/28519848/74664139-1ed0af00-51d8-11ea-837b-4500936f2a65.png)

**Comment by TartaricAcid** [comment]
准备将自带模型遗留问题收入专栏进行修改，此 Issues 关闭
