### ISSUE TITLE
对于服务端的一些建议

### ISSUE THREAD

**Issue by PIPILAN** [TartaricAcid/TouhouLittleMaid#229]
增加自动重载功能，客户端改了直接生效，服务端不行，每次都要重开服务器

**Comment by TartaricAcid** [comment]
刚开始看这段话我理解了半天，才明白你说的重载指的是“配置文件的热重载”

我所知道绝大部分模组，其在服务端都没有配置文件热重载的功能

**Comment by PIPILAN** [comment]
不过对于需要这种微调配置的，还是加入热重载比较好，比如说我想调整P点的掉落数之类的

**Comment by TartaricAcid** [comment]
暂时不添加此功能，绝大部分模组都没有
