### ISSUE TITLE
女仆拾物开启后的bug

### ISSUE THREAD

**Issue by Jedidiah-Zhang** [TartaricAcid/TouhouLittleMaid#23]
拾物模式打开后，如果玩家和女仆同时捡掉落物，掉落物会变成两份，分别出现在玩家和女仆的物品栏里。。。

顺便说一个还没有证实的bug：
有一次标记Home的位置被遮挡后，女仆跑到了离Home三十几格之外的地方，重设了坐标之后才恢复正常。
但是后来做测试的时候，又都没有问题了，所以就不开一个新的issue了

**Comment by TartaricAcid** [comment]
第一个问题很早就已经修复，坐等下次发布
第二个问题没法复现，只能归咎于玄学问题
