### ISSUE TITLE
关于本模组在服务器中玩家无法破坏坐垫的BUG

### ISSUE THREAD

**Issue by PIPILAN** [TartaricAcid/TouhouLittleMaid#230]
我刚刚测试了下，在单人游戏中可以破坏但是服务器无法破坏(shift+左键)
服务端版本是CatServer-a9501ab-async，模组是1.1.0beta，确定配置文件没有开启仅创造玩家可以破坏坐垫
动图链接(11.6MB略大稍等)：https://file.moetu.org/images/2020/02/19/BUGf6630f1d93f90411.gif

**Comment by TartaricAcid** [comment]
服务端是不是开启了禁止敲掉坐垫的配置？

**Comment by PIPILAN** [comment]
并没有，这是服务端配置截图
https://file.moetu.org/images/2020/02/20/QQ20200220101301634b8bb9c2f26579.png

**Comment by TartaricAcid** [comment]
无法查证，请更换纯 forge 端进行验证
