### ISSUE TITLE
秦心的头发有Z-fighting现象

### ISSUE THREAD

**Issue by RisingInIris2017** [TartaricAcid/TouhouLittleMaid#232]
Forge 版本: 14.23.5.2847
Touhou Little Maid 版本：1.1.10
如题，这个不是模组本身的Bug，可能更好的做法是向模型作者反馈。
![TIM截图20200219192406](https://user-images.githubusercontent.com/28519848/74830171-84927780-534d-11ea-97de-b2f327a6f4cc.png)

**Comment by TartaricAcid** [comment]
已经修复
