### ISSUE TITLE
服务器报错日志

### ISSUE THREAD

**Issue by 119Acta** [TartaricAcid/TouhouLittleMaid#233]
[crash-2020-02-19_19.47.18-server.txt](https://github.com/TartaricAcid/TouhouLittleMaid/files/4225031/crash-2020-02-19_19.47.18-server.txt)

**Comment by TartaricAcid** [comment]
你的服务端问题，你的服务端缺失 vecmath 库导致游戏启动失败，请重新下载服务端

**Comment by 119Acta** [comment]
好的
