### ISSUE TITLE
我用的是官网正版的MC，他显示不是最新的java，我按照上面写的去启动器的高级设置改，但是没找到

### ISSUE THREAD

**Issue by 1314pzl** [TartaricAcid/TouhouLittleMaid#234]
我用的是官网正版的MC，我的Java是最新的了，他显示不是最新的，我按照上面写的去启动器的高级设置改，但是没找到，不知道怎么在启动器里面改，作者大大可以告诉我吗，谢谢

**Comment by TartaricAcid** [comment]
![1](https://user-images.githubusercontent.com/19620085/75540449-0756b900-5a57-11ea-9f72-99577918013b.png)
![2](https://user-images.githubusercontent.com/19620085/75540466-0e7dc700-5a57-11ea-8d10-a73d8d22a045.png)
![3](https://user-images.githubusercontent.com/19620085/75540471-0faef400-5a57-11ea-8a7f-711a14b8b29f.png)
![4](https://user-images.githubusercontent.com/19620085/75540475-10e02100-5a57-11ea-8035-3a80a71cc65d.png)
![5](https://user-images.githubusercontent.com/19620085/75540480-12a9e480-5a57-11ea-977e-33896f044401.png)
