### ISSUE TITLE
被横扫之刃的余波扫到的坐垫会被打飞

### ISSUE THREAD

**Issue by Chloe-koopa** [TartaricAcid/TouhouLittleMaid#236]
![image](https://user-images.githubusercontent.com/43518523/75233447-d591e800-57f3-11ea-86ba-cdab9cd903ca.png)
->
![image](https://user-images.githubusercontent.com/43518523/75233462-dd518c80-57f3-11ea-885d-e50fa1c76f8f.png)
模组版本：[mcg特供1.0.0]

**Comment by TartaricAcid** [comment]
已修复
