### ISSUE TITLE
女仆可以利用其他模组刷物品的问题。

### ISSUE THREAD

**Issue by debilh** [TartaricAcid/TouhouLittleMaid#237]
这个是我朋友在一起游玩服务器的时候偶然发现的。
touhoulittlemaid版本为1.1.9
forestry版本为5.8.2.387
buildcraft版本为7.99.24.4
用两个女仆交互面板，一个输入，一个输出，标定好物品后再放相应要刷的物品到女仆背包里就可以实现刷物品。在任何女仆可以走动的模式都是生效的。
目前测试到林业的蜂箱(刷蜜蜂)和bc的高级工作台(刷【任何？】物品)都是有效的，在刷满一组物品后还会以一组一组的形式刷取物品。
![图](https://user-images.githubusercontent.com/46564343/75312214-37099380-5894-11ea-8468-71784bee245e.png)

**Comment by TartaricAcid** [comment]
交互面板已经禁用了
