### ISSUE TITLE
请问，怎么修改祭坛中的效果事件的合成配方

### ISSUE THREAD

**Issue by redXpanda** [TartaricAcid/TouhouLittleMaid#238]
按照自定义祭坛wiki的方法，我不知道怎么填写第三个参数，配方产出。比如生成女仆，生成闪电，复活手办这些配方。

**Comment by TartaricAcid** [comment]
暂时只有物品的合成修改支持，后续尝试考虑任意实体的支持

**Comment by Chloe-koopa** [comment]
> 暂时只有物品的合成修改支持，后续尝试考虑任意实体的支持

或许可以用来召唤末影鸡（雾

**Comment by TartaricAcid** [comment]
已经添加此功能 5f2e69d663c983e01d3cca791671002f6bbf7771
