### ISSUE TITLE
服务器中女仆走丢后找回，随即产生的双女仆问题

### ISSUE THREAD

**Issue by Zyilin98** [TartaricAcid/TouhouLittleMaid#239]
版本是touhoulittlemaid-1.12.2-1.1.9-release
forge版本是2847
服务器核心是CAT（其余信息未知）
在昨天下午上线服务器的时候发现我工作在农场的女仆走丢（当时认为其遭遇不幸）
随即成功召唤新女仆，新的女仆功能上没有问题
随后在今天上午再次上线的时候，离家跑图，在离家20区块左右的水坑里发现了走丢的女仆
该女仆正常跟随 除女仆背包无法打开其余功能正常 带回家后两女仆工作均正常 ，但两个女仆背包都无法打开
随即杀死 走丢女仆，正常掉落手办 女仆背包里原有物品全部遗失（部分装备遗失）
新女仆依然无法打开背包界面，但工作正常

**Comment by TartaricAcid** [comment]
无法复现，难以查证

**Comment by TartaricAcid** [comment]
几个问题需要求证下：
这两个无法打开背包的女仆是不是你的女仆？
因为判定上只有驯服过的，自己的女仆才能够打开背包。
其次，既然工作正常，那么又是如何打开背包的？因为背包界面才可以切换工作模式，这是不是前后矛盾了？

**Comment by Zyilin98** [comment]
确定是我的 因为服务器里拥有女仆的玩家除了腐竹就只有我，其他人均不会使用此模组。这里说的背包
指的是女仆的物品栏和饰品栏
背包主界面是可以正常打开的 也可以选择工作模式
没有表述清楚是我的错，还请见谅

**Comment by TartaricAcid** [comment]
我收到了好几个关于 catserver 服务器下背包无法打开的问题，你试试纯 forge 服务端或者 sponge 服务端。我这边 forge 服务端是好的。

**Comment by Zyilin98** [comment]
这个问题我给腐竹反映过，也曾经辅助他尝试过sponge，但最后还是一直没有更换掉Sponge。多次询问腐竹，腐竹对此事都是闭口不谈。
所以我也很绝望

**Comment by TartaricAcid** [comment]
那我没有办法，catserver 本身设计问题，可能大概率会放大很多不存在的 bug，我目前没有精力维护与它的兼容。
