### ISSUE TITLE
一些建议

### ISSUE THREAD

**Issue by Coloryr** [TartaricAcid/TouhouLittleMaid#24]
1.在多人的时候，玩家不能攻击别人的女仆。  
2.若其他玩家攻击了其他的女仆，主人可以取消其攻击状态。  
3.跨纬度传送女仆。（跑去地狱女仆不跟过来就很烦）  
4.可以让女仆设置成不死。（~~恶趣味~~）

**Comment by Snownee** [comment]
建议下次把建议分条发成 issue

**Comment by TartaricAcid** [comment]
2 已经实现了，只需要切换一次待命就能清除女仆的攻击状态，这一点和原版狼去除攻击状态是一致的

**Comment by Haocen2004** [comment]
我觉得这边第一条可以给增加下判断
服务器pvp关闭时 | 计分板同队且队伍伤害关闭时 | ftbu pvp 关闭时 
这些状态下女仆免疫来源于玩家的伤害

**Comment by TartaricAcid** [comment]
问题已经全部解决
