### ISSUE TITLE
坐垫被冲走穿模坐垫视线问题

### ISSUE THREAD

**Issue by 906535817** [TartaricAcid/TouhouLittleMaid#241]
坐垫被水流冲走或被剑打到后后会穿模甚至是消失不见。坐在坐垫上丢出物品不论视线方向指向永远是往前扔的，使用植物魔法泰拉剑的光束也是一样的问题。

**Comment by TartaricAcid** [comment]
>坐垫被水流冲走消失不见

我这边一切正常，没有试验出来

> 坐在坐垫上丢出物品不论视线方向指向永远是往前扔的

坐垫方面为了同步朝向弄了很多视线同步。不排除物品丢出方向和这个有关系。

几乎也不会有人坐在坐垫上要精准的往某个方向丢东西，暂且不做任何检查和修复。
