### ISSUE TITLE
关于模型资源包的一些小疑问

### ISSUE THREAD

**Issue by chunjienan** [TartaricAcid/TouhouLittleMaid#242]
服务端：CatServer-264808e-async
Mod版本：1.1.10

1. 在祭坛召唤的女仆是何种模型的概率是不是和抽卡的概率一样？
2. 服务端配置文件已开启【禁止玩家更改女仆皮肤】与【禁止玩家更改坐垫皮肤】，客户端未开启该选项，实际进入服务器游戏后，玩家依旧可以自由更改皮肤。请问这是否为特性？
3. 能不能给神秘的傀儡套上女仆的皮肤

**Comment by TartaricAcid** [comment]
1. 不是
2. 有截图或者演示视频么？
3. 不能
