### ISSUE TITLE
关于禁止玩家切换女仆模型缺无效的bug

### ISSUE THREAD

**Issue by Yurzi** [TartaricAcid/TouhouLittleMaid#243]
在forge版本为14.23.5.2847的
forge和MC原版核心文件为一体的（不是正常装forge那样，就直接整合到一起的，服务器常用的）环境下
模组版本 1.1.9及1.1.10均有此问题
在配置中修改禁止玩家切换模型为true之后仍可以切换

**Comment by TartaricAcid** [comment]
有你切换模型时的截图么？

**Comment by Yurzi** [comment]
抱歉，确实是在创造模式下切换的。生存模式是无法切换，sorry
