### ISSUE TITLE
关于在服务器中女仆交互面板的问题

### ISSUE THREAD

**Issue by SUNmode** [TartaricAcid/TouhouLittleMaid#244]
在服务器中，可以通过放置 过滤模式为黑名单（不在黑名单中设置物品），物流模式为输入的女仆交互面板，获取其他玩家的女仆背包内的物品

(就是女仆会往这个面板贴合的容器内放入自己身上的所有物品 )
感觉这个“特性”需要处理一下，比如女仆要和面板交互必须要先绑定之类的。服务器内可能会出现玩家利用这个“特性”恶意窃取其他玩家的女仆物品的情况。
使用版本:
forge:14.23.5.2847
Touhou Little Maid:1.1.10
ps:服务器为海绵（sponge）端

**Comment by TartaricAcid** [comment]
当前面板问题较多，现在暂时搁置后续进行重置，建议先暂时封禁此物品
