### ISSUE TITLE
关于服务器端cfg禁止玩家修改坐垫无效的BUG和在customnpc中添加坐垫的建议

### ISSUE THREAD

**Issue by SoaliGer** [TartaricAcid/TouhouLittleMaid#245]
很高兴服务器端中的添加了禁止修改坐垫的选项，但是我发现服务器端上设置后，需要客户端同步才可以，但是玩家是能够自己修改cfg的，类似于史莱姆变油库里的那个选项，这令我非常头疼，今天还是个塞钱箱起床就变摩托了

关于坐垫兼容customnpc的原因是我希望可以运用坐垫来完成一些npc事件，比如利用夜雀餐店完成玩家购买食物，赛钱箱的每日塞钱提高阵营点数，我记得以前兼容坐垫的可惜没有NPC女仆工具，因为坐垫的模型实在是太精美了，我现在利用NPC骑乘工具让NPC骑在坐垫上面，但是玩家可以修改坐垫模型.....

**Comment by TartaricAcid** [comment]
以前兼容坐垫时候是用的 EntityLiving，后面因为会发生各种问题，改成了 EntityLivingBase

**Comment by TartaricAcid** [comment]
已修复更改模型问题
