### ISSUE TITLE
关于女仆实战与生产中的一些bug和建议

### ISSUE THREAD

**Issue by QuartzZerozss** [TartaricAcid/TouhouLittleMaid#246]
感谢你为此mod所做的努力。我有以下几条问题反馈一下：
模组版本1.1.10beta 游戏1.12.2forge2847 装有jeid
1.女仆在远程攻击模式解决掉敌人后，会返回玩家身边进行无意义的横向运动，这一运动无视悬崖或岩浆湖，会使女仆突然掉下去受伤，有时十分致命。
2.若玩家行动过快，女仆距玩家大概两三个区块后（区块未卸载）无法传送到玩家身边。可能会导致女仆彻底丢失，而且还占用玩家的女仆数量。能否加入一个工具使得玩家可以强制将女仆传送回自己身边（或将自己传送到女仆身边）？
3.女仆即使是远程攻击也依然有时会尝试接近敌人。经常骑脸苦力怕。能否向自定义npc的某些选项那样，加入一个不主动攻击苦力怕的按钮？
4.飞行模式下经常卡方块，且有时打不出弹幕（估计是打到了扫把碰撞箱上）。这是mc自己的问题，但我在想能不能取消被骑扫把的碰撞箱并让女仆以自己为中心处于飞行状态来解决这个问题？
5.女仆即使装备了旗指物依然会受到来自玩家的伤害。有些模组提供的高伤害武器还是会对女仆造成不少伤害。
6.女仆在工作时会耗费大量时间在看其他生物上，经常发生两个女仆忘我的互相凝视。这很可爱，但也很低效。能否提供一个选项来更改女仆对其他生物的兴趣？
7.在一个箱子的正面放置一个交互面板，女仆在从背面接近面板时会突然站在箱子上并深情凝望着面板（就是不放）并停止工作
8.剪羊毛时，羊的毛有时会跳到栅栏上，女仆会深情凝望着羊毛掉落物（就是捡不到）能不能让女仆工作时将所有收获物直接放入女仆背包中而非掉落？
9.能否加入重叠模式？比如让女仆平时种田，并在发现敌人时自动反击。
10.在少数情况下，女仆坐在本mod提供的坐垫上时身体不断往一侧扭（脖子不错2333）在gui中也显示不正常。坐在其它实体上时也有可能触发此问题。
11.在少数情况下，女仆死亡信息显示不正常。（显示为xxx.xxxxxx.xxx，x指字母，具体内容我忘了）
最后感谢你做出这么可爱的mod！

**Comment by QuartzZerozss** [comment]
对了，女仆还会轻易踩坏瓜田（就是站在瓜上跳到田上踩坏田）

**Comment by QuartzZerozss** [comment]
又发现一个问题，女仆无法识别某些mod中的作物，如沉浸工程的工业大麻（成熟后两格高）只能种不能收。

**Comment by TartaricAcid** [comment]
1. 已修复

2. 我测试，只要女仆所处区块没有卸载，即使距离七八个区块也会正常传送，请检查你所认为的“区块未卸载”是否属实。
    > 能否加入一个工具使得玩家可以强制将女仆传送回自己身边    

       此问题本身真实性存在疑问，故此后续想法也不予以考虑

3. 目前还没有好的想法为女仆添加攻击怪物的白名单黑名单

4. 飞行模式本来就不打算设计成女仆主要的行为方式，在没有较大问题的情况下，暂不予以修复

5. 玩家伤害在装备旗指物后仍然存在是游戏本身设计故意而为止，否则旗指物的造价就不会那么便宜了。
  伤害走的是原版的系统，如果部分模组不遵循原版的设计，自然旗指物也无法抵御其造成的伤害。如果可以，建议给这些作者反馈下，让他们严苛遵循统一的原版标准设计模组。

6. 更改了互相看 AI 的设计，只有空闲模式下才会触发，其他工作模式下此功能不启用

7. 看起来是寻路方面出了点问题，鉴于面板本身问题比较多，先暂时搁置。

8. 不打算这么做，太过 OP。
  但是后续可以考虑添加饰品，能够像磁力指环一样吸收周围的掉落物，避免此问题。

9. 女仆本身就打算设计成多个女仆互相协作，不打算将其设计的太过智能，而是建议玩家多个工作模式的女仆互相配合使用。（这也是为什么要细分那么多种植模式的原因）

10. 这个渲染问题我尝试过很多解决办法，暂时无解，触发原因和解决办法也不清楚。（如果你对此有所了解或者发现，非常感谢协同解决此问题，我也挺头疼）

11. 我新版本更改了死亡信息提示，也许会解决这个问题

12. 这个我回头看看怎么规避

13. 同问题 5，我走的原版的 ICrop 系统，如果作者严苛遵循原版设计理念，基本上收获是没问题的（比如潘马思的作物就能正常识别种植收获）。建议给沉浸工程作者反馈下，让他严苛遵循统一的原版标准设计模组。
