### ISSUE TITLE
关于车万女仆与日站女仆的皮肤包与音效包是否兼容的提问

### ISSUE THREAD

**Issue by okatu-loli** [TartaricAcid/TouhouLittleMaid#247]
您好，请问
Q1:车万女仆支不支持[这个模组](https://www.mcbbs.net/thread-932911-1-1.html)的皮肤包和音效包呢？
Q2:如不不支持，请问能不能想办法兼容呢？
（ps：我在外地，身边没有电脑进行测试，如果打扰到了您的生活，请见谅！）

**Comment by TartaricAcid** [comment]
这个问题提的非常好，首先先说一下这个模组诞生的原因之一

去年夏天时候本来想重新做一期日站女仆模组教程，结果发现它的女仆皮肤包制作非常复杂，只有连个选项：
1. 固定模型，只是换皮肤材质。这样做限制太多，无法充分自定义
2. 更换模型。这个自定义程度高，但是需要一整个女仆模组的开发环境，并且对  forge 模组开发有一定了解才能做出自定义模型包，门槛实在是太高。

而且皮肤和音效包的安装太过于麻烦，需要丢进 mods 文件夹，重启游戏才能使用。

然后我花了一个星期时间自己写了个这个模组出来。

鉴于此，问题 1 和 2 就很明晰了。

**Comment by TartaricAcid** [comment]
问题 2 的另一个回答方式
虽然格式上不兼容日站女仆模型包，但是你可以仿制它的模型来制作自己的 TLM 女仆模型包，而且比日站模型包制作更加人性化，简单。

当然，请记得使用别人材质前询问授权，否则建议你制作原创模型
