### ISSUE TITLE
女仆渲染实体报错，会导致客户端崩溃

### ISSUE THREAD

**Issue by BurgessYT** [TartaricAcid/TouhouLittleMaid#248]
[报错详情](https://shimo.im/docs/HKkKTd3PqkkvtKXc/)
女仆mod版本 1.1.9 (不确定1.1.10是否修复了这个问题 )

**Comment by TartaricAcid** [comment]
这不是渲染实体出错，是女仆面板出现的问题

当前女仆面板问题较多，建议禁用
