### ISSUE TITLE
发现一个bug

### ISSUE THREAD

**Issue by okatu-loli** [TartaricAcid/TouhouLittleMaid#249]
蜘蛛会攻击妖精女仆，我的女仆在开启攻击模式后不会攻击敌对生物
不知道这是bug还是特性
版本1.1.10beta

**Comment by TartaricAcid** [comment]
蜘蛛会攻击妖精女仆：那是因为妖精女仆的弹幕打到了蜘蛛而已
女仆开启攻击模式后不会攻击敌对性生物：有视频或者其他佐证么？什么类型的敌对生物，你是怎么做的，怎样没有触发攻击？

**Comment by okatu-loli** [comment]
不知道为什么今天无法复现了，和昨天是同一个存档emmm

**Comment by okatu-loli** [comment]
对了，今天我偶然在B站看到一个网站http://cpmmod.top/，请问是否兼容车万女仆？看介绍是通过JSON文件自定义玩家模型https://www.bilibili.com/read/cv4571429/

**Comment by Logic530** [comment]
> 对了，今天我偶然在B站看到一个网站[http://cpmmod.top/，请问是否兼容车万女仆？看介绍是通过JSON文件自定义玩家模型https://www.bilibili.com/read/cv4571429/](http://cpmmod.top/%EF%BC%8C%E8%AF%B7%E9%97%AE%E6%98%AF%E5%90%A6%E5%85%BC%E5%AE%B9%E8%BD%A6%E4%B8%87%E5%A5%B3%E4%BB%86%EF%BC%9F%E7%9C%8B%E4%BB%8B%E7%BB%8D%E6%98%AF%E9%80%9A%E8%BF%87JSON%E6%96%87%E4%BB%B6%E8%87%AA%E5%AE%9A%E4%B9%89%E7%8E%A9%E5%AE%B6%E6%A8%A1%E5%9E%8Bhttps://www.bilibili.com/read/cv4571429/)

不兼容，cpm使用的是自己特殊的格式

**Comment by TartaricAcid** [comment]
无效问题，关闭
