### ISSUE TITLE
最新版本的显示bug

### ISSUE THREAD

**Issue by QuartzZerozss** [TartaricAcid/TouhouLittleMaid#251]
一些原版两格高花朵（如向日葵）出现显示（？）错误
![2020-03-24_11 40 37](https://user-images.githubusercontent.com/62364026/77386002-af487380-6dc4-11ea-977c-c4f5d55319dc.png)
![2020-03-24_11 40 41](https://user-images.githubusercontent.com/62364026/77386004-b40d2780-6dc4-11ea-81fe-5f065973c6af.png)
上图中第二张图是截下第一张图后发生的。下层突然消失，一段时间后上层也消失了。
一些原版一格高花朵有时也会浮空。很快就会消失，甚至来不及截图。

**Comment by QuartzZerozss** [comment]
补充一下：
本模组更新前没有此问题。
自己放置的两个高花朵不会发生同类问题，只有自然生成的一部分花有此类现象。
浮空花朵消失后不会掉落本身。

**Comment by TartaricAcid** [comment]
删掉本模组后有没有类似问题？

**Comment by QuartzZerozss** [comment]
> 删掉本模组后有没有类似问题？

删除后未能重现此问题。但我刚刚在仅装有此模组的情况下也未能重现此问题。。。

我又排查了其他模组，但都没再找到过。。。

考虑到这些浮空花很快就消失了，估计我可能是没看到。

**Comment by QuartzZerozss** [comment]
我觉得我应该还没说清楚。

最初是我装了一些mod玩，此模组更新后我带着其他模组开了新档测试，发现刚出生时周边有很多浮空的花，这些花有选择框，周边放置或破坏方块会消失，自己过一段时间也会消失。

只有在创造模式下飞的比较快时才在新加载的区块发现同样的问题。
但我现在再测试时没找到。

可能是影响了世界生成？或许也可能是奇奇怪怪的模组兼容问题，我现在也很困惑。

**Comment by TartaricAcid** [comment]
_(:з」∠)_ 感觉我就是个背锅侠……
