### ISSUE TITLE
与RTM真实火车共同载入导致的崩溃

### ISSUE THREAD

**Issue by SakuraWuhen** [TartaricAcid/TouhouLittleMaid#252]
FORGE版本：14.23.5.2847

当RTM真实火车与车万女仆在客户端同时载入时，会在初始化阶段引起RTM的崩溃
[crash-2020-03-25_16.55.35-client.txt](https://github.com/TartaricAcid/TouhouLittleMaid/files/4379893/crash-2020-03-25_16.55.35-client.txt)

辛苦了，车万女仆和酒石酸都是最棒的！

**Comment by TartaricAcid** [comment]
看了下，是 RTM 模组本身的设计问题。

它识别文件系统存在问题，把女仆模型的资源描述问题误识别为了火车模型。

建议解决方法（以下方法任选一条）：
> 1. 删除 RTM 模组
> 2. 删除本模组
> 3. 将问题反馈给 RTM 作者，并等待对方修复识别问题。
