### ISSUE TITLE
关于皮肤与属性关联的建议

### ISSUE THREAD

**Issue by SaltGin** [TartaricAcid/TouhouLittleMaid#253]
作者大大你好！

最近有在试玩这个MOD 目前在服务器上大约运行了这个MOD大约有2个星期了 在游玩过程中思考了一番 决定过来提出一部分建议

在服务器上运行时我是一直开启禁止皮肤更换模式的 这样霖之助的作用就不仅限于提供P点了 但是相应的问题是 即使皮肤分为多个稀有度分级 也并没有对应的奖励机制 就比如相应更高级的UR 提供的生命值和攻击力会更高 这样子

如果像这样 战力和稀有度成正比的话就很棒了！如果有心一点按正作里的战力去划分 想必也是相当有能的！但是如果看修改的工作量来说 目前最方便的方法是以稀有度划分

其实还有一点相当小的提议（如果新开一个issue可能显得比较浪费git的资源）就是建议女仆不用御币也可以进行弹幕攻击 不然实在是太违和了...

以上，
大大辛苦了！

**Comment by Logic530** [comment]
~~我不知道我天天混在这个仓库的Issues里干什么XD~~

总之根据943在B站发布的消息，皮肤扭蛋这块做得不是很满意，会重做或修改。

我个人对于皮肤扭蛋这部分也觉得不是特别好，根本上来说女仆能改变皮肤这个设计就不是很好，因为这把女仆的外表和本质剥离开了，让女仆显得就是一个 _套壳的工具_ 。

当然这么设计是为了防止玩家召唤不出想要的女仆。

**Comment by TartaricAcid** [comment]
> 更高级的 UR 提供的生命值和攻击力会更高

实际上我甚至想删掉抽卡部分的内容，我总是对抽卡这个设定有厌恶感。

> 女仆不用御币也可以进行弹幕攻击

我拒绝，已经够 op 了

**Comment by SaltGin** [comment]
了解了 提出来是因为实测女仆在一对多甚至二对多的战斗上很不占优势 即使是装有旗指物和护甲的情况下
~~但是主要原因估计是因为服务器里装了僵尸意识 一来一大群~~
