### ISSUE TITLE
关于女仆皮肤系统的一点建议

### ISSUE THREAD

**Issue by Logic530** [TartaricAcid/TouhouLittleMaid#254]
之前在B站看到消息说打算 重做/修改 皮肤系统，同时我也觉得现在的皮肤系统不是很合适，再加上碰巧我对此有了一点想法，故来说两句。

我觉得皮肤系统的不合适，根本在于皮肤可以切换。心理学这方面我不是很懂，但是我觉得女仆作为一种吉祥物，外表需要是唯一且不可变的，这样玩家才可以对其寄托情感。或者说外表需要是女仆的一种不可变的**根本属性**，否则女仆的根本属性就只剩下了自动种地。说得简单一点就是：如果皮肤可以换，那么你老婆和我老婆没有区别，都是工具人。总之，我觉得**皮肤不可切换更好**。

当然，当初设计可以切换是为了防止玩家召唤不到自己想要的女仆，所以把皮肤设为不可切换的同时，要让玩家能够选择召唤的女仆。

那么如何选择召唤的女仆又是一个问题。做成GUI的话，还是点点鼠标就能决定女仆是谁，似乎也不是很好。~~不卖关子了XD~~

我对此的设想是对每个女仆设计一个对应的 召唤物/信物，用召唤物可以召唤对应的女仆，每种召唤物的合成配方不同，配方可以选择一些与女仆相关的、成本合适的材料。这样既可以给予玩家选择的权力，玩家通过收集材料也能加强对女仆的情感寄托，相对的没有之前所说的女仆工具人的问题。

不过这样设计有几个问题：
- 每个女仆都有一个召唤物，物品太多，材质绘制工作量大
- 女仆资源包里的女仆怎么办？
- 女仆太多，配方难设计

第一个问题的话其实很好解决。~~偷懒就行了。~~ 可以先使用同一个材质，只是物品名称不同，“XX的信物”这样。之后如果有确实需要再分别绘制。
第二个问题我认为最简单的方法是对所有非原生女仆都使用同一个通用的信物（通用信物有单独的一个配方），通用信物召唤出的女仆可以在所有女仆包的女仆间切换。当然后续也可以加入自定义信物的功能。
第三个问题我也不知道怎么办，感觉原版物品应该足够用于设计配方吧，实在不行加几个中间物品也行。

当然，可以保留GUI切换皮肤的功能，通过配置文件设置使用哪一种皮肤系统。

以上是我的全部建议，希望能有所帮助。

**Comment by TartaricAcid** [comment]
> 之前在B站看到消息说打算 重做/修改 皮肤系统

是的，正如你所见，我已经把新版本皮肤加载系统搞完了。

> 我也觉得现在的皮肤系统不是很合适

但是我觉得还挺不错的

看完评论，说几点我的看法：
1. 首先高度评价你的建议，有几个设计点很不错，我觉得后续可以考虑实现；
2. 自由切换女仆功能绝不会禁止，只会设计成可配置的，不喜欢的可以主动关闭；
3. 第三方资源包的女仆切换功能着实是个问题，目前并不好解决。
