### ISSUE TITLE
关于女仆农场模式的问题和建议

### ISSUE THREAD

**Issue by Logic530** [TartaricAcid/TouhouLittleMaid#255]
~~我又来了XD~~

### 先是问题

直接上图
![2020-03-27_15 26 18](https://user-images.githubusercontent.com/22793670/77732992-0d818a80-7041-11ea-80cc-008efcfd111d.png)
![2020-03-27_15 26 21](https://user-images.githubusercontent.com/22793670/77732999-0f4b4e00-7041-11ea-8124-4a5e38d4abf2.png)

图中女仆均设置为农场模式，Home模式均为打开，坐标绑定如图所示，并都给予了一组种子。
问题出现在左边的女仆并不会开始种植。
右边的女仆可以正常种植，并且工作范围得到了应有的限制。

并不是什么大问题，因为只要像右边那样设置就可以了，但是我认为大部分玩家设置的时候都会像左边那样设置，左边那样设置也更便捷和符合直观。~~很多玩家可能并不会发现右边的解决方法~~
个人~~瞎猜~~推测问题的发生可能与耕地方块不足一格高有关。

### 然后是建议

我觉得农场模式可能是最实用，也是玩家使用最多的模式，但是目前存在一些细节的问题影响了这个功能的使用体验：

+ 如果使用女仆交互面板让女仆输出收获的作物（例如马铃薯这种种子和果实相同的）最终女仆会将全部的作物输出到箱子里导致停产
+ 类似上面的问题，如果种植的是小麦（种子和果实不同的）最终种子会占满女仆物品栏导致无法收获
+ 如果女仆的工作范围里有多种作物，最终女仆会将所有的耕地都种上同一种作物，取决于哪一种作物占据了女仆物品栏的第一格

对于上面的第一个和第三个问题，我认为可以通过简单地修改工作逻辑完美解决，只要让女仆收获作物后**立即**补种上**对应的**作物（而不是物品栏第一格的作物），之后在进行别的动作即可。这样女仆会优先保证种植，不会把所有作物都输出到箱子里。

~~至于第二个问题我不知道有什么简单的解决办法，可能需要一些稍微复杂的逻辑，例如有交互面板可以输出种子时，保留一组种子，多余的输出之类的。~~
第二个问题其实也可以通过上面的方法解决，只要设置两个交互面板，一个输出小麦，一个输出种子即可。

以上是我的全部反馈，希望有所帮助。

~~再多说一句，我觉得图中的“当前模式：设置范围”改成“坐标模式：设置范围”的话更好，不然易理解为女仆工作模式。~~

**Comment by TartaricAcid** [comment]
问题：
很简单，手册里面提一句即可，我觉得把耕地包含进去更加符合直觉（因为你是检测耕地啊）

建议：
女仆面板目前问题非常多，我打算重新设计

**Comment by Logic530** [comment]
~~如果我直接拿着左边不能工作的图来反馈，943会不会修复呢~~

我认为把耕地包含进去不符合直觉的原因之一是，如果圈地时要包含耕地，那么必须要把耕地的角落挖掉一块才能圈到，这样操作并不方便。我觉得大多数玩家应该会直接在耕地对角上点两下。

这些也确实不是大问题，等重做后再说。

**Comment by TartaricAcid** [comment]
> 如果我直接拿着左边不能工作的图来反馈，943会不会修复呢

我会这样回复：你没有圈住耕地，所以无法工作。然后关闭此 Issues。


> 我认为把耕地包含进去不符合直觉的原因之一……

我认为把耕地包含进去符合直觉


> 这些也确实不是大问题，等重做后再说

已经重做了，所以我关闭此 issues
