### ISSUE TITLE
 关于帕秋莉前置Mod的一个问题的提示和建议

### ISSUE THREAD

**Issue by i493052739** [TartaricAcid/TouhouLittleMaid#257]
经过测试，安装帕秋莉模组以后，Pam's (潘马斯)丰收Mod会出现崩溃问题，但崩溃的原因不会被定位到任何Mod中（这也是经过很久的二分测试一个个摘出来的。。）
原因在于帕秋莉Mod在读取其他模组合成方式的时候与一部分模组存在冲突（目前只测试了Pam's）
但不排除其他更多的Mod会出现问题（因为在外网看到有更多的Crash-Report反应了有些客户端在没有Pam's只有帕秋莉和其他Mod依然出现同样错误报告的情况）

【问题描述】
客户端在使用快捷键，或拖动合成时偶然性崩溃，该类崩溃直接导致毁端，并且会传染
    如：在一个玩家偶然合成BUG物品崩溃后，他下一次上线无论是否合成BUG物品，必定会触发BUG。导致毁端。如果身边有人尝试复现此BUG，仍然会出现越来越多的相同问题，且无指向任何可以MOD。

【问题详情分析】
https://www.mcbbs.net/forum.php?mod=viewthread&tid=722609&page=48#pid16208409

【同类问题的受害者】
https://minereapers.enjin.com/mobile/forum/viewthread/m/4993703/id/29757700-crash-to-desktop-on-openign-inventory/viewthread/27769122-stuck-in-bed
https://forum.gamer.com.tw/C.php?bsn=18673&snA=104167&page=40
https://paste.feed-the-beast.com/view/4d0aad3e
https://www.mcbbs.net/thread-833466-12-1.html
https://www.minecraftforge.net/forum/topic/73016-rendering-screen-issue-while-crafting/
https://www.minecraftforum.net/forums/support/java-edition-support/2997587-getting-this-error-on-modded-server
https://github.com/Vazkii/Quark/issues/837

【建议】
这个关于Pam's和帕秋莉的问题在mcbbs中也只有几个服主发现了，但那些受害Mod的作者貌似并没有关注这个问题，也没有几个人尝试下手更改或者提示玩家这些潜在的致命BUG。。
https://www.mcbbs.net/forum.php?mod=viewthread&tid=722609&page=54#pid16675730
希望能在Mod加载时提示玩家帕秋莉与Pam's等其他模组的兼容性问题，至少这个事情应该由帕秋莉来解决，但是目前没有。

最后，感谢开发，你们太赞了。

**Comment by TartaricAcid** [comment]
我不是很想解决这个问题，因为它的的确确和我一点关系也没有……
