### ISSUE TITLE
关于mcbbs上的常见问题解答中的疑惑之处。

### ISSUE THREAD

**Issue by YoungBoron** [TartaricAcid/TouhouLittleMaid#258]
> 女仆和玩家同时坐在船上，玩家射箭会伤到女仆：你可以试试和其他生物也同时坐上船上，也会触发类似问题。
> **还等什么啊，赶紧轰炸 Mojang 反馈 bug 啊**
> 女仆寻路无法跨过铁轨：同上，你可以试试原版的僵尸、骷髅、狗、猫等生物的寻路，也无法跨过铁轨
> **还等什么啊，赶紧轰炸 Mojang 反馈 bug 啊**
> 在洞穴中骑扫帚，碰着顶部有可能会卡进方块受到伤害：同上，你可以试试在洞穴中骑马，你看碰着顶部时候会不会受到卡进方块的窒息伤害。
> **还等什么啊，赶紧轰炸 Mojang 反馈 bug 啊**
> 

这是否意味着，如果mojang在1.16或更高版本修复了这个bug，模组会考虑版本迁移呢？

**Comment by TartaricAcid** [comment]
我自己都不知道我会不会更新高版本，你们倒是可以帮我预测下

这个问题属于无关问题吧，我就 close 了
