### ISSUE TITLE
記憶中的幻想鄉的介面

### ISSUE THREAD

**Issue by DarkSmallK** [TartaricAcid/TouhouLittleMaid#259]
如題，在全螢幕下的時候書本上可以調顯示大小，不過調了兩回之後發現書本卡在右下角根本點不到，書本的位置跑掉，只能從大概的位置去條回來

**Comment by TartaricAcid** [comment]
这是 patchouli 模组本身的问题，这里有原作者的仓库，请用英文向原作者 vazkii 进行反馈。
https://github.com/Vazkii/Patchouli
