### ISSUE TITLE
关于女仆踩在樱模组的落叶行走问题

### ISSUE THREAD

**Issue by Moshang666** [TartaricAcid/TouhouLittleMaid#260]
樱模组的落叶会使行走在落叶上的女仆出现转圈圈
[Minecraft 1.12.2 2020-04-15 18-10-02.zip](https://github.com/TartaricAcid/TouhouLittleMaid/files/4480577/Minecraft.1.12.2.2020-04-15.18-10-02.zip)

**Comment by TartaricAcid** [comment]
寻路算法把不完整方块当做不可越过的方块，原版的所有生物均会出现此问题。
这严苛来说没有必要解决。
