### ISSUE TITLE
沒有跑出女僕的動畫

### ISSUE THREAD

**Issue by DarkSmallK** [TartaricAcid/TouhouLittleMaid#261]
如題，不管是讓女僕待機還是女僕的眨眼睛的動畫都沒有跑出來，但是朋友的都有，我是不是有調到什麼選項嗎....

**Comment by TartaricAcid** [comment]
你使用的 Java 8 版本比较老，需要 Java 8 u60 及以后版本

> 但是我更新了 Java 啊，怎么还是不行

因为你用的是官方启动器，官方启动器需要修改配置才能切换 Java 版本

> 官方启动器……怎么改 Java 版本的来着？

按这个来：
https://github.com/TartaricAcid/TouhouLittleMaid/issues/234
