### ISSUE TITLE
和科技枪(Techguns)Mod冲突

### ISSUE THREAD

**Issue by zorc** [TartaricAcid/TouhouLittleMaid#262]
和科技枪(Techguns)Mod冲突，两者并存时女仆模型会花掉

**Comment by TartaricAcid** [comment]
经过测试，并无此问题

![001](https://user-images.githubusercontent.com/19620085/79850819-07d85400-83f7-11ea-8b5c-bd02e1cf3479.png)

**Comment by TartaricAcid** [comment]
使用版本如下：
车万女仆：`1.2.0-alpha`
科技枪：`2.0.2.0_pre3.1`
