### ISSUE TITLE
P点消失

### ISSUE THREAD

**Issue by hsh778205** [TartaricAcid/TouhouLittleMaid#263]
从第三个门进地狱时发现了如下的事情（前两个门没看）

进入地狱前，P点是满的（5.00）

进入地狱，没看

**出来，P点显示没了（0.00）**

**点庭灯-全部存入，能存进去5点**

然后就恢复正常了

MC=1.12.2  forge=1.12.2-14.23.5.2838

谢谢

**Comment by TartaricAcid** [comment]
是客户端服务端同步问题，也就是 P 点存在了服务端，但是没有同步到客户端。

虽说只是显示方面的小问题，但是我下个版本修复

**Comment by TartaricAcid** [comment]
https://github.com/TartaricAcid/TouhouLittleMaid/commit/91efc5823d4151d5da233745c8889755933a8d05
已修复
