### ISSUE TITLE
车万女仆能实现类似旧版本女仆里的多关节模型皮肤包吗？

### ISSUE THREAD

**Issue by erer00gg** [TartaricAcid/TouhouLittleMaid#264]
关于女仆的模型，个人总觉得直膝盖直手臂的模型是有极限的。普通女仆皮肤看起来类似Q版，多关节模型类似正常比例，那么多关节的模型可能在车万女仆里还原出来吗？

个人还是很希望想这样的模型能够出现在车万女仆里的
![20200512-161910404_20200512162254](https://user-images.githubusercontent.com/58005561/81651921-020de580-946e-11ea-823b-1f4945ccc2cf.gif)

**Comment by Logic530** [comment]
以我个人对这个项目的理解，先回答一波。

首先我认为你的这个设想，在目前这个阶段应该是没有实现的可能。

最主要的原因当然是技术上困难，工作量大。实现这样的动画应该意味着动画部分要全部重做。据我观察这个项目主要是943一人在维护，难以完成如此大量的工作。

另有一个重要的原因是，本模组最大的特色之一是第三方女仆模型包，如果进行这样的修改，目前的所有第三方女仆包都会无法使用。并且，更加复杂的模型和动画会增大第三方模型包的制作难度。

以我个人的审美，我觉得目前的Q版形象其实优于偏写实的形象。毕竟方块的表现力有限，追求写实将会付出大量的工作，吃力不讨好。Q版形象则可以在付出较少工作的同时达到最好的视觉效果。

当然，也可以在模组里加入两套模型并存。

以上是我的个人理解，仅供参考，欢迎交流。

**Comment by TartaricAcid** [comment]
模型可以自定义，而且可以使用 JavaScript 制作自定义动画，所以原则上来说，你想做什么模型、动画，就能做什么模型动画。

所以这个问题的答案就是：是的，可以实现类似**日站**女仆的多关节皮肤模型包
