### ISSUE TITLE
关于音乐播放的建议

### ISSUE THREAD

**Issue by harrynhj** [TartaricAcid/TouhouLittleMaid#266]
不知道能不能在模组配置里增加网络代理相关选项，否则海外党好多歌曲都无法播放

**Comment by TartaricAcid** [comment]
因为用的是 paulscode soundsystem 库实现的音乐播放，这个库封装性比较好，没有相关代理功能，所以目前无法实现此功能。

不过你可以挂全局代理，但是会比较麻烦。
