### ISSUE TITLE
会给女仆添加“Blocklings”小方块那样的的砍树、挖矿功能吗？

### ISSUE THREAD

**Issue by bili777** [TartaricAcid/TouhouLittleMaid#267]
以后会给女仆添加“Blocklings”小方块那样的的砍树、挖矿功能吗？个人希望女仆的作用能更大一点。
另外我最近在摆手办时发现毒人偶梅蒂欣·梅兰可莉的模型没了，希望酒石酸菌添加一下

**Comment by TartaricAcid** [comment]
会，但是需要时间

我查看下，可能是更新模组时候误删除了模型。

**Comment by bili777** [comment]
好，辛苦了，希望这个mod越来越好
