### ISSUE TITLE
右键女仆的菜单界面点不开

### ISSUE THREAD

**Issue by ChrisFSRM** [TartaricAcid/TouhouLittleMaid#268]
一直使用的是hmcl启动器，没有增删mod。重新合成了女仆也解决不了

**Comment by lone-wolf-akela** [comment]
你给女仆喂蛋糕驯服她了么？

**Comment by ChrisFSRM** [comment]
女仆mod已经用了一段时间了，突然就右键失效了。重新生成后，右键还是失效，蛋糕也喂不了

**Comment by TartaricAcid** [comment]
有视频佐证么？
以及，女仆在判定打开 GUI 时候会检索玩家的 UUID，如果玩家 UUID 发生了变化，那么先前的女仆肯定是不允许进行任何操作的。

如果是国际版正版用户，UUID 是永远不变的，但是离线模式下，UUID 大多是启动器自动生成的，你看看你是不是改了什么用户名，导致你的 UUID 发生了变化。

**Comment by ChrisFSRM** [comment]
那就是这个原因。我最近才购入国际版，以前是离线模式。那重新合成女仆有用吗（还是说其他解决办法），我之前一直是从手办中复活

**Comment by TartaricAcid** [comment]
都不行，女仆哪怕死亡了，复活仍然会记住玩家 uuid，你只能用原版的结构方块右击女仆来强行转换主人

**Comment by ChrisFSRM** [comment]
解决了，谢谢
