### ISSUE TITLE
建议规范一下分支

### ISSUE THREAD

**Issue by redXpanda** [TartaricAcid/TouhouLittleMaid#269]
至少分一下dev分支和master吧？一个版本打一个tag也好。开发到一半或者未经测试的代码提到master总感觉不太好（其实是我同步代码不方便

**Comment by TartaricAcid** [comment]
我提交到 github 的代码，都是经过测试，或者开发完毕一部分的的，适合推送到 master 的。

至于开发到一半或者未经测试的代码，我会直接留存到本地，而不会推送
