### ISSUE TITLE
放置任意chair后出现报错

### ISSUE THREAD

**Issue by redXpanda** [TartaricAcid/TouhouLittleMaid#270]
服务器后台开始刷报错，信息：
/*  StackTrace :                                                                                             */
/*     java.lang.IllegalStateException:                                                                      */
/*     Intended to capture dropped item                                                                      */
/*     entities! Please analyze the current                                                                  */
/*     phase context.                                                                                        */
/*     org.spongepowered.common.event.tracking.TrackingUtil.lambda$throwWithContext$4(TrackingUtil.java:384) */
/*     org.spongepowered.common.event.tracking.PhaseContext.getCapturedItems(PhaseContext.java:406)          */
/*     net.minecraft.world.WorldServer.func_175647_a(WorldServer.java:4810)                                  */
/*     net.minecraft.world.World.func_72872_a(World.java:3068)                                               */
/*     com.github.tartaricacid.touhoulittlemaid.entity.item.EntityChair.func_85033_bc(EntityChair.java:95) 
环境：
/* Minecraft : 1.12.2                                                                                        */
/* SpongeAPI : 7.2.0-d871149cb                                                                               */
/* Sponge : 1.12.2-7.2.2                                                                                     */
/* SpongeForge : 1.12.2-2838-7.2.2                                                                           */
/* Minecraft Forge : 14.23.5.2847  
mod版本为master最新编译。
chair上和附近没有任何实体，即使人坐上去也不会停止。打掉chair恢复正常。

**Comment by TartaricAcid** [comment]
我查看了下此处代码，调用的是原版 `net.minecraft.world.World#getEntitiesWithinAABB(java.lang.Class<? extends T>, net.minecraft.util.math.AxisAlignedBB)` 方法，但是我并没有对这个方法做任何修改，而且也是正常的调用，所以我实在不明白一个普普通通的原版方法调用为何会报错，除非 sponge 本身对这个方法做了什么我所不知道的修改。

**Comment by redXpanda** [comment]
> 我查看了下此处代码，我调用的是原版 `net.minecraft.world.World#getEntitiesWithinAABB(java.lang.Class<? extends T>, net.minecraft.util.math.AxisAlignedBB)` 方法。
> 但是我并没有对这个方法做任何修改，而且也是正常的调用。
> 所以我实在不明白一个普普通通的原版方法调用为何会报错，除非 sponge 本身对这个方法做了什么我所不知道的修改。

我估计也是sponge的锅，实在不行我回退sponge版本吧。

**Comment by redXpanda** [comment]
换用spongeforge7.2.0后可以了。

**Comment by TartaricAcid** [comment]
那看起来就是 sponge 的锅了
