### ISSUE TITLE
关于女仆模组农场模式的与实用拓展兼容问题

### ISSUE THREAD

**Issue by luobolb** [TartaricAcid/TouhouLittleMaid#273]
近日发现女仆模组农场模式对于实用拓展两种作物——油菜和水稻收获时产出错误。
两者本应分别产出油菜和稻米
而女仆收获时分别掉落了实用拓展的纸杯和奶酪
望知悉，若有必要，后续会补充截图等材料

**Comment by TartaricAcid** [comment]
已经修复
