### ISSUE TITLE
Game crash when player opens a Portable Audio's GUI

### ISSUE THREAD

**Issue by RisingInIris2017** [TartaricAcid/TouhouLittleMaid#274]
### MOD版本 - Mod version:
1.12.2-1.2.2-release

### Forge版本 - Forge version:
14.23.5.2854

### 单人/多人游戏？ - Singleplayer or Multiplayer:
单人游戏和多人游戏均发生此现象。
在同一多人游戏中，**仅这名玩家**打开音响GUI会崩溃；
这名玩家**以同一ID启动单人游戏**，打开音响GUI也会崩溃。

### 完整的MOD列表 - Installed mods:
https://paste.ubuntu.com/p/Z4tFH7kDwh/

### 崩溃报告
https://paste.ubuntu.com/p/vT3K9PpTvx/

### 问题描述 - Description of the problem
产生Bug的步骤 - How to reproduce:
1. 这名玩家启动游戏，打开女仆手提音响GUI，此时没有问题。
2. 这名玩家添加了一个网易云歌单。
3. 这名玩家再次打开手提音响，游戏崩溃。
4. 这名玩家退出多人游戏，回到单人游戏中打开音响，游戏崩溃。
5. 检查这名玩家所在服务器的服务端，
包括 `config/touhou_little_maid` 目录，`config/TouhouLittleMaid.cfg` 文件，
这名玩家的 `world/playerdata/<uuid>.dat` NBT 数据文件，均未能发现存放歌单相关设置的地方。

现在的情况是，这名玩家一旦开启手提音响 GUI 就会导致客户端的崩溃，
而我又不能明确在哪里可以帮助他将歌单设置恢复为默认值。
在此不仅请求开发者们修复这一问题，还要请求告知将歌单设置恢复的方法，
给这名玩家一个应急处理崩溃问题的方式。
非常感谢！

**Comment by TartaricAcid** [comment]
打开音响的崩溃问题是玩家输入了错误的歌单，误把 userid 当做了歌单 id 输入了进去，而恰好这个歌单又是存在的（但是没有歌曲），导致加载了一个空歌单，进而导致游戏崩溃。

歌单存储在 C 盘/用户/[你现在操作系统的用户名，一般为 Administrator]/touhou_little_maid/music_list 文件，删掉重启游戏即可

**Comment by RisingInIris2017** [comment]
> 打开音响的崩溃问题是玩家输入了错误的歌单，误把 userid 当做了歌单 id 输入了进去，而恰好这个歌单又是存在的（但是没有歌曲），导致加载了一个空歌单，进而导致游戏崩溃。
> 
> 歌单存储在 `C 盘/用户/[你现在操作系统的用户名，一般为 Administrator]/touhou_little_maid/music_list` 文件，删掉重启游戏即可

非常感谢你的及时回复！
这个问题如果能在之后的版本设法避免就好了。

**Comment by TartaricAcid** [comment]
下个版本就修复

**Comment by TartaricAcid** [comment]
已修复
