### ISSUE TITLE
女仆种植甘蔗好像不兼容子沙

### ISSUE THREAD

**Issue by MrFengzhou** [TartaricAcid/TouhouLittleMaid#275]
我在使用女仆的种甘蔗的时候，女仆不会在Snad模组中的子沙上面种植

**Comment by TartaricAcid** [comment]
一万个模组会有十万种修改原版行为的可能性，所以兼容全部的模组既不可能，也没有必要。

只需要原版和部分常见模组兼容方面不存在问题即可。

所以不兼容才是合理的。

**Comment by MrFengzhou** [comment]
> 一万个模组会有十万种修改原版行为的可能性，所以兼容全部的模组既不可能，也没有必要。
> 
> 只需要原版和部分常见模组兼容方面不存在问题即可。
> 
> Snad模组作为一个冷门模组，不兼容才是合理的。

好的，我已经把子沙换成了原版的沙子。酒石酸辛苦了
