### ISSUE TITLE
关于服务器坐垫报错

### ISSUE THREAD

**Issue by hhhfsj** [TartaricAcid/TouhouLittleMaid#276]
https://paste.ubuntu.com/p/Tgqnq654gR/

**Comment by hhhfsj** [comment]
forge：forge-1.12.2-14.23.5.2854
spongeforge：spongeforge-1.12.2-2838-7.2.3
touhoulittlemaid：touhoulittlemaid-1.12.2-1.2.2-release

**Comment by AlioDream** [comment]
同样问题：https://paste.ubuntu.com/p/d5mrxpgsHc/
/* Minecraft : 1.12.2
/* SpongeAPI : 7.2.0-e4abe364d
/* Sponge : 1.12.2-7.2.3
/* SpongeForge : 1.12.2-2838-7.2.3
/* Minecraft Forge : 14.23.5.2838
touhoulittlemaid-1.12.2-1.2.2-release
Mods：https://paste.ubuntu.com/p/FBCH5RCcbd/

**Comment by TartaricAcid** [comment]
换用 spongeforge7.2.0 。
