### ISSUE TITLE
1.12.2版本下似乎和RTM有冲突

### ISSUE THREAD

**Issue by wuya-mkjy** [TartaricAcid/TouhouLittleMaid#277]
女仆版本     touhoulittlemaid-1.12.2-1.2.2-release
NGTLib        NGTLib2.4.18-35_forge-1.12.2-14.23.2.2611
RTM            RTM2.4.20-39_forge-1.12.2-14.23.2.2611
Forge          forge-1.12.2-14.23.5.2854

应该可以确定是女仆和RTM的问题
只留这两个依然崩溃
能进游戏，能进世界，但是一加载到有关的物品就会崩溃
       操作上是打开背包，创造模式往后翻页或者搜索往下滚或者JEI往下滚，到接近似乎是女仆物品的范围时崩溃，大约看到了水
       晶状的饰品
如果留了帕秋莉手册，进世界物品栏里有手册，但右键打开就会崩溃
单独留女仆或者RTM都能正常用
留女仆和NGTLib可以正常运行
[crash-2020-08-10_04.17.56-client.txt](https://github.com/TartaricAcid/TouhouLittleMaid/files/5048355/crash-2020-08-10_04.17.56-client.txt)

**Comment by wuya-mkjy** [comment]
报告的entity里不止出现过水车
其他几次崩溃里也有别的
只有最后一次崩溃没留别的mod
[crash-2020-08-10_02.14.00-client.txt](https://github.com/TartaricAcid/TouhouLittleMaid/files/5048359/crash-2020-08-10_02.14.00-client.txt)

[crash-2020-08-10_04.02.30-client.txt](https://github.com/TartaricAcid/TouhouLittleMaid/files/5048358/crash-2020-08-10_04.02.30-client.txt)

[crash-2020-08-10_03.17.31-client.txt](https://github.com/TartaricAcid/TouhouLittleMaid/files/5048356/crash-2020-08-10_03.17.31-client.txt)
[crash-2020-08-10_04.00.01-client.txt](https://github.com/TartaricAcid/TouhouLittleMaid/files/5048357/crash-2020-08-10_04.00.01-client.txt)

**Comment by wuya-mkjy** [comment]
看到类似的issue了
估计是一样的问题
准备放弃RTM 不知道有没有类似的铁路mod推荐？mcbbs上逛了一圈同类只看到一个沉浸铁路

**Comment by TartaricAcid** [comment]
类似问题：#252

原因：RTM 识别火车模型没有做判定，把女仆模型的资源描述问题误识别为了火车模型，导致加载失败。

建议解决方法（以下方法任选一条）：
> 删除 RTM 模组
> 删除本模组
> 将问题反馈给 RTM 作者，并等待对方修复识别问题。
>
