### ISSUE TITLE
打开女仆背包看照片模型不全

### ISSUE THREAD

**Issue by hsh778205** [TartaricAcid/TouhouLittleMaid#279]
_【这是老版本的一个问题，如果已经修复，请忽略我】_

打开女仆背包看（自己背包中的）照片时，照片中的人物模型显示不全，只会显示翅膀&手持物品

（若是打开自己的背包看当然不会有问题）
![image](https://user-images.githubusercontent.com/51521470/89853854-0492ef00-dbc5-11ea-8afb-dc515e35d638.png)

![image](https://user-images.githubusercontent.com/51521470/89853879-107eb100-dbc5-11ea-8a08-1ec45713852b.png)

版本真的很早：touhoulittlemaid-1.12.2-1.2.0-alpha

**Comment by TartaricAcid** [comment]
这个 bug 之前就发现了，但是那时候没有细查原因。

**Comment by TartaricAcid** [comment]
这个问题在 1.2.4 的更新中已经修复
