### ISSUE TITLE
女仆无法和农业工艺的作物架互动。。。。

### ISSUE THREAD

**Issue by zwfengineer** [TartaricAcid/TouhouLittleMaid#280]
小女仆无法使用农业工艺mod[https://www.mcmod.cn/class/514.html]的作物架[https://www.mcmod.cn/item/37532.html]，希望作者能添加这个功能。至少让他们学会怎么从作物架上收获成熟作物。
肥肠感谢。。。。。。。。

**Comment by TartaricAcid** [comment]
可以作为附加功能，但不优先考虑
