### ISSUE TITLE
部分女仆不眨眼问题

### ISSUE THREAD

**Issue by TheEmptyDuckstache** [TartaricAcid/TouhouLittleMaid#284]
在其他女仆眨眼的时候,部分女仆却不会眨眼,但紫的间隙中的眼睛会眨眼(虽然她不会眨眼,似乎是一个彩蛋?我不知道.)能否对这个问题进行修复?

**Comment by TartaricAcid** [comment]
因为是早期模型，所以把眨眼效果修改到了隙间上

**Comment by TartaricAcid** [comment]
准备将自带模型遗留问题收入专栏进行修改，此 Issues 关闭
