### ISSUE TITLE
史诗攻城MOD对该mod的ai有影响

### ISSUE THREAD

**Issue by Jacksun329** [TartaricAcid/TouhouLittleMaid#287]
如题，当同时使用史诗攻城mod时，女仆在使用弓或御币时不是使用射击或弹幕攻击，而是会拿着这两种道具“敲击”目标
该mod的两种敌对生物和爬行者都不再被稻草人驱逐
该mod的两种敌对生物都不再攻击女仆

**Comment by TheEmptyDuckstache** [comment]
史诗攻城里有设置,你可以设置受模组影响的实体清单.

**Comment by TartaricAcid** [comment]
史诗攻城模组对绝大部分生物的 AI 都强行进行了修改，你可以通过修改那个模组的配置文件来避免修改
