### ISSUE TITLE
一些对该mod的建议

### ISSUE THREAD

**Issue by Jacksun329** [TartaricAcid/TouhouLittleMaid#288]
猫车等载具可添加功能让玩家拉着女仆走
可以让女仆使用镜符攻击
可以让女仆工作模式多开并自动进行最近任务
女仆在空闲状态受到生物工具可以让女仆自动取出背包中武器进行反击
当女仆使用的工具损坏时，可以让女仆自动从背包中拿出同类工具进行工作

**Comment by TartaricAcid** [comment]
> 猫车等载具可添加功能让玩家拉着女仆走

未来也许会出专门的自定义载具

> 可以让女仆使用镜符攻击

那是什么？

> 可以让女仆工作模式多开并自动进行最近任务

我觉得现在工作模式太全能了，不但不打算这么做，甚至还想细分下工作模式

> 女仆在空闲状态受到生物攻击可以让女仆自动取出背包中武器进行反击

可以考虑

> 当女仆使用的工具损坏时，可以让女仆自动从背包中拿出同类工具进行工作

可以设计为饰品功能
