### ISSUE TITLE
客户端崩溃：ClassCastException: java.lang.Boolean cannot be cast to java.lang.String

### ISSUE THREAD

**Issue by RisingInIris2017** [TartaricAcid/TouhouLittleMaid#290]
### Forge 版本：
14.23.5.2854
### TLM 版本：
touhoulittlemaid-1.12.2-1.2.2-release
### 问题描述：
在某个区块召唤女仆之后，靠近这个区块的玩家都会出现客户端崩溃的情况。
### 崩溃报告的链接：
https://paste.ubuntu.com/p/r9CGrDh6th/

**Comment by yaoxiaosa** [comment]
我也有同样的问题，迫切需要解决，召唤女仆后服务端没有任何报错，而客户端在女仆身边的人会崩溃

**Comment by TartaricAcid** [comment]
我实在不知道为何女仆存储的模型 id 会莫名其妙变成布尔值的，要么你更新下模组试试。

**Comment by yaoxiaosa** [comment]
已经尝试过最新版本1.2.3，出现同样的问题，估计是和什么模组冲突了吧，呜呜呜

**Comment by TartaricAcid** [comment]
这个问题非常奇怪，因为模型 id 肯定是字符串，这种简单的错误绝不可能犯，而且这块地方以及正常运行好半年了，所以肯定是有什么别的模组篡改了女仆的数据，强行把它改成了布尔值

**Comment by yaoxiaosa** [comment]
估计是什么服务器插件问题吧，因为单机状态下能正常运作

**Comment by yaoxiaosa** [comment]
也不对，插件没有进行更换，10几天前还可以正常运作

**Comment by yaoxiaosa** [comment]
好兄弟们解决了，原因是帕秋莉模组1.0-20版本和最新版的女仆在服务器就会崩溃掉，换成1.0-21就可以了
