### ISSUE TITLE
用Metamorph mod变身成女仆时的几个问题

### ISSUE THREAD

**Issue by galahadplayer** [TartaricAcid/TouhouLittleMaid#294]
1.在玩家变身成女仆且背包装满的情况下，仍可拾取物品，只是捡起的物品会直接消失
2.在玩家变身成女仆的情况下，乘坐椅子类或载具类时模型显示位置不对(用第二、三人称时)
![2020-10-04_12 31 42](https://user-images.githubusercontent.com/71592120/95007172-2f3a7a80-063f-11eb-926c-625237ba3077.png)
![2020-10-04_12 31 50](https://user-images.githubusercontent.com/71592120/95007176-3497c500-063f-11eb-9441-7c3e827b3ea8.png)
上图为一般情况
下图为座座垫时，模型显示比实际碰撞箱低了一些

**Comment by TartaricAcid** [comment]
> 1.在玩家变身成女仆且背包装满的情况下，仍可拾取物品，只是捡起的物品会直接消失
啊，所以这和 Touhou Little Maid 模组有什么关系啊……（你是在生存模式下捡起的物品么？希望能提供更加详细的信息）

> 2.在玩家变身成女仆的情况下，乘坐椅子类或载具类时模型显示位置不对(用第二、三人称时)
我也发现这个问题了，看看后面能不能修复

**Comment by galahadplayer** [comment]
关于第一个问题的详细情况：(生存模式)
假设我的背包36格全部放满泥土，现在地上有一个石头，在玩家变身成女仆时可以捡起石头，但石头就不见了；同样条件下变身成其他模组的生物或实体时就无法捡起石头

**Comment by TartaricAcid** [comment]
看起来 Metamorph 模组的代码哪块出问题了，Metamorph 模组是有 github issues 反馈地址的，你去给原作者反馈下他模组的问题吧

**Comment by galahadplayer** [comment]
行
