### ISSUE TITLE
女仆好感度暴跌问题

### ISSUE THREAD

**Issue by TheEmptyDuckstache** [TartaricAcid/TouhouLittleMaid#295]
我的女仆好感度总是莫名其妙的暴跌至负数万,可我也并没有把她们放在岩浆上烤啊.

**Comment by G41mywaifu** [comment]
我当时家具摆放是直播站紧贴着床  大概是因为传送的原因 导致女仆站在了直播站的椅子背上  此时女仆的好感度迅速下降 一分钟左右变成了-8w

**Comment by TartaricAcid** [comment]
属于 1.12 设计上的问题，1.16 不会再有此问题了（因为 1.16 所有的生物 mojang 都给添加了睡觉属性，判定不再容易出问题了）

1.12 我也不打算修了
