### ISSUE TITLE
这本书沒有中文

### ISSUE THREAD

**Issue by dep0717** [TartaricAcid/TouhouLittleMaid#298]
請问我哪裡錯了??
![Minecraft 1 12 2 2020_11_21 上午 11_10_27](https://user-images.githubusercontent.com/74804452/99866216-454dcb80-2bea-11eb-8b42-dc673d83538e.png)

**Comment by TartaricAcid** [comment]
目前模组翻译还没有人提交繁体中文，所以只有简体中文的翻译

**Comment by dep0717** [comment]
谢谢!
