### ISSUE TITLE
对于弹幕系统的一些建议

### ISSUE THREAD

**Issue by lizhanyiawa** [TartaricAcid/TouhouLittleMaid#302]
个人非常喜欢东方主题的mod，对于弹幕来说也只是稍微有些想法，这里只是提一些小的建议。
  1.希望对弹幕的模型进行优化，毕竟看着札弹就是一个片，某些弹幕只是一张平面图片怪怪的......蝶弹可以适当加一些动画（掉帧警告）
  2.自定义符卡希望在游戏内加一个GUI，写好的符卡也可以放在.minecraft文件下，可以与其他人共享
  3.符卡希望加更多的动画效果
  非常感谢！

**Comment by lizhanyiawa** [comment]
然后的话，希望符卡播放可以带一些动画......（甚至可以是东方正作右上角的符卡名称或者是类似则的符卡六芒星阵等等）
可以自定义一些子弹，毕竟单发单发打总觉得怪怪的......这个地方感觉可以塞NBT整个弹幕道具什么的。
增加关于人物的一些道具，（例如妖梦的白楼剑，幽香的伞，咲夜的时停表和飞刀等）这个比较费时间，毕竟模型要一个一个做......

**Comment by lizhanyiawa** [comment]
魔炮建议单独加一个八卦炉的道具吧233说不定给女仆用也挺好的？

**Comment by TartaricAcid** [comment]
我还是觉得弹幕实在是太吃服务器计算压力了，我后续还想移除一部分内容

**Comment by TartaricAcid** [comment]
已经计划在 1.16 版本中移除锄普通弹幕外的一切弹幕
