### ISSUE TITLE
有关女仆上限问题

### ISSUE THREAD

**Issue by michaelng1129** [TartaricAcid/TouhouLittleMaid#304]
我知道配置设定里面可以设置每个人的女仆拥有上限。
请问作者女仆的记录是在地图档的那个文件夹里面，我找一遍都没看见。
在我的服务器，有些人的女仆被kill指令杀掉 ，掉落物也没有，我想重置那个人的女仆上限，有方法吗？

**Comment by TartaricAcid** [comment]
女仆数量属于玩家的 cap 系统，所以你不能通过简单的方法修改、

但是模组提供了修改玩家女仆数量的指令啊，/tlm 指令
