### ISSUE TITLE
关于多人模式的一个小想法

### ISSUE THREAD

**Issue by joe-vettek** [TartaricAcid/TouhouLittleMaid#311]
有些朋友一起玩的时候不熟悉，就死了，但是开局送的东西就没了，就是那个记忆中的幻想乡和魂符。
请问是否可以添加前三次复活时再次赠送的功能或者告知下如何使用管理员指令给他重新发一下。
谢谢。
不方便开创造模式。

**Comment by TartaricAcid** [comment]
这几个东西都是可以在创造模式标签页里面直接可以找到的物品。所以对于传统的服务器，想要送一个普通的物品有 10086 中方法可以做到，而且功能更加全面强大。      
完全不需要设计一个全新的指令，这样做是画蛇添足。

从你的问题中看出你似乎并不熟悉基础的服务器指令和插件，所以建议你学习下基础相关内容

**Comment by joe-vettek** [comment]
刚开始不知道
