### ISSUE TITLE
[建议] CrT 添加祭坛合成时，如遇配方 ID 重复，改用 CrT 默认的 HASH 数字代替重复的 ID

### ISSUE THREAD

**Issue by RisingInIris2017** [TartaricAcid/TouhouLittleMaid#313]
### TLM 版本
1.2.4
### 问题描述
如 Issue 标题所示。
目前版本，使用 CraftTweaker 添加 TLM 祭坛合成配方时，如遇配方 ID 重复，
CrT 会只添加这些配方中排在 ZS 脚本最末尾的一个，而位于这个配方之前的重复 ID 配方都不会被添加。
考虑到配方 ID 重复往往是大量的复制粘贴代码，然后只改了配方输入输出，
忘记修改这些配方中部分或全部的配方 ID 所致，
在这种情况下排查丢失的配方比较困难。
如果“改用 CrT 默认的 HASH 数字代替重复的 ID”比较困难，
在检测到有祭坛合成配方 ID 重复时，直接让 CrT 报错也不失为一个好选择。

我的建议就是这样。
感谢你的耐心阅读，期待你的回复！

**Comment by TartaricAcid** [comment]
ID 的目的是为了删除已有合成用的，所以设计成了语义化可读的。

避免 ID 重复也完全可以通过脚本来排除，所以我不打算这样设计。而且 1.12 也不打算更新了，只做一些 bug 修复和兼容性更新。至于 1.16 那就直接上数据包了，也不打算用 ct 了
