### ISSUE TITLE
[Bug] 1.12 版本 draw gui 指令总是提示：“模型包未与服务器同步”

### ISSUE THREAD

**Issue by DJQ28** [TartaricAcid/TouhouLittleMaid#316]
在游玩车万女仆的时候，在服务器添加了额外的资源包让女仆有了更多模型，
然后我禁用了自由切换皮肤，这时候模组自动启用了抽奖模式，
但是这个模式里，只有原模组自带的模型兑换券，没有添加资源包的模型兑换券。

这种情况下能不能添加资源包里的抽奖券，
我试过本模组自带的/draw gui,但是没用。
提示模型包未与服务器同步，请等待同步后再使用此指令

**Comment by TartaricAcid** [comment]
这是目前的 bug，前段时间因为各种原因导致没有精力修复此 bug，会在之后尝试修复。

**Comment by TartaricAcid** [comment]
已修复 https://ci.covertdragon.team/job/TouhouLittleMaid/233/
