### ISSUE TITLE
安装资源包后崩溃

### ISSUE THREAD

**Issue by galahadplayer** [TartaricAcid/TouhouLittleMaid#317]
安装额外的女仆模型包后，随便按一个键盘上的键，游戏就崩了。把其他模组全部移除还是一样，只要资源包没有移除，按键盘就会崩。

**Comment by TartaricAcid** [comment]
有错误报告么？发一份

**Comment by galahadplayer** [comment]
多试了几次，发现可能是其他模组的设定档或是其他模组本身冲突到，移除或修改就没事了
