### ISSUE TITLE
favorability

### ISSUE THREAD

**Issue by sophienix** [TartaricAcid/TouhouLittleMaid#318]
how do I get the favorability up I cant find it anywhere besides cheating in the creative favorability items but I don't want to do that

**Comment by TartaricAcid** [comment]
![1](https://user-images.githubusercontent.com/19620085/125088838-61ae6200-e100-11eb-9771-8c06ee0df0c3.png)
![2](https://user-images.githubusercontent.com/19620085/125088949-7ee33080-e100-11eb-9361-8dd2e96c697e.png)
![3](https://user-images.githubusercontent.com/19620085/125089007-8b678900-e100-11eb-8800-500c867d3cff.png)

emmmmmemmmmmmmm, I really don’t know how to remind players...

**Comment by sophienix** [comment]
i cant find it
