### ISSUE TITLE
missing item

### ISSUE THREAD

**Issue by sophienix** [TartaricAcid/TouhouLittleMaid#319]
i can find the maid interaction hud item i think thats what its called its a item that lets them put items in chests is this a bug or did it get removed cause i cant find it in jei this is the last issue i had

**Comment by Logic530** [comment]
It is removed due to a item duplication bug.

**Comment by sophienix** [comment]
ah ok that sucks couldn't you guys fix it? if not then what version it it in cause i need it cause the maids keep on planting sugar cane and getting lost cause of it

**Comment by sophienix** [comment]
also if you add this to serv tech ages and use farming mode it give you free wooden gears if they break hemp

**Comment by sophienix** [comment]
couldnt you fix it ?

**Comment by TartaricAcid** [comment]
In the latest version, an bauble is designed to let the maid input/output items in the chest

**Comment by TartaricAcid** [comment]
> also if you add this to serv tech ages and use farming mode it give you free wooden gears if they break hemp

I designed a configuration file to fix this kind of bug, you only need to modify this file
https://github.com/TartaricAcid/TouhouLittleMaid/blob/1.12.2/src/main/resources/assets/touhou_little_maid/config/crop.json
