### ISSUE TITLE
[1.12.2] 玩家 NBT 中的 owner_maid_num 子项只增加不减少

### ISSUE THREAD

**Issue by RisingInIris2017** [TartaricAcid/TouhouLittleMaid#320]
### 游戏版本
1.12.2
### Forge 版本
14.23.5.2855
### TLM 模组版本
1.2.4
### 如何复现
1. 进入存档，用任意手段获取一个女仆。
2. 退出存档，关闭游戏。用 NBTExplorer 观察 `<uuid>.dat\ForgeCaps\touhou_little_maid:owner_maid_num` 子项，其值为 1。
3. 进入存档，杀死女仆。
4. 退出存档，关闭游戏。用 NBTExplorer 观察 `<uuid>.dat\ForgeCaps\touhou_little_maid:owner_maid_num` 子项，其值仍为 1。
### 附加文本
在实际游玩过程中，这个问题表现为：当一个玩家曾经获得过的女仆数量，达到配置文件中规定的上限值后，
这个玩家无法再召唤任何女仆，也不能重生死去的女仆。
当这个玩家的女仆全部死亡后，这个玩家将不可能再拥有女仆，非常破坏玩家的游戏体验。

在这里先感谢你耐心阅读了反馈，期待你的回复。

**Comment by TartaricAcid** [comment]
设定如此，女仆死亡并不会减少数据，因为本来就没有加判断

**Comment by TartaricAcid** [comment]
另外，是提供了指令来设置玩家拥有的女仆数量的，并非完全不可修改
