### ISSUE TITLE
1.16.5-1.0.0-13版本车万女仆疑似跟Xaero小地图冲突

### ISSUE THREAD

**Issue by Rinko1231** [TartaricAcid/TouhouLittleMaid#321]
崩溃报告：https://paste.ubuntu.com/p/t5vCpTGgqs/
使用的是是茶会整合包里的1.16.5车万女仆
我和我的同学试着把mod文件放进了我们的服务器（forge36.2.2）里（我不知道这是否合规），结果当天晚上，他表示无法靠近有女仆的地方，一靠近客户端就会崩溃。
我并没有崩，不过我只能移除车万女仆，于是问题解决。
可以看到有一行是
Caused by: java.lang.NullPointerException
	at com.github.tartaricacid.touhoulittlemaid.client.model.BedrockModel.func_205072_a(BedrockModel.java:345) ~[?:?]

**Comment by TartaricAcid** [comment]
看了下错误报告，似乎是这样的：
1. 小地图模组尝试在地图上渲染女仆的头像
2. 但是女仆头部有可能为空（这很显然，因为女仆是支持自定义模型的）
3. 小地图模组没有做 null 检查，它认为头部一定存在
4. 游戏崩溃了

解决办法：Xaero小地图模组我没用过，我建议把小地图模组更换为旅行地图，旅行地图用户量大，功能全面，可能更具优势
