### ISSUE TITLE
i cant find the Chinese website

### ISSUE THREAD

**Issue by sophienix** [TartaricAcid/TouhouLittleMaid#326]
i heard theres a Chinese website where can i find it ? i saw in the comments there is a Chinese website

**Comment by YumekoCourier** [comment]
maybe this?:https://tlmwiki.cfpa.team/zh/

**Comment by TartaricAcid** [comment]
Are you talking about mcbbs?

**Comment by sophienix** [comment]
it was in the chat ssome one said there is a Chinese web site for this mod

**Comment by sophienix** [comment]
it was this 
![image](https://user-images.githubusercontent.com/74495871/134855722-457e0481-f874-4fba-a3c9-1bc046fa15ce.png)

**Comment by TartaricAcid** [comment]
This comment is wrong, you can directly download to the snapshot version of the mod in release.
https://github.com/TartaricAcid/TouhouLittleMaid/releases
