### ISSUE TITLE
1.16.5无法放置女仆

### ISSUE THREAD

**Issue by YumekoCourier** [TartaricAcid/TouhouLittleMaid#329]
不懂就问,是不是因为mod不支持java 11/16

**Comment by YumekoCourier** [comment]
用指令生成女仆会显示an unexpected error occurred trying to execute that command

**Comment by TartaricAcid** [comment]
请给出详细的游戏日志

**Comment by YumekoCourier** [comment]
没事了,是跟游戏内其他mod产生了冲突.已经解决了
