### ISSUE TITLE
[Bug] 1.12 Tombstone Bauble duplication glitch

### ISSUE THREAD

**Issue by Sereath** [TartaricAcid/TouhouLittleMaid#331]
Found a duplication glitch every time your maid has the Tombstone Bauble and dies to anything.

Recorded a short video of me replicating the glitch:

https://youtu.be/18Ltnnp8Wjw

**Comment by sophienix** [comment]
what modpack and minecraft  forge version are you using ? cause it could be the modpack and or the minecraft forge version

**Comment by sophienix** [comment]
cause i have a simular problem with serv tech ages when the maid harvested sertan crops she gave out gears

**Comment by Sereath** [comment]
Unreleased modpack being developed by me.

Modlist:
https://gist.github.com/Aeron216/a091d83eb58a07c17622c1305ecfa049

Forge 2855

Touhou version: 1.2.4

**Comment by Sereath** [comment]
Downgrading to forge 2854 did nothing.

And I also just noticed that as soon as you retrieve the items and the maid from the tombstone, a clone of them also falls to the ground:

![2021-10-05_02 52 32](https://user-images.githubusercontent.com/54506307/135983474-b965513d-dbb9-4e4b-83f0-0459bea49f65.png)

Very unfortunate that this lovely mod has such a game breaking bug.

**Comment by TartaricAcid** [comment]
~~Tombstone bauble has been tested many times, and I can almost be sure that this is not the reason on my side.~~
~~I have encountered similar problems before, without exception: other mod **triggered multiple death events**.~~
~~You need to check the mod you use.~~

**Comment by TartaricAcid** [comment]
@sophienix 
> cause i have a simular problem with serv tech ages when the maid harvested sertan crops she gave out gears

Your problem is not the same as the current issues

**Comment by Sereath** [comment]
Just a follow up. I did a binary search until there was no mod left but this one:

https://youtu.be/g-rOAr7OLVU

https://youtu.be/R5-yFvm84VA

Understandable if nothing can be done about it right now. I'll see if I can remove the recipe with CraftTweaker.

Logs:

debug.log
https://gist.github.com/Aeron216/e4132d310c2001d8f539e626d279ed31
latest.log
https://gist.github.com/Aeron216/d2153ef098d3627d18bfa07af29c6866

**Comment by TartaricAcid** [comment]
fix in https://github.com/TartaricAcid/TouhouLittleMaid/commit/b2911481ae59797656c50beca1550a0d3839eb29
