### ISSUE TITLE
Sevtech Ages maid gives gears bug

### ISSUE THREAD

**Issue by sophienix** [TartaricAcid/TouhouLittleMaid#332]
Sorry about this I know I asked this question before, but I can't find it. How do I fix the maid in Sevtech ages? she is giving out gears when she harvest crops. it's not in my history I checked.

**Comment by TartaricAcid** [comment]
Just modify this file: https://github.com/TartaricAcid/TouhouLittleMaid/blob/1.12.2/src/main/resources/assets/touhou_little_maid/config/crop.json

**Comment by TartaricAcid** [comment]
```json
{
  "actuallyadditions:item_misc": {             // block id
    "id": "actuallyadditions:item_misc",     // harvest crops id
    "meta": 13                             // harvest crops meta
  }
}
```
