### ISSUE TITLE
[Bug] Beta version update custom model animations cause issues on server end

### ISSUE THREAD

**Issue by ScoutTheSaneless** [TartaricAcid/TouhouLittleMaid#333]
when uploading the mod onto a server instance, it apparently causes issues due to model animations. this is kind of an issue for me in particular, since i'm using the maids as representations of my follower-base
[latest.log](https://github.com/TartaricAcid/TouhouLittleMaid/files/7290927/latest.log)

**Comment by TartaricAcid** [comment]
I don’t know what version of the mod you are using

But I have tested the 1.16 animation many times, I suggest you try the latest version of the snapshot
