### ISSUE TITLE
1.12.2 请问还有可能看到女仆收取农业工艺的作物架上的作物吗？

### ISSUE THREAD

**Issue by joe-vettek** [TartaricAcid/TouhouLittleMaid#336]
我看到issue里在去年9月有说这个功能不会被优先考虑，随后被关闭，不过时至今日仍然没有看到这个功能。请问这件事情还有可能吗？
如果确实没有这个打算我就把农业工艺给删除了。。。。不能交互怪不舒服的。

**Comment by joe-vettek** [comment]
希望能给个明确的回复，谢谢啦。

**Comment by TartaricAcid** [comment]
1.12 不会再更新了
