### ISSUE TITLE
[Bug] Touhou Little Maid（touhou_little_maid）在done事件阶段遇到错误

### ISSUE THREAD

**Issue by Edel-Lilies** [TartaricAcid/TouhouLittleMaid#340]
### Minecraft Version

- [ ] 1.12.2
- [X] 1.16.5

### What happened?

1.install
2.啟動遊戲
3.報錯
我在我個人的整合包裡添加了touhoulittlemaid-1.16.5-1.0.0,之後遇到了啟動錯誤
[crash-2021-10-17_01.47.55-client.txt](https://github.com/TartaricAcid/TouhouLittleMaid/files/7358034/crash-2021-10-17_01.47.55-client.txt)
於是我扔進測試服務端試啟動也出現了錯誤
[crash-2021-10-17_03.36.31-server.txt](https://github.com/TartaricAcid/TouhouLittleMaid/files/7358058/crash-2021-10-17_03.36.31-server.txt)

**Comment by TartaricAcid** [comment]
你发了两个崩溃日志，原因各不相同
第一个是和 Untranslated Items 模组的冲突，Untranslated Items 模组直接魔改了原版的语言包系统，导致了加载出错，目前不太好解决，你只能选择删掉 Untranslated Items 模组
第二个已经在 https://github.com/TartaricAcid/TouhouLittleMaid/releases/tag/snapshot-2021101704191634444380 修复
