### ISSUE TITLE
[Bug] 1.16 Shift 点击取下女仆护甲时，女仆的护甲值没有变化

### ISSUE THREAD

**Issue by PTALTS-LK** [TartaricAcid/TouhouLittleMaid#342]
### Minecraft Version

- [ ] 1.12.2
- [X] 1.16.5

### What happened?

1.先用任意方式给女仆装上护甲（以下届合金套为例）
2.然后再用shift键把护甲取下
3.然后就能看见护甲值并没有减少（指20点防御值）

使用此模组版本
https://github.com/TartaricAcid/TouhouLittleMaid/releases/tag/snapshot-2021101705311634448692

**Comment by TartaricAcid** [comment]
已知 bug，暂未查出原因

**Comment by TartaricAcid** [comment]
fix in https://github.com/TartaricAcid/TouhouLittleMaid/commit/eb66232741a533b3e4e2b9c1c41a9083f06d5242

**Comment by TartaricAcid** [comment]
再次修正
