### ISSUE TITLE
[Bug] 1.12 Maid always sleep at twilightforest and other dimensions

### ISSUE THREAD

**Issue by xmxmxmmmm** [TartaricAcid/TouhouLittleMaid#360]
### Minecraft Version

- [X] 1.12.2
- [ ] 1.16.5

### What happened?

1.maid always sleep at twilightforest and other dimensions
![image](https://user-images.githubusercontent.com/89410020/140631990-628ebc94-cba7-4030-bcc0-2b81212e06ce.png)
https://www.mcbbs.net/forum.php?mod=viewthread&tid=1274694&pid=23767566&page=1&extra=#pid23767566

### Contact Details

983888731@qq.com

**Comment by TartaricAcid** [comment]
This is a design error and will be fixed in the next update
