### ISSUE TITLE
[Bug] 1.12 使用 CatServer 服务端在网络通信时发生错误

### ISSUE THREAD

**Issue by axin0452** [TartaricAcid/TouhouLittleMaid#361]
### Minecraft Version

- [X] 1.12.2
- [ ] 1.16.5

### What happened?

1.发生这个报错的时候 一个玩家掉线了 不清楚是如何触发的

### Relevant log output

```shell
https://sourceb.in/qgr5Qt6HiT
```

**Comment by TartaricAcid** [comment]
不清楚是不是 CatServer 的问题，网络通信时候 `ctx.getServerHandler()` 可能返回了 null，你试试最新版的 CatServer 是否修复了此问题

**Comment by TartaricAcid** [comment]
1.12.2 has stopped supporting
