### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by lvshu2503897746** [TartaricAcid/TouhouLittleMaid#372]
### Minecraft Version

- [X] 1.12.2
- [ ] 1.16.5

### What happened?

1.在1.12.2版本的服务器中，玩家不能在创造模式下使用魔理沙的扫帚，系统提示要更改配置文件，我是服务器op，使用了帕秋莉手册的书修改之后没有用，是不是要去mod文件里修改？
2.
3.

**Comment by TartaricAcid** [comment]
修改服务端配置文件即可

> 使用了帕秋莉手册的书修改之后没有用

？你不是服务器么？为啥要修改客户端的配置文件？
