### ISSUE TITLE
[Bug] 加载某个资源包导致游戏材质错误

### ISSUE THREAD

**Issue by Orisamthesecond** [TartaricAcid/TouhouLittleMaid#382]
### Minecraft Version

- [ ] 1.12.2
- [X] 1.16.5

### What happened?

加载了 雪尼资源包 使游戏大部分材质不加载，卸载资源包刷新后恢复原状
可能是这个资源包占用了其他的材质

**Comment by TartaricAcid** [comment]
1.16.5 模型包不是原版资源包形式加载的，而是放在游戏主目录下方的 tlm_custom_pack 文件夹中
