### ISSUE TITLE
[Bug] 1.16.5祭坛配方JEI查询不能正常显示含minecraft:air的配方

### ISSUE THREAD

**Issue by Rinko1231** [TartaricAcid/TouhouLittleMaid#385]
### Minecraft Version

- [ ] 1.12.2
- [X] 1.16.5

### What happened?

1.首先定义个祭坛配方，这里我用的是kubejs的event.custom（感觉跟这个没关系，直接改数据包应该差不多），然后是效果是召唤闪电，祭品没有填满6个，空的用minecraft:air。
2.
///
event.custom({
  "type": "touhou_little_maid:altar_crafting",
  "output": {
    "type": "minecraft:lightning_bolt"
  },
  "power": 0.0,
  "ingredients": [
    {
      "item": "minecraft:gunpowder"
    },
    {
      "item": "minecraft:redstone"
    },
    {
      "item": "kubejs:washed_sand_pile"
    },
    {
      "item": "kubejs:washed_sand_pile"
    },
    {
      "item": "kubejs:washed_sand_pile"
    },
    {
      "item": "minecraft:air"
    }
  ]
})
///
3.结果是，查询kubejs:washed_sand_pile（我的自定义物品）在JEI内，祭坛合成标签页下这个配方显示出来是空白页面。
4.不过，实际在祭坛上摆上对应内容，还可以生效的

**Comment by TartaricAcid** [comment]
空气就不要写上去了，`ingredients` 支持 1-6 个可变参数

**Comment by TartaricAcid** [comment]
http://page.cfpa.team/TouhouLittleMaid/zh_CN/custom_altar_recipes.html#_1-16-5
