### ISSUE TITLE
模组在往用户主目录中写文件

### ISSUE THREAD

**Issue by chiyuki0325** [TartaricAcid/TouhouLittleMaid#391]
### Minecraft Version

- [X] 1.12.2
- [ ] 1.16.5

### What happened?

1. 正常启动游戏
2. 主目录中多出 touhou_little_maid 文件夹

应改为写在 `.minecraft` 或 `.minecraft/versions/版本隔离`

![图片](https://user-images.githubusercontent.com/73830635/164720018-d7c29bac-78af-4c0a-8d48-b798cf445e4b.png)

### Contact Details

ydz@yidaozhan.ga

**Comment by TartaricAcid** [comment]
我就是特意往那个文件夹写的

**Comment by TartaricAcid** [comment]
这样写的目的是为了多个游戏能共享一个本地的模型库，但是有人提到这样设计会导致清理软件无法正确识别，长时间堆积会占用 C 盘空间（虽然目前所有的资源包合起来也才十几 M 大小）

所以 1.16 我改成了 `.minecraft/config` 文件夹
