### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by rtxyd** [TartaricAcid/TouhouLittleMaid#394]
### Minecraft Version

- [ ] 1.12.2
- [X] 1.16.5

### What happened?

1.在地图上走来走去，脚底每隔一段时间会自动生成可放入物品栏的p点，间隔时间不固定，不清楚原理，但是不移动的时候不会生成p点，垂直移动水平移动都会触发（比如开创造飞到很高的高空也会在过程中一直触发）。3人联机的时候有一个人最先出现这种情况，后来消失。然后一段时间后相隔一千方块之外的我作为主机也出现了这种情况。（已明确触发方式）
2.模组版本为1.0.2
3.触发方式为身穿dungeons gear的item:dungeons_gear:emerald_chestplate 或 item:dungeons_gear:opulent_chestplate 或item:dungeons_gear:gilded_glory_chestplate 或 item:dungeons_gear:opulent_helmet 或 item:dungeons_gear:emerald_helmet

### Relevant log output

```shell
日志中没有有用的信息
```

### Contact Details

498567672@qq.com

**Comment by TartaricAcid** [comment]
我并没有设计和 dungeons gear 模组任何相关的联动，我也不清楚怎么回事
