### ISSUE TITLE
[Suggestion] Iron Chest Support

### ISSUE THREAD

**Issue by Gizmo0320** [TartaricAcid/TouhouLittleMaid#397]
I was wondering if it would be possible to add Iron Chest Support.

**Comment by Gizmo0320** [comment]
Any update on this

**Comment by chen125666** [comment]
What about ae2 or Tom's Simple Storage

**Comment by TartaricAcid** [comment]
https://github.com/TartaricAcid/TouhouLittleMaid/commit/3dc6bded1687d9e61194b5c9a5aee6d3e41ce788
