### ISSUE TITLE
[crash]渲染时发生了crash.....

### ISSUE THREAD

**Issue by Coloryr** [TartaricAcid/TouhouLittleMaid#4]
开启游戏的时候没问题，但是在物品栏选择的时候就crash了。
错误报告：
https://paste.ubuntu.com/p/PzxRfMsNBb/
https://paste.ubuntu.com/p/9fJcsYPWWt/
(貌似是渲染问题)

**Comment by 3TUSK** [comment]
https://github.com/TartaricAcid/TouhouLittleMaid/blob/d1e068b1c84d354a04ac27d9608199c1da1aa6be/src/main/java/com/github/tartaricacid/touhoulittlemaid/entity/passive/EntityMaid.java#L589-L594

没有检查传入的 `capability` 对象的具体类型直接进行 unchecked cast。
