### ISSUE TITLE
女仆合成物品的bug

### ISSUE THREAD

**Issue by ZAuxTSCkJe** [TartaricAcid/TouhouLittleMaid#40]
女仆在进行一些`产物数量大于1`的合成时（比如原木转化为木板，骨头转化为骨粉），每次合成只会获得`1`份产物。

~~女仆不能用`丛林木木板`合成`箱子/木镐`。~~

**Comment by Snownee** [comment]
问题1已修复。问题2无法复现

**Comment by ZAuxTSCkJe** [comment]
> 问题1已修复。问题2无法复现

无法重新复现问题2，已去除。  
~~看样子可以close了?~~
