### ISSUE TITLE
[Suggestion] Immersive Vehicles Integration

### ISSUE THREAD

**Issue by uraido** [TartaricAcid/TouhouLittleMaid#400]
Would it be possible to improve the compatibility with the Immersive Vehicles mod on 1.12.2? As of now, the maids CAN ride the vehicles (I got them to ride it using the Carry On mod), but they sit on top of the collision box as if it were a horse, instead of sitting on the intended vehicle seats, I just wanted to ride around  with my maido :(

In Immersive Vehicles, vehicle seat coordinates are set through JSON files in whichever vehicle pack they belong, maybe that could be useful, just an idea.

**Comment by TartaricAcid** [comment]
1.12.2 has stopped supporting
