### ISSUE TITLE
[Bug] [1.16.5] 启动游戏时崩溃

### ISSUE THREAD

**Issue by BBleae** [TartaricAcid/TouhouLittleMaid#403]
### Minecraft Version

- [ ] 1.12.2
- [X] 1.16.5

### What happened?

做的整合包在群友电脑上打不开，换了JVM、把mod删到只剩TLM一个，还是同样的报错

整合包的 crash-report (Oracle JRE) https://bytebin.lucko.me/iFsFFgCzPQ

整合包的 crash-report (Zulu JDK) https://bytebin.lucko.me/9NUkeDbMn8

单独加 TLM 时的 latest.log https://paste.debian.net/1260694/

**Comment by TartaricAcid** [comment]
1.16.5 应该用 Java 8，只有 1.18 才能用 Java17
