### ISSUE TITLE
[Bug] 玩家重生或者从末地返回后 P 点消失

### ISSUE THREAD

**Issue by Wybxc** [TartaricAcid/TouhouLittleMaid#406]
### Minecraft Version

- [ ] 1.12.2
- [ ] 1.16.5

### What happened?

版本 1.18.2，模组版本 1.0.0-alpha。

配置项中的 `PlayerDeathLossPowerPoint` 不生效，无论设为什么，都会在死亡后清空 P 点。

### Contact Details

wybxc@qq.com

**Comment by Wybxc** [comment]
简单排查了一下，问题出在这里：

https://github.com/TartaricAcid/TouhouLittleMaid/blob/71b43b4f04e79b93a86a0708b5d61fd9fd430bfa/src/main/java/com/github/tartaricacid/touhoulittlemaid/event/CapabilityEvent.java#L41

`oldPowerCap.ifPresent` 是 false，导致重生后更新 P 点的逻辑没有运行。

我正在试着自己修一下，但是我也没接触过 mod 开发，所以可能靠我自己是修不好的（x

**Comment by TartaricAcid** [comment]
最近打算更新，我先同步下 1.16.5 和 1.18.2

**Comment by TartaricAcid** [comment]
已修复，可在 https://github.com/TartaricAcid/TouhouLittleMaid/releases 下载最新版
