### ISSUE TITLE
[Bug]当背包满时存在的可堆叠物品复制bug

### ISSUE THREAD

**Issue by FridayAnubis** [TartaricAcid/TouhouLittleMaid#409]
### Minecraft Version

- [ ] 1.12.2
- [X] 1.16.5

### What happened?

Minecraft version 1.16.5, Mod version 1.0.2
1. 在女仆身上放入整组的任意可堆叠物品；
2. 把自己的身上塞满，仅保留放入第1步中女仆身上的物品，数量小于一组都可；
3. 打开女仆，通过快速移动（shift+左键）移动整组物品，则身上不满一组的该物品被填满，女仆身上的物品未被消耗，依然为整组。

初步测试，只要在将女仆身上已有的物品快速移动到身上时，满足仅有部分物品能够成功移动（空间不足）时，即可触发该Bug。

**Comment by TartaricAcid** [comment]
一直此问题，会尽快修复

**Comment by TartaricAcid** [comment]
我试了很多次都无法触发此问题，你确认下你是玩的哪个版本？是单机还是服务器

**Comment by TartaricAcid** [comment]
1.16.5 和 1.18.2 已经修复

**Comment by TartaricAcid** [comment]
可在 https://github.com/TartaricAcid/TouhouLittleMaid/releases 下载修复版
