### ISSUE TITLE
1.1.1-alpha的东方女仆体验/意见/bug反馈

### ISSUE THREAD

**Issue by TakimotoEirlo** [TartaricAcid/TouhouLittleMaid#41]
推荐：
littlemaidmob的女仆酱有个AI，撞一下女仆，女仆会向靠到一边去（似乎是用来移动女仆防止妨碍防止方块）

问题：
挖矿时女仆会挡在面前？
（AI）水底有掉落物品时女仆会一直停留在水上企图捡起物品但是无法潜水去捡？
（声音）挖矿时掉落两物品女仆看到企图捡起时会播放两次音效？
（声音）女仆有时声音奇怪（Minecraft的变声，有事会把女仆音调变低的难听了起来，在littlemaidmob中似乎不是这样的低。）

(兼容)DynamicTrees树未完全倒下时就掉下物品，女仆立即过去捡就树砸死了？

**Comment by Snownee** [comment]
建议下次把问题分条发成 issue

**Comment by TartaricAcid** [comment]
> （声音）挖矿时掉落两物品女仆看到企图捡起时会播放两次音效？
现在应该不是这样了

> 女仆有时声音奇怪（Minecraft的变声，有事会把女仆音调变低的难听了起来，在littlemaidmob中似乎不是这样的低。）
能细说下是怎么触发的么？
