### ISSUE TITLE
车万女仆和龙核最新版冲突

### ISSUE THREAD

**Issue by kang-png** [TartaricAcid/TouhouLittleMaid#411]
https://pastebin.com/pJwUsTwU

 2.6.2.1的龙核（是目前最新版）和车万女仆冲突
两个mod都单独可以启动 放一起就不行了

链接：https://pan.baidu.com/s/1ZO49IAqpvnntjIAnng0AFg?pwd=9999 
提取码：9999

**Comment by TartaricAcid** [comment]
我看了下错误报告，是在服务端调用了客户端模组导致的，但是我写的模组并没有调用错误报告中所说的任何客户端类，非常的莫名其妙，无法解决此问题
