### ISSUE TITLE
[Bug] Nametag Easter egg model doesn't have the coat layer on the player's head.

### ISSUE THREAD

**Issue by pantsguyapp** [TartaricAcid/TouhouLittleMaid#413]
### Minecraft Version

- [x] 1.12.2
- [X] 1.16.5

### What happened?

1. Rename the maid using a nametag and the easter egg player name.
2. Fill in someone with an overlayer on their head (For me I used FuriousDestroyer).
3. Observe that the skin is missing the layer.

**Comment by TartaricAcid** [comment]
This is the case at the moment, because the model is too difficult to make two layers
