### ISSUE TITLE
[Bug] start book is missing

### ISSUE THREAD

**Issue by drachenfreund15** [TartaricAcid/TouhouLittleMaid#414]
### Minecraft Version

- [ ] 1.12.2
- [X] 1.16.5

### What happened?

1.we installed the 1.16.5 version
2.we added 50 other mod ut but i tried the mod alone and i still dont have the starter book
3. i tried to spawn it without book but it didnt work 

### Contact Details

drachenfreund90@gmail.com

**Comment by TartaricAcid** [comment]
Please check if you have patchouli mod installed

If not, you can also can be crafted
