### ISSUE TITLE
[1.18.2] Sound crash event

### ISSUE THREAD

**Issue by Runburner** [TartaricAcid/TouhouLittleMaid#419]
**Minecraft Version**
-  1.18.2

**Mod Version**
- touhoulittlemaid-1.18.2-release-1.1.0.jar

**What happened?**
Randomly crashed due to the follow error log
https://pastebin.com/646nTw7u
[crash-2023-09-06_07.31.55-client.txt](https://github.com/TartaricAcid/TouhouLittleMaid/files/12536907/crash-2023-09-06_07.31.55-client.txt)
Every time when trying to rejoin world, crash as soon as we load in. We also don't have any maids put down yet. They are put away in soul spell.

**Comment by TartaricAcid** [comment]
Download: https://github.com/TartaricAcid/TouhouLittleMaid/releases
