### ISSUE TITLE
[兼容问题]animania模组和CarryOn模组与TLM女仆的兼容

### ISSUE THREAD

**Issue by TakimotoEirlo** [TartaricAcid/TouhouLittleMaid#42]
（以后TouhouLittleMaid简称TLM女仆；LittleMaidMob简称LMM女仆）

CarryOn是一个可以让玩家抱起/放置实体的功能模组，通过按键可以将一部分方块（熔炉，小箱子）/被动生物（如鸡、猪）抱起进行移动位置，抱起时被移动的实体的信息是记录好的，经过试验，两个模组的女仆都可以抱起，并且尚未看到有无女仆数据的变动。
animania是一个替换添加了更多家禽牲畜等生物的模组

逻辑：
抱起animania的鸡，放置在TLM女仆身上，女仆可以携带他，可能会在女仆头上，也可能 在身上某处

**Comment by TakimotoEirlo** [comment]
此时女仆移速出现变化。

**Comment by TartaricAcid** [comment]
所以第一个反馈了什么 Bug 么？
第二个问题，我不清楚 animania 模组是怎么写逻辑的，目前模组兼容方面优先级最低，主要还是致力于本体大框架的设计。所以只要不是严重 bug，暂时不进行修改

**Comment by TartaricAcid** [comment]
长时间不提供有效信息，关闭此 Issues
