### ISSUE TITLE
Crash on Start-Up

### ISSUE THREAD

**Issue by ScoutTheSaneless** [TartaricAcid/TouhouLittleMaid#420]
I have no idea what's going on, but when I installed the maids into my pack with excitement, the game started screaming at me. Is there a mod in there that isn't playing nice with the sweet maids? Maybe it has to do with the new speech bubble changes, I'm not certain, but something is angered by them...

[crash-2023-09-07_09.41.00-client.txt](https://github.com/TartaricAcid/TouhouLittleMaid/files/12551569/crash-2023-09-07_09.41.00-client.txt)

**Comment by ScoutTheSaneless** [comment]
upon further investigation, the maids are having problems w Pollen/Etched

**Comment by TartaricAcid** [comment]
try it: https://github.com/TartaricAcid/TouhouLittleMaid/releases/tag/snapshot-2023090816231694190216

**Comment by TartaricAcid** [comment]
Is it available now? Please give me a reply

**Comment by ScoutTheSaneless** [comment]
[crash-2023-09-09_14.44.56-server.txt](https://github.com/TartaricAcid/TouhouLittleMaid/files/12566739/crash-2023-09-09_14.44.56-server.txt)
here's what happened

**Comment by ScoutTheSaneless** [comment]
it also says that it has problems reading the resourcepacks

**Comment by TartaricAcid** [comment]
try this: https://github.com/TartaricAcid/TouhouLittleMaid/releases/tag/snapshot-2023091212131694520814

**Comment by ScoutTheSaneless** [comment]
latest release fixed the issue!
