### ISSUE TITLE
1.19.2 of Game does not load mods properly?

### ISSUE THREAD

**Issue by lSherozl** [TartaricAcid/TouhouLittleMaid#421]
[latest.log](https://github.com/TartaricAcid/TouhouLittleMaid/files/12552585/latest.log)

Might be an issue with pollen-related mods, don't know for sure. Ill keep updating here after trying out different mods and seeing the result.

**Comment by lSherozl** [comment]
Yeah its been figured out that its pollen and etched mod causing the issue

**Comment by TartaricAcid** [comment]
try it: https://github.com/TartaricAcid/TouhouLittleMaid/releases/tag/snapshot-2023090816231694190216

**Comment by lSherozl** [comment]
> try it: https://github.com/TartaricAcid/TouhouLittleMaid/releases/tag/snapshot-2023090816231694190216

Got this crash after putting that mod into the fol
[crash-2023-09-08_14.33.20-client.txt](https://github.com/TartaricAcid/TouhouLittleMaid/files/12563573/crash-2023-09-08_14.33.20-client.txt)
der

**Comment by lSherozl** [comment]
[latest.log](https://github.com/TartaricAcid/TouhouLittleMaid/files/12563655/latest.log)

**Comment by lSherozl** [comment]
> try it: https://github.com/TartaricAcid/TouhouLittleMaid/releases/tag/snapshot-2023090816231694190216

Yes it still crashes I provided the crash report and log

**Comment by TartaricAcid** [comment]
It seems to be a problem with the xaeroworldmap mod, try deleting this mod

**Comment by lSherozl** [comment]
> It seems to be a problem with the xaeroworldmap mod, try deleting this mod

If that was the case then removing pollen and etched and then having the world map mod and little maid would not have made it work together to begin with

**Comment by lSherozl** [comment]
[crash-2023-09-09_13.07.35-client.txt](https://github.com/TartaricAcid/TouhouLittleMaid/files/12566538/crash-2023-09-09_13.07.35-client.txt)

**Comment by lSherozl** [comment]
[latest.log](https://github.com/TartaricAcid/TouhouLittleMaid/files/12566536/latest.log)

**Comment by lSherozl** [comment]
Still crashes even after removing world map mod

> It seems to be a problem with the xaeroworldmap mod, try deleting this mod

**Comment by lSherozl** [comment]
> It seems to be a problem with the xaeroworldmap mod, try deleting this mod

The problem Has to be with the mods Pollen and Etched Vs Maid mod, removing pollen and etched causes the maid mod to work even if the world map mod is present

**Comment by TartaricAcid** [comment]
try this: https://github.com/TartaricAcid/TouhouLittleMaid/releases/tag/snapshot-2023091212131694520814

**Comment by lSherozl** [comment]
> try this: https://github.com/TartaricAcid/TouhouLittleMaid/releases/tag/snapshot-2023091212131694520814

Thank you, it works now with pollen and etched
