### ISSUE TITLE
[Bug] 女仆与驯养革新的兼容问题

### ISSUE THREAD

**Issue by linxcy** [TartaricAcid/TouhouLittleMaid#426]
### Minecraft Version

- [ ] 1.12.2 (End of support)
- [ ] 1.16.5
- [ ] 1.18.2
- [ ] 1.19.2
- [X] 1.20/1.20.1

### What happened?

1.女仆睡了宠物床之后，如果女仆死亡，第二天早上会复活两个女仆出来。
2.按设定来讲，睡过宠物床的宠物死亡后不会掉落任何物品，但是女仆还是会把她背包里面的所有东西掉落出来。
3.不仅东西会掉落出来，复活的新女仆身上还会复制一份物品。而且联动问题1，复活出来的两个女仆都有一份。

**Comment by TartaricAcid** [comment]
这是很明显的设计冲突，我看看怎么解决

**Comment by TartaricAcid** [comment]
https://github.com/TartaricAcid/TouhouLittleMaid/commit/5a3fd1c90aa15e258374eeec1a6d3fbcb8c017b1

已修复：
- 修复女仆死亡后，在宠物床上复活的复制问题
- 修复宠物床绑定后，重复掉落物品问题
- 修正死亡诅咒和烈焰保护附魔的不兼容问题（拒绝这两个附魔施加于女仆，其中烈焰保护附魔会导致任意宠物的崩溃，不限于女仆模组）
