### ISSUE TITLE
[Bug] 模型声音包下载和分类

### ISSUE THREAD

**Issue by Anchormeow** [TartaricAcid/TouhouLittleMaid#427]
### Minecraft Version

- [ ] 1.12.2 (End of support)
- [ ] 1.16.5
- [ ] 1.18.2
- [ ] 1.19.2
- [x] 1.20/1.20.1

### What happened?

1.模型声音包点击下载后，即使已经下载完成，依然显示“下载中”，等待较长时间也不会更新状态。重新打开游戏后才会显示“已下载”。
2.也许是bug或者就是如此设计的？“全部资源包”列表中不包含声音资源包，仅包含人物模型和坐垫模型。

**Comment by TartaricAcid** [comment]
你的第二个问题是错误的，不存在的问题

**Comment by Anchormeow** [comment]
关于问题2，通过测试发现这个bug的触发方式：首先打开资源包下载页面，可以看到“全部资源包”一项正常显示（图1），点击切换到“声音包”，再切换回“全部资源包”，发现**部分栏目消失**（图2）。

图1：
![2023-12-17_00 00 44](https://github.com/TartaricAcid/TouhouLittleMaid/assets/96508226/58823a21-c488-4fba-af06-2d338ae755c7)
图2：
![2023-12-17_00 01 37](https://github.com/TartaricAcid/TouhouLittleMaid/assets/96508226/68e4030b-7ba9-4a84-bba8-02d9a771c633)

**Comment by TartaricAcid** [comment]
好的，我查证一下

**Comment by TartaricAcid** [comment]
我还是试不出来，我这边一切正常

**Comment by Anchormeow** [comment]
那就不知道是我这边网络问题还是mod冲突引起的，确实有点奇怪。我除了tlm就装了wthit、帕秋莉、JEI、旅行地图和optifine这几个常见mod，我把这些mod都删了后进行测试，问题依然存在。有时间我用pcl重新安装个纯净版游戏单独加tlm试试看。

**Comment by TartaricAcid** [comment]
你用的什么版本的 tlm，截个图

**Comment by Anchormeow** [comment]
用的11月27号的1.1.4-hotfix版本
![255](https://github.com/TartaricAcid/TouhouLittleMaid/assets/96508226/e828193a-bcb7-4e96-ab1b-0ac76a816802)

**Comment by TartaricAcid** [comment]
还是无法复现，此问题暂时关闭

**Comment by Anchormeow** [comment]
将mod版本升级到1.1.7后问题2解决，不知道和模型包下载界面改版有关还是和我这边的Forge升级有关（从47.0.35升到了47.2.0）。总之感谢大佬近期疯狂加班迭代的新版本给我们带来的新体验，孩子很喜欢；）
