### ISSUE TITLE
Game Crash [Bug] 

### ISSUE THREAD

**Issue by YejiYeah** [TartaricAcid/TouhouLittleMaid#429]
### Minecraft Version

- [ ] 1.12.2 (End of support)
- [ ] 1.16.5
- [ ] 1.18.2
- [ ] 1.19.2
- [x] 1.20/1.20.1

### What happened?

1. The game crashes in my modpack, I have not been able to identify the cause

### Relevant log output

```shell
https://gist.github.com/SaraXianLin/b3a40b62620658a7a0fd5c3b5447e58b
```

### Contact Details

sarahi07mina@gmail.com

**Comment by YejiYeah** [comment]
the maids keep crashing my game with the same issue, I am going to try to add them to the bad mobs blacklist

**Comment by TartaricAcid** [comment]
Provided too little information and I really can't solve it
