### ISSUE TITLE
小问题：手办变化

### ISSUE THREAD

**Issue by TakimotoEirlo** [TartaricAcid/TouhouLittleMaid#43]
更换新版1.1.1→1.1.2后，“大妖精”（上个版本放置）手办变成了“莉莉白”手办

**Comment by Jedidiah-Zhang** [comment]
这个情况我也出现了，但是这应该不算问题吧，手办命名应该是改了，所以应该没有修正的必要

**Comment by TartaricAcid** [comment]
这是新旧版本模型数据更改的问题，你只能重新获取手办
