### ISSUE TITLE
[不确定/模组兼容Bug] Carryon 搬运女仆出现较严重性能问题

### ISSUE THREAD

**Issue by Sorrow-Scarlet** [TartaricAcid/TouhouLittleMaid#439]
### Minecraft Version

- [ ] 1.12.2 (End of support)
- [ ] 1.16.5
- [ ] 1.18.2
- [X] 1.19.2
- [ ] 1.20/1.20.1

### What happened?

**特征**：200+mods整合包，使用embeddium, oculus, Carry on, tlm
1. 放女仆
2. 搬女仆
3. 掉帧，且出现天空位移现象   

存在优化类mod，以及200+mods，不确定是否是其他mod产生的间接影响，但是直接搬运空白的女仆就会出现这个问题。

### Relevant log output

```shell
1. latest.log: https://wwty.lanzouj.com/izHQ11kxfmvi  
密码:dk2g  
2. debug.log: https://wwty.lanzouj.com/ipP6H1kxfmxa  
密码:82a8  
3. 视频演示：https://wwty.lanzouj.com/iIAQ31kxf6yf
```

**Comment by TartaricAcid** [comment]
已修复
https://github.com/TartaricAcid/TouhouLittleMaid/commit/0ce9d5c156d7f002c8d37fb0a8ee7b63a4b03ecd

**Comment by TartaricAcid** [comment]
https://github.com/TartaricAcid/TouhouLittleMaid/releases/tag/snapshot-2024011515121705331565
