### ISSUE TITLE
一些问题与建议[Bug] 

### ISSUE THREAD

**Issue by zhenadao** [TartaricAcid/TouhouLittleMaid#440]
### Minecraft Version

- [ ] 1.12.2 (End of support)
- [ ] 1.16.5
- [ ] 1.18.2
- [ ] 1.19.2
- [X] 1.20/1.20.1

### What happened?

问题1：女仆使用弓需要箭，如果没有箭则会一直做射箭动作停不下来，目前只能通过给箭附魔无限且提供箭才能临时解决，建议添加箭数量的判断
问题2：武器耐久消耗完后女仆还会显示拿着武器，打开女仆物品栏后退出武器才消失

建议1：增加个选项，是否消耗完武器耐久，比如剩余1点耐久就不再工作了

**Comment by TartaricAcid** [comment]
问题 1：已解决
问题 2：我没试验出来，我这边能正常消失，而且这一块我特意关注了客户端服务端同步的

**Comment by zhenadao** [comment]
估计是其他模组导致的问题，我单模组测试是正常的
