### ISSUE TITLE
[Bug] 模型包下载界面 下载不了卡在下载中 下不下来 服务器和单机都试过了不行

### ISSUE THREAD

**Issue by LOVE1264** [TartaricAcid/TouhouLittleMaid#442]
### Minecraft Version

- [ ] 1.12.2 (End of support)
- [ ] 1.16.5
- [ ] 1.18.2
- [X] 1.19.2
- [ ] 1.20/1.20.1

### What happened?

1.
2.
3.

**Comment by TartaricAcid** [comment]
试一下最新版的模组，已修复此问题

**Comment by TartaricAcid** [comment]
https://github.com/TartaricAcid/TouhouLittleMaid/releases/tag/snapshot-2024011515121705331565
