### ISSUE TITLE
[Bug] Danmaku maids don't have damage scaling

### ISSUE THREAD

**Issue by pantsguyapp** [TartaricAcid/TouhouLittleMaid#448]
### Minecraft Version

- [X] 1.12.2 (End of support)
- [X] 1.16.5
- [X] 1.18.2
- [X] 1.19.2
- [X] 1.20/1.20.1

### What happened?

1. Uses Creative Max Favorability
2. Observes maids in different fighting modes, and see that only in sword mode that the damaged got increased.
3. Switch the maid to danmaku mode and sees her fight, she still only deal 4 damage per hit.
4. Now spawn in a witch, and watch as the danmaku maids literally unable to defeat her, since the witch healing potion heal 8 hp.

What should happened.
Maids' danmaku power should get stronger as they health go up also.

**Comment by pantsguyapp** [comment]
Yeah the witch is a pain in the ass for danmaku maids? Pls make the danmaku maids stronger á they level up.

**Comment by TartaricAcid** [comment]
Has been completed

**Comment by pantsguyapp** [comment]
So how much does a danmaku maid with max favor deal now?
