### ISSUE TITLE
希望女仆可以开关门和栅栏门

### ISSUE THREAD

**Issue by Jedidiah-Zhang** [TartaricAcid/TouhouLittleMaid#45]
主要用于喂养模式下不用我自己带女仆进栅栏
然后我注意到手上拿着麦子的女仆并不能吸引动物？

**Comment by TartaricAcid** [comment]
开关门后续加上，吸引动物也算是个不错的设计，我试试

**Comment by Snownee** [comment]
本来就可以开关门啊

**Comment by Jedidiah-Zhang** [comment]
开关门实测不行，把女仆放到带门的封闭空间，她只会瞬移出来；。
把她带到栅栏外，调成喂养模式她也只会看着里面的动物，我把门打开后才进去。

**Comment by Jedidiah-Zhang** [comment]
如果编了开关门的程序的话，那就应该是寻路AI的问题了

**Comment by lone-wolf-akela** [comment]
实测开关门不行……我同时养了一直灵梦和一只peko版的小女仆，每次peko版女仆走门的时候灵梦都卡在门另一边，直到我走远了再传送过来
