### ISSUE TITLE
[Bug] Maid's mob detection is too low.

### ISSUE THREAD

**Issue by pantsguyapp** [TartaricAcid/TouhouLittleMaid#450]
### Minecraft Version

- [ ] 1.12.2 (End of support)
- [X] 1.16.5
- [X] 1.18.2
- [X] 1.19.2
- [X] 1.20/1.20.1

### What happened?

1. Spawn in a skeleton from far away
2. Nudge it to just get in the range of a maid
3. Watch the skeleton attack, as it strafe it got outside of the maid's follow range and maid now just got hit by arrows and have no clue whats attack her.

Would be useful if the followrange is 16 just like normal mobs so maids can keep track of enemies.

**Comment by TartaricAcid** [comment]
Maid has a working scope, and she will not work beyond the scope. This is reasonable.

Secondly, too fast detection will put pressure on the server.

**Comment by pantsguyapp** [comment]
That mean they will always struggle with the skeletons, I just asked for the scope to be increased to 16, I tried increse the work radius in the config and this issue still happen.
