### ISSUE TITLE
[Bug] maids are kind of suck when it comes to sword fighting.

### ISSUE THREAD

**Issue by pantsguyapp** [TartaricAcid/TouhouLittleMaid#451]
### Minecraft Version

- [X] 1.12.2 (End of support)
- [X] 1.16.5
- [X] 1.18.2
- [X] 1.19.2
- [X] 1.20/1.20.1

### What happened?

1. Have sword maid vs a standard zombie or skeleton.
2. Maids are dumb enough to run straight to the mob and get hurt, repeat.
3. Repeat until maid die.

Expected behavior:
1. Maid run toward the mob, but stop just close enough to be able to hit the mob while stay out of its reach.
2. Maid defeat the zombie without taking a single damage.

This has been the way for maids from Little maids mod, but not for touhou maids.

**Comment by TartaricAcid** [comment]
This issue has been fixed
Default attack range is now 2
And the distance will increase with the favorability
