### ISSUE TITLE
[Bug] 女仆用拔刀剑不会坏

### ISSUE THREAD

**Issue by Minepig** [TartaricAcid/TouhouLittleMaid#454]
### Minecraft Version

- [ ] 1.12.2 (End of support)
- [ ] 1.16.5
- [X] 1.18.2
- [ ] 1.19.2
- [ ] 1.20/1.20.1

### What happened?

![image](https://github.com/TartaricAcid/TouhouLittleMaid/assets/30530115/4cae1949-e98e-4942-96fd-bff0c0a0f73a)
尝试让女仆用木偶，但是耐久耗尽以后并没有断掉

**Comment by TartaricAcid** [comment]
已知问题，女仆会用到耐久还剩一格

**Comment by TartaricAcid** [comment]
因为是拔刀剑自己的机制问题，无法修复也不会修复
