### ISSUE TITLE
[Bug] Please fix the AI

### ISSUE THREAD

**Issue by AngelToad465** [TartaricAcid/TouhouLittleMaid#457]
I just had an CRYSIS because maid AI wants to always pick up items, even in LAVA
PLEASE FIX IMMEDIEATLY
sorry I can't upload footage because it is more than 10mb

**Comment by AngelToad465** [comment]
please add danger detection

**Comment by TartaricAcid** [comment]
What version of Minecraft are you using and what version of mods are you using?

**Comment by AngelToad465** [comment]
1.18.2
mod ver. 1.1.7

**Comment by AngelToad465** [comment]
also PLEASE FIX ASAP THEY ARE ALSO TEMPTED PY XP ORBS

**Comment by TartaricAcid** [comment]
![image](https://github.com/TartaricAcid/TouhouLittleMaid/assets/19620085/db8aaae2-733e-4029-86f1-d07401c5d75a)
After my testing, this did not happen

**Comment by TartaricAcid** [comment]
This issue cannot be reproduced and the commenter did not provide further relevant information. This issue is closed.
