### ISSUE TITLE
[Feature Request] Have a Maid learn how to use Crossbow

### ISSUE THREAD

**Issue by cyliamargatroid** [TartaricAcid/TouhouLittleMaid#458]
### Minecraft Version

- [ ] 1.12.2 (End of support)
- [ ] 1.16.5
- [ ] 1.18.2
- [ ] 1.19.2
- [X] 1.20/1.20.1

### What happened?

I know Maids knows how to only use bow, but not crossbows, so we need a new feature for a Maid using a crossbow that the arrows hits hard than it is fired from a bow.

**Comment by TartaricAcid** [comment]
Has been completed
