### ISSUE TITLE
[Bug] 与CGM枪械模组冲突

### ISSUE THREAD

**Issue by Ojuscal** [TartaricAcid/TouhouLittleMaid#469]
### Minecraft Version

- [ ] 1.12.2 (End of support)
- [X] 1.16.5
- [ ] 1.18.2
- [ ] 1.19.2
- [ ] 1.20/1.20.1

### What happened?

不加载女仆模组能进入游戏，加载则出现以下错误提示
![ERROR](https://github.com/TartaricAcid/TouhouLittleMaid/assets/61080873/72c6b86e-bc05-491a-a3e8-79808f69b80c)
[minecraft-exported-crash-info-2024-03-09T12-46-33.zip](https://github.com/TartaricAcid/TouhouLittleMaid/files/14545008/minecraft-exported-crash-info-2024-03-09T12-46-33.zip)

### Contact Details

1185754490@qq.com

**Comment by TartaricAcid** [comment]
似乎是 lithium 的问题，删掉这个模组试试，这个模组已经停止更新 forge 版本了

**Comment by Ojuscal** [comment]
成了！神医啊酒大夫！
