### ISSUE TITLE
魔理沙扫帚的bug

### ISSUE THREAD

**Issue by Jedidiah-Zhang** [TartaricAcid/TouhouLittleMaid#47]
把扫帚放在地上后SHIFT左击打掉会掉落两把；
玩家骑着扫帚时不能正常从传送门传送，然后试了一下1997矿界那个传送门，扫帚自己会传送过去。
用神秘岛的链接书传送后（玩家骑在扫帚上），扫帚会消失不见。
女仆骑在扫帚上也不能通过下界那类传送门，但是可以通过矿界传送门。但是传送后扫帚消失，而且女仆处在一种伪飞行模式。即不能正常走路和跟随玩家，定在一个位置，玩家离开一段距离后会传送到玩家身边。通过在她下面放扫帚再让她下来可恢复。

**Comment by TartaricAcid** [comment]
1. 掉落两把？？我从没遇到过啊

2. 骑着扫帚时不能正常从传送门传送……你可以试试，基本是你骑着很多东西都不能穿越传送门，这个我要没记错还是原版的设定。

3. 你们的玩法是真的多……

4. 应该是 bug，我试试后续不让女仆进行任何传送门的操作

**Comment by Jedidiah-Zhang** [comment]
我这试了很多次，都是掉落两把

**Comment by TartaricAcid** [comment]
![001](https://upload.cc/i1/2019/08/02/hN5Yzf.gif)

无法复现

**Comment by Jedidiah-Zhang** [comment]
![Capture 01 00_00_00-00_00_06](https://user-images.githubusercontent.com/50638143/62352102-eddda500-b539-11e9-9cc7-bc874bb702ce.gif)

**Comment by Jedidiah-Zhang** [comment]
扫帚继承的是哪个实体？我想想可能跟哪个模组冲突

**Comment by TartaricAcid** [comment]
EntityLivingBase

**Comment by Jedidiah-Zhang** [comment]
测了40多个模组，终于确定是坚定意志Tough as Nails的锅

**Comment by Jedidiah-Zhang** [comment]
创造打掉掉落一把，生存打掉掉落两把。
其实可以参照矿车，经过测试矿车是没问题的

**Comment by TartaricAcid** [comment]
多谢，现在依据矿车逻辑已经修复此问题，是我的锅
