### ISSUE TITLE
[Suggestion] Enchantments for the Gohei

### ISSUE THREAD

**Issue by pantsguyapp** [TartaricAcid/TouhouLittleMaid#471]
### Minecraft Version

- [X] 1.12.2 (End of support)
- [X] 1.16.5
- [X] 1.18.2
- [X] 1.19.2
- [X] 1.20/1.20.1

### What happened?

The Gohei should be compatible with some custom enchantments such as:
- **Impeding Bullets I-IV**: Bullets now inflict slowness I - IV on the enemy.
- **Speedy Bullets I-II**: Bullets travel x2 regular speed at lv I and x3 at lv II, please note that the vanishing time for the bullets will also need to be changed to prevent bullets from keep traveling unto unloaded chunks.
- **Keen Hands**: Increasing Gohei's DPS aka the maid will be able to fire the bullets at double the speed, waiting only half the cooldown before they fire another round.
- **Spread Bullets I-IV**: When firing a singular bullet against a lone enemy, maids will get a bonus bullet, at level IV that would be 5. Please note that this enchantment only make sure that the maid fire multiple bullets instead of one, not actually add in any extra bullets when spread firing.
- **Enders Ender**: Bullets can actually hit Enderman and damage them without cause them to teleport away.
- Unbreaking and Mending - this has already been implemented.

I tried to make these enchantments to be as loyal to the Touhou's mechanic as possible, instead of having these as enchantments, you can make it so maids can learn these as their favor goes up instead, such as the Keen Hands enchant is more dependent on the maid's skill instead of a good Gohei, it's up to you to decide.
### Relevant log output

If possible make this compat with Enchantment descriptions https://www.curseforge.com/minecraft/mc-mods/enchantment-descriptions

**Comment by TartaricAcid** [comment]
![image](https://github.com/TartaricAcid/TouhouLittleMaid/assets/19620085/a1bb1000-6c74-4738-bfcf-41bdda6641eb)
Great idea, I have implemented it
Two enchantments from the vanilla are reused.

**Comment by pantsguyapp** [comment]
Outstanding tbh :)) I don't think you will add in all of these enchantments since with all of these upgrades, the staff will turn into a literal machine gun.
