### ISSUE TITLE
[Bug] Maids can still remain seated even when their idling time is over

### ISSUE THREAD

**Issue by pantsguyapp** [TartaricAcid/TouhouLittleMaid#472]
### Minecraft Version

- [ ] 1.12.2 (End of support)
- [X] 1.16.5
- [ ] 1.18.2
- [ ] 1.19.2
- [ ] 1.20/1.20.1

### What happened?

1. Set down some maids with some seats nearby
2. Switch the time to their idling time, wait for then to sit down then skip to their work time
3. Observe as some maid can still ride on the entity.

**Comment by TartaricAcid** [comment]
Do you mean maids should leave their seats during working hours?

**Comment by pantsguyapp** [comment]
Yeah, they should.

**Comment by TartaricAcid** [comment]
I don't think so, just like the vanilla mobs can't leave the minecart and boat
