### ISSUE TITLE
[Suggestion] Allow maids to sleep in vanilla beds

### ISSUE THREAD

**Issue by pantsguyapp** [TartaricAcid/TouhouLittleMaid#476]
### Minecraft Version

- [ ] 1.12.2 (End of support)
- [X] 1.16.5
- [X] 1.18.2
- [X] 1.19.2
- [X] 1.20/1.20.1

### What happened?

Maids should be able to sleep in vanilla beds, like a villagers. When a maid is sleeping, neither will villagers or players be able to bother her.

Might get conflicted with villagers.

**Comment by TartaricAcid** [comment]
I won't do this
