### ISSUE TITLE
[Bug] Massive Server Lag

### ISSUE THREAD

**Issue by Proxwian** [TartaricAcid/TouhouLittleMaid#479]
### Minecraft Version

- [ ] 1.12.2 (End of support)
- [ ] 1.16.5
- [ ] 1.18.2
- [ ] 1.19.2
- [X] 1.20/1.20.1

### What happened?

1. Server lag even when no maids spawned in the world

### Relevant log output

```shell
https://spark.lucko.me/vhlgmNIh6x
```

**Comment by Proxwian** [comment]
<img width="1259" alt="image" src="https://github.com/TartaricAcid/TouhouLittleMaid/assets/31781674/20aa01b8-a324-40d6-ac09-50293e6c73dc">

**Comment by TartaricAcid** [comment]
The link has expired

**Comment by TartaricAcid** [comment]
![image](https://github.com/TartaricAcid/TouhouLittleMaid/assets/19620085/50ebcdb1-2b56-4026-8dfb-e4ed1f95f800)

**Comment by Proxwian** [comment]
[oVgVHMHttB.sparkprofile.zip](https://github.com/TartaricAcid/TouhouLittleMaid/files/14789358/oVgVHMHttB.sparkprofile.zip)
