### ISSUE TITLE
[Request] Allow players to use the Gohei.

### ISSUE THREAD

**Issue by pantsguyapp** [TartaricAcid/TouhouLittleMaid#480]
### Minecraft Version

- [ ] 1.12.2 (End of support)
- [X] 1.16.5
- [X] 1.18.2
- [X] 1.19.2
- [X] 1.20/1.20.1

### What happened?

I missed when in 1.12.2 versions you can use the Gohei as well as be able to change the bullet style.
But from 1.16.5 onward the feature is gone.

**Comment by TartaricAcid** [comment]
This is a function I deleted on purpose. I think it can only be used by maids.
