### ISSUE TITLE
[Request] 兼容旅行者背包

### ISSUE THREAD

**Issue by 1343008086** [TartaricAcid/TouhouLittleMaid#482]
### Minecraft Version

- [ ] 1.12.2 (End of support)
- [X] 1.16.5
- [ ] 1.18.2
- [ ] 1.19.2
- [ ] 1.20/1.20.1

### What happened?

目前旅行者背包可以放入女仆的背包，现在女仆就等于一个巨大的移动仓储存空间，希望能兼容旅行者背包并禁止将旅行者背包放入女仆的背包

**Comment by TartaricAcid** [comment]
禁止背包套娃的功能是 mojang 1.17 才引入的，我没法在 1.16.5 做到这些，建议使用高版本
