### ISSUE TITLE
[Request] Maids use vanilla xp to mend instead.

### ISSUE THREAD

**Issue by pantsguyapp** [TartaricAcid/TouhouLittleMaid#483]
### Minecraft Version

- [ ] 1.12.2 (End of support)
- [X] 1.16.5
- [X] 1.18.2
- [X] 1.19.2
- [X] 1.20/1.20.1

### What happened?

Mending on maids should work with vanilla xp, since the power points aren't that very much common at all.

**Comment by TartaricAcid** [comment]
https://github.com/TartaricAcid/TouhouLittleMaid/blob/1.20/src/main/java/com/github/tartaricacid/touhoulittlemaid/entity/passive/EntityMaid.java#L487-L495
