### ISSUE TITLE
[Bug] Maids' name disappear sometimes.

### ISSUE THREAD

**Issue by pantsguyapp** [TartaricAcid/TouhouLittleMaid#489]
### Minecraft Version

- [ ] 1.12.2 (End of support)
- [ ] 1.16.5
- [X] 1.18.2
- [X] 1.19.2
- [X] 1.20/1.20.1

### What happened?

1. Name tag a maid
2. Observe as the name is unseen at first
3. Wait a while until the name can be seen at all times.

It should always show up everytime you look at a maid.

**Comment by TartaricAcid** [comment]
fixed
![image](https://github.com/TartaricAcid/TouhouLittleMaid/assets/19620085/c046402b-be31-4450-a0da-a04b3f579fb5)
