### ISSUE TITLE
jei_1.12.2-4.15.0.268看不到女仆蛋

### ISSUE THREAD

**Issue by wandaren** [TartaricAcid/TouhouLittleMaid#49]
我是直接放到天空工厂4的整合包里面的，JEI看不到，重新到curseforge上下载了jei_1.12.2-4.15.0.268的替换还是看不到，但是合成表里面可以合成。

**Comment by Jedidiah-Zhang** [comment]
我这里实测可以，应该是你整合包的问题

**Comment by Jedidiah-Zhang** [comment]
![image](https://user-images.githubusercontent.com/50638143/62300866-1d44d100-b4aa-11e9-8a13-649fb4c4a4df.png)
![image](https://user-images.githubusercontent.com/50638143/62300913-3057a100-b4aa-11e9-99a1-ed4ff8aa6db8.png)

**Comment by TartaricAcid** [comment]
SF4 整合应该隐藏了所有刷怪蛋的显示，这是 JEI 的功能一部分，不是 Bug
