### ISSUE TITLE
[Bug] 不可破坏的装备在女仆身上会被损耗耐久

### ISSUE THREAD

**Issue by PopSlime** [TartaricAcid/TouhouLittleMaid#492]
### Minecraft Version

- [ ] 1.12.2 (End of support)
- [ ] 1.16.5
- [ ] 1.18.2
- [ ] 1.19.2
- [X] 1.20/1.20.1

## 描述
无法破坏（即带有 `{Unbreakable:1b}` NBT 标签）的装备在女仆身上时会被异常损耗耐久值。

**Comment by TartaricAcid** [comment]
![image](https://github.com/TartaricAcid/TouhouLittleMaid/assets/19620085/f42c4be3-047e-42bf-873b-1dc1ac2b2bbd)
经过测试，并仔细查阅相关源码，并未发现任何异常，带有 `{Unbreakable:1b}` 标签物品并不会损失耐久

此问题无法复现

**Comment by PopSlime** [comment]
非常抱歉，刚刚重新仔细测试并分析了相关源代码，发现是另一 mod 的问题，与 Touhou Little Maid 没有任何关系。现关闭该 issue。
