### ISSUE TITLE
[Bug] 女仆进食堆叠状态大于一的带有容器的食物不会返还容器（蜂蜜瓶，安装了农夫乐事后可堆叠的甜菜汤）

### ISSUE THREAD

**Issue by Sukuna2021** [TartaricAcid/TouhouLittleMaid#500]
### Minecraft Version

- [ ] 1.12.2 (End of support)
- [ ] 1.16.5
- [X] 1.18.2
- [ ] 1.19.2
- [ ] 1.20/1.20.1

### What happened?

1.女仆进食堆叠状态大于一的带有容器的食物不会返还容器（蜂蜜瓶，安装了农夫乐事后可堆叠的甜菜汤）
2.同时如果进食完堆叠状态为一的食物后返还的容器会持续占用一只手，导致女仆无法再进食其他的食物（不是bug，但是建议加一个名单用于控制女仆会把哪些持于副手的物品自动放入背包）
3.

### Relevant log output

```shell
并非会导致游戏崩溃的bug
```

### Contact Details

zyc1446990444@gmail.com

**Comment by TartaricAcid** [comment]
https://github.com/TartaricAcid/TouhouLittleMaid/commit/f0db9010caa6376cec94bbbf202c9880145e133b

**Comment by TartaricAcid** [comment]
农夫乐事的也解决了

**Comment by TartaricAcid** [comment]
3 的话有点难办，暂时不处理
其他全部解决
