### ISSUE TITLE
[Bug] resouce packs wont show in game after downloading

### ISSUE THREAD

**Issue by sophienix** [TartaricAcid/TouhouLittleMaid#506]
### Minecraft Version

- [ ] 1.12.2 (End of support)
- [ ] 1.16.5 (End of support)
- [ ] 1.18.2
- [ ] 1.19.2
- [X] 1.20/1.20.1

### What happened?

1. open maid gui
2.go to download resource packs
3. download a resource pack 
4. says its downloading but its not showing in resource packs in game

### Contact Details

sophienixneuroi@gmail.com

**Comment by TartaricAcid** [comment]
Due to network problems, downloading will be slow, so you need to wait for a long time. This is normal.

You cannot see the file until it is completely downloaded (this is a protection mechanism I designed)

**Comment by sophienix** [comment]
> Due to network problems, downloading will be slow, so you need to wait for a long time. This is normal.
> 
> You cannot see the file until it is completely downloaded (this is a protection mechanism I designed)

nope wanst that it was showing in the folder but not in game had to restart it
