### ISSUE TITLE
[建议]女仆AI优化

### ISSUE THREAD

**Issue by LTHPKBTE** [TartaricAcid/TouhouLittleMaid#51]
驯服两个女仆，都切换成弹幕模式，让他们在复杂地形攻击同一个生物，然后...站前面那个就一直挨打了
建议优化攻击被挡住的时候只走位不攻击

**Comment by LTHPKBTE** [comment]
2.建议加上玩家远程攻击，女仆在弹幕模式也一起攻击的判定

**Comment by TartaricAcid** [comment]
1. 这个后续做一个饰品，能够防止友军伤害
2. 本来不就有这功能么？

**Comment by LTHPKBTE** [comment]
在所有模式下，我拿弓箭/博丽的御币攻击任何动物/玩家都没有反应，没有任何其他模组,forge版本14.23.5.2838

**Comment by TartaricAcid** [comment]
![001](https://upload.cc/i1/2019/08/02/TJjvUu.gif)
我这用弓箭/御币攻击生物一切正常啊，该伤害的都造成伤害了，有反应啊

**Comment by LTHPKBTE** [comment]
对不起我没说清楚，我指的是女仆没有跟着攻击

**Comment by LTHPKBTE** [comment]
3、女仆不会主动攻击史莱姆
(貌似不在主动攻击列表？)

**Comment by TartaricAcid** [comment]
我看了下原版的 AI 逻辑，狼也不会主动攻击玩家用弓箭攻击的对象，这也是 bug 么

**Comment by LTHPKBTE** [comment]
女仆有远程攻击
但是在那儿站着看我打
难受啊

**Comment by TartaricAcid** [comment]
史莱姆？史莱姆不是 EntityMob 的子类

**Comment by TartaricAcid** [comment]
远程攻击部分我看了下，远程攻击设定目标是写死在 EntityPlayer 里面的，虽然也可以改，但是可能会影响原版的一些逻辑（比如狼也会攻击远程目标了），这是具有一定风险的操作，我还是谨慎处理。

行，大部分问题处理了，我 close 这个问题反馈吧
