### ISSUE TITLE
Enhancement: Danmaku (Maid Fairy) damage scaling

### ISSUE THREAD

**Issue by cyliamargatroid** [TartaricAcid/TouhouLittleMaid#511]
The Maid Fairy danmaku projectile damage can be scaled up depending on a difficulty

Key: Small Danmaku | Large Danmaku
Easy: 1 | 2
Normal: 1.5 | 3
Hard: 2 | 4
Note: Difficulty damage scaling ignores Iron Golem

**Comment by TartaricAcid** [comment]
No need to ignore iron golems
