### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by BlackAngel0001** [TartaricAcid/TouhouLittleMaid#520]
### Minecraft Version

- [ ] 1.12.2 (End of support)
- [X] 1.16.5 (End of support)
- [ ] 1.18.2
- [ ] 1.19.2
- [ ] 1.20/1.20.1

### What happened?

Maids don't interact with fashion items, whether it's the maids' bed or the Gomoku game board

### Contact Details

Lareshchev@bk.ru

**Comment by TartaricAcid** [comment]
This problem cannot be reproduced, and 1.16.5 is no longer supported.
