### ISSUE TITLE
[Bug] game crash when maid shoots an arrow

### ISSUE THREAD

**Issue by angela212121** [TartaricAcid/TouhouLittleMaid#523]
### Minecraft Version

- [ ] 1.12.2 (End of support)
- [ ] 1.16.5 (End of support)
- [ ] 1.18.2
- [ ] 1.19.2
- [X] 1.20/1.20.1

### What happened?

1. The game crashes when the maid shoots a bow while the improved mobs mod is installed.
2.
3.
[crashmods.zip](https://github.com/user-attachments/files/15751199/crashmods.zip)

### Relevant log output

```shell
The game crashed whilst ticking entity
Error: java.lang.ClassCastException: class net.minecraft.world.item.BowItem cannot be cast to class net.minecraft.world.item.CrossbowItem (net.minecraft.world.item.BowItem and net.minecraft.world.item.CrossbowItem are in module minecraft@1.20.1 of loader 'TRANSFORMER' @4751e8b9)
```

### Contact Details

dkwomje@gmail.com or discord: buddy___

**Comment by TartaricAcid** [comment]
I used the Vanilla bow and crossbow and there was no crash, which is very strange
