### ISSUE TITLE
[Bug] 与 EMI 一起使用时，切换工作模式页面显示不正确。

### ISSUE THREAD

**Issue by LukeChen-j** [TartaricAcid/TouhouLittleMaid#526]
### Minecraft Version

- [ ] 1.12.2 (End of support)
- [ ] 1.16.5 (End of support)
- [ ] 1.18.2
- [ ] 1.19.2
- [X] 1.20/1.20.1

### What happened?

Forge 1.20.1
touhoulittlemaid-1.20.1-release-1.1.10-hotfix
emi-1.1.7+1.20.1+forge
女仆 GUI 正常，但切换工作模式页面下和 EMI 部分 UI 错位，和女仆的一些按钮重合。
最下面的截图是旅行者背包的界面，EMI 绕开了旅行者背包的不规则形状的 UI。
![2024-06-18](https://github.com/TartaricAcid/TouhouLittleMaid/assets/89825412/c54f442e-dd76-43bf-9910-52dea0282bba)
![2024-06-18 (1)](https://github.com/TartaricAcid/TouhouLittleMaid/assets/89825412/7ff8db96-76c9-4e68-af32-335993739cc9)
![2024-06-18 (2)](https://github.com/TartaricAcid/TouhouLittleMaid/assets/89825412/c2b57eb8-65ef-4d10-888e-c8c08495fa3e)

**Comment by TartaricAcid** [comment]
已完成
