### ISSUE TITLE
[Bug] 野餐篮GUI互动异常

### ISSUE THREAD

**Issue by mc-kaishixiaxue** [TartaricAcid/TouhouLittleMaid#527]
### Minecraft Version

- [ ] 1.12.2 (End of support)
- [ ] 1.16.5 (End of support)
- [ ] 1.18.2
- [ ] 1.19.2
- [x] 1.20/1.20.1

### What happened?

mod版本：1.1.10-hotfix
1.拿着野餐篮右击打开GUI；
2.当野餐篮正上方的格子有物品时，玩家无法通过点击拿起任何物品；
3.同时，野餐篮本身却可以直接在GUI通过鼠标点击拿起，点击后立即退出GUI。

**Comment by TartaricAcid** [comment]
已修复
