### ISSUE TITLE
[建议]让女仆下雨的时候会主动找地方躲雨

### ISSUE THREAD

**Issue by jksndk** [TartaricAcid/TouhouLittleMaid#534]
如标题所示，女仆在露天农场工作，下雨了不会找我建的小亭子躲，老是淋雨太可怜了QAQ

**Comment by TartaricAcid** [comment]
那么就会有玩家问：为什么我的女仆一下雨就不工作了

**Comment by jksndk** [comment]
虽然我设想的是让她在工作的空闲时间（比如说没有空着的田地也没有成熟的作物）躲雨，不过好像这功能确实有点冗余了💀，不好意思
