### ISSUE TITLE
女仆语音音调有时过低

### ISSUE THREAD

**Issue by lone-wolf-akela** [TartaricAcid/TouhouLittleMaid#56]
#41
上述issue中提到了”女仆有时声音奇怪（Minecraft的变声，有事会把女仆音调变低的难听了起来，在littlemaidmob中似乎不是这样的低。）“的问题，不过因为那个issue同时报告了好几个问题，然后又已经被关闭了，所以我觉得可能单独拿出来重新发一个比较好？

总而言之，我在游戏里也确实遇到了这个问题。我大概看了下代码试图寻找原因（我不会java但是会c++/c#之类的，也从来没接触过MC MOD编写，所以如果哪儿搞错了请见谅），似乎是由于女仆只override了
getAmbientSound函数但没有override getSoundPitch函数。而基类EntityLivingBase对getSoundPitch的默认实现似乎是

    return this.isChild() ? (this.rand.nextFloat() - this.rand.nextFloat()) * 0.2F + 1.5F : (this.rand.nextFloat() - this.rand.nextFloat()) * 0.2F + 1.0F;

如果我没有搞错的话，这意味着极端情况下女仆语音的音调可能只有原始音调的0.8。在现在使用的这套语音包下，确实有时候会听起来觉得稍微有些恐怖/阴森的感觉。

相比之下我看了下[LittleMaidReengaged](https://github.com/arcusmaximus/LittleMaidReengaged/blob/master/src/main/java/net/blacklab/lmr/entity/EntityLittleMaid.java)的实现，如果我没搞错的话（LMR的声音相关代码感觉要复杂挺多，这个我确实不太确定看的位置对不对），是以下代码

    float lpitch = LittleMaidReengaged.cfg_VoiceDistortion ? (rand.nextFloat() * 0.2F) + 0.95F : 1.0F;

意味着女仆音调最低只有原始音调的0.95，比我们的实现要高得多，所以听起来就没有那种恐怖的感觉。

**Comment by TartaricAcid** [comment]
多谢，我之前没发现此问题
