### ISSUE TITLE
[Bug] Crash on create new world

### ISSUE THREAD

**Issue by QianFuv** [TartaricAcid/TouhouLittleMaid#569]
### Minecraft Version

- [ ] 1.12.2 (End of support)
- [ ] 1.16.5 (End of support)
- [ ] 1.18.2
- [x] 1.19.2
- [ ] 1.20/1.20.1

### What happened?

After update to 1.1.12 cause this crash, back to 1.1.11 is fine.

### Relevant log output

```shell
https://mclo.gs/liyXaaQ
```

**Comment by yuusyaasisutanto** [comment]
I'm in MC 1.20.1 and TLM 1.1.12, And using Sinytra Connector and It seems same probrem had happened. (Exception in server tick loop)
but 1 thing differenet from this, I was tried to login already exist world.
When reverted to 1.1.11, this probrem won't happen too.

https://mclo.gs/Xh17nAf

I think this was related to this issue, but If I should seperate this issue, please tell me and I'll do.
sry for my poor english, but thank you.

**Comment by TartaricAcid** [comment]
The error report you sent me shows that it has nothing to do with the maid mod

You are missing an item from the archaeology mod

**Comment by QianFuv** [comment]
However, I did not install the archaeology mod, and this issue arose after updating the maid mod.

**Comment by TartaricAcid** [comment]
But the error report doesn't lie, It just says that...

You must have done something wrong

**Comment by TartaricAcid** [comment]
Try removing the L_Ender's Cataclysm mod and see if it works properly.

**Comment by TartaricAcid** [comment]
@yuusyaasisutanto The cause of your error is different from this issue, This seems to be a problem with the reply mod. There is a conflict. I will see how to solve it.

**Comment by yuusyaasisutanto** [comment]
> @yuusyaasisutanto The cause of your error is different from this issue, This seems to be a problem with the reply mod. There is a conflict. I will see how to solve it.

ah sorry, Should I make another issue?
(sry again but I'm not used to writing in Github...)

**Comment by QianFuv** [comment]
Further testing:
![image](https://github.com/user-attachments/assets/b0ab8fd4-65f8-4d27-87e0-cd594ca02a5b)
Creating a new world crashes when only installing these few mods.
https://mclo.gs/KqCV8Vn

**Comment by TartaricAcid** [comment]
@QianFuv 才发现你是中文用户，直接用中文就可以，这个应该是某个罕见的导致类触发的 bug，我尝试修复一下

**Comment by TartaricAcid** [comment]
![image](https://github.com/user-attachments/assets/af8646a4-72ce-4392-bdad-443bedecf567)
1.20.1 测试没有问题了

**Comment by QianFuv** [comment]
嗯嗯 谢谢啦🥰🥰🥰

**Comment by QianFuv** [comment]
您发布新版本后可以随时关闭此 Issue

**Comment by TartaricAcid** [comment]
查了下，确实是灾变模组的锅，没写好实体机制，导致这次更新误触他的有问题的代码

1.20.1 灾变模组是解决了这个问题的，1.19.2 我这边也无法解决，所以建议你更换到新版本

此问题关闭

**Comment by QianFuv** [comment]
好的 谢谢回复
