### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by GilbertLi1206** [TartaricAcid/TouhouLittleMaid#570]
### Minecraft Version

- [ ] 1.12.2 (End of support)
- [ ] 1.16.5 (End of support)
- [ ] 1.18.2
- [ ] 1.19.2
- [X] 1.20/1.20.1

### What happened?

My maid spawns a tombstone on the ground after her death, but I am unable to remove it, even though I am the server administrator. When I click on the tombstone, a message always appears: "This maid tombstone is not yours! If you are a server administrator, please use NTR Item to right-click to remove it. Current NTR item: [structure void]." What does this mean? How can I properly remove the tombstone?

**Comment by TartaricAcid** [comment]
please use NTR Item to right-click to remove it.
Current NTR item: [structure void]

=> use structure void item right-click tombstone

What, what is structure void?

Um, you are playing Minecraft, right? Structure void is an item in Minecraft. You can check this wiki and find it.
<https://minecraft.fandom.com/wiki/Structure_Void>
