### ISSUE TITLE
[Bug] 在自定义<基岩>超平坦世界中出现严重的计算延迟。

### ISSUE THREAD

**Issue by Candy-Link** [TartaricAcid/TouhouLittleMaid#572]
### Minecraft Version

- [ ] 1.12.2 (End of support)
- [ ] 1.16.5 (End of support)
- [ ] 1.18.2
- [ ] 1.19.2
- [X] 1.20/1.20.1

### What happened?

当前版本：1.1.12 & 1.1.12-hotfix。Forge_47.2.0。Java_17.0.8_x64。

新建或进入>>底部仅一层基岩的自定义超平坦世界，例如"bedrock;plains"预设。
移除其它MOD后依然存在问题。在正常游玩时这个问题似乎会让计算延迟出现抖动。

这个现象可能与妖精女仆生成有关，在配置文件中设置"MaidFairySpawnProbability = 0"后一切回归正常。

![2024-09-13_01 32 07](https://github.com/user-attachments/assets/e89bdab1-cd1d-4caa-b5f1-c93c4a6fdc72)

上个版本：1.1.11。也有类似的性能特征(微乎其微)，但不能通过"MaidFairySpawnProbability = 0"消除。

_(:з)∠)_不知道是否有关联所以写后面咯~

### Contact Details

BiliBili_UID：22759192

**Comment by Candy-Link** [comment]
我猜测这个问题和妖精女仆的生成机制有关，因为当我意识到这个可能的因素后、我尝试在配置文件中设置"MaidFairySpawnProbability = 0"后一切都回归正常。
因此相比上个版本(1.1.11)当前版本(1.1.12)整体性能表现不稳定，并且版本(1.1.11)也表现出类似特性不过影响微乎其微。

**Comment by TartaricAcid** [comment]
https://github.com/TartaricAcid/TouhouLittleMaid/commit/dc32f2f8b7fe352dbdeed3f92d871429f624ed15

已修正
