### ISSUE TITLE
和C2ME冲突

### ISSUE THREAD

**Issue by NeoStarWonV** [TartaricAcid/TouhouLittleMaid#575]
### Minecraft Version

- [ ] 1.12.2 (End of support)
- [ ] 1.16.5 (End of support)
- [ ] 1.18.2
- [ ] 1.19.2
- [X] 1.20/1.20.1
- [ ] 1.21/1.21.1

### What happened?

跑图的时候崩溃了
[crash-2024-09-13_16.30.35-server.txt](https://github.com/user-attachments/files/17083207/crash-2024-09-13_16.30.35-server.txt)

### Contact Details

1516021910@qq.com

**Comment by TartaricAcid** [comment]
你这个问题有点难办，你用了 Fabric 模组，我不清楚是不是因为两个加载器模组有某些 mixin 冲突，建议先移除 Fabric 模组测试

**Comment by TartaricAcid** [comment]
原来 C^2M 修改了区块生成，让其多线程生成啊，难怪会导致 CME 问题

**Comment by NeoStarWonV** [comment]
所以这是c2me的问题？

**Comment by NeoStarWonV** [comment]
所以这是c2me的问题？

**Comment by NeoStarWonV** [comment]
他们c2me让我来这里提交，这里能修么

**Comment by TartaricAcid** [comment]
我想办法解决一下，但是 C2ME 是 Fabric 模组啊，我写完没法测试啊

**Comment by NeoStarWonV** [comment]
我帮你测试哈哈

**Comment by ghost** [comment]
同样遇到了该问题

**Comment by TartaricAcid** [comment]
https://github.com/TartaricAcid/TouhouLittleMaid/releases/tag/snapshot-2024122509041735117471
修好了
