### ISSUE TITLE
[Bug] - Maids voicepacks Audio Jack issues

### ISSUE THREAD

**Issue by cyliamargatroid** [TartaricAcid/TouhouLittleMaid#577]
### Minecraft Version

- [ ] 1.12.2 (End of support)
- [ ] 1.16.5 (End of support)
- [ ] 1.18.2
- [ ] 1.19.2
- [X] 1.20/1.20.1
- [X] 1.21/1.21.1

### What happened?

1. When a Person irl plugs in a headphones while Minecraft is running, Maids voices has issues, it plays undesired sounds.
2. The only thing that fixes maid voice issues is `/tlm pack reload`, but that is unavailable when cheat is disabled.

So far, I only found that issue on Windows.

**Comment by TartaricAcid** [comment]
fixed in #574
