### ISSUE TITLE
关于扫帚的建议

### ISSUE THREAD

**Issue by Jedidiah-Zhang** [TartaricAcid/TouhouLittleMaid#58]
现在扫帚的合成表有点打破平衡了，
原版需要打完龙才能滑翔，但是现在有一个末影之眼就能飞了，感觉原版的平衡破坏的不是一点半点。
所以建议给扫帚加耐久或者把造价调高。（虽然我自己也能改，但是还是说一下这个问题）

**Comment by TartaricAcid** [comment]
扫帚现在改了设定，只允许创造模式骑乘
