### ISSUE TITLE
[Bug] Competition with RTM

### ISSUE THREAD

**Issue by cy-1818** [TartaricAcid/TouhouLittleMaid#580]
### Minecraft Version

- [X] 1.12.2 (End of support)
- [ ] 1.16.5 (End of support)
- [ ] 1.18.2
- [ ] 1.19.2
- [ ] 1.20/1.20.1
- [ ] 1.21/1.21.1

### What happened?

In 1.12.2, this mod can't use with RTM(https://www.curseforge.com/minecraft/mc-mods/realtrainmod/comments). I'm poor for java, but maybe maid_model.json is wrongly treated as RTM model pack, and it crashes. I know you don't support this version, but I'm happy if you can fix it.

### Relevant log output

---- Minecraft Crash Report ----

WARNING: coremods are present:
  IELoadingPlugin (ImmersiveEngineering-core-0.12-98.jar)
  FixRtmCorePlugin (fixRtm-2.0.28.jar)
  MekanismCoremod (Mekanism-1.12.2-9.8.3.390.jar)
  OTGCorePlugin (OTG-Core.jar)
  Quark Plugin (Quark-r1.6-179.jar)
  CQRPlugin (Chocolate_Quest_Repoured-1.12.2-2.6.16B.jar)
  iceandfire (iceandfire-1.9.1-1.12.2.jar)
  CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
  EnderCorePlugin (EnderCore-1.12.2-0.5.78-core.jar)
  HookingFixRtmCorePlugin (fixRtm-2.0.28.jar)
  llibrary (llibrary-core-1.0.11-1.12.2.jar)
  PatchingFixRtmCorePlugin (fixRtm-2.0.28.jar)
  JarInJarLoaderCoreMod (fixRtm-2.0.28.jar)
  DCASMPlugin (HeatAndClimateLib_1.12.2-3.9.3.jar)
  ReachFixPlugin (ReachFix-1.12.2-1.0.9.jar)
  TakumiASMCore (takumicraft-2.1.0.jar)
Contact their authors BEFORE contacting forge

// Who set us up the TNT?

Time: 9/27/24 12:41 PM
Description: Initializing game

jp.ngt.rtm.modelpack.ModelPackException: [RTMResourceManager] Can't get input stream (maid_model.json)
      at jp.ngt.rtm.modelpack.RTMResourceManager.func_110536_a(RTMResourceManager.java(modified by fixrtm):72)
      at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110536_a(SimpleReloadableResourceManager.java:65)
      at com.github.tartaricacid.touhoulittlemaid.client.resources.CustomResourcesLoader.loadMaidModelPack(CustomResourcesLoader.java:71)
      at com.github.tartaricacid.touhoulittlemaid.client.resources.CustomResourcesLoader.reloadResources(CustomResourcesLoader.java:53)
      at com.github.tartaricacid.touhoulittlemaid.client.event.ReloadResourceEvent.onTextureStitchEvent(ReloadResourceEvent.java:23)
      at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_828_ReloadResourceEvent_onTextureStitchEvent_Post.invoke(.dynamic)
      at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
      at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
      at net.minecraftforge.client.ForgeHooksClient.onTextureStitchedPost(ForgeHooksClient.java:218)
      at net.minecraft.client.renderer.texture.TextureMap.finishLoading(TextureMap.java:263)
      at net.minecraft.client.renderer.texture.TextureMap.func_110571_b(TextureMap.java:112)
      at net.minecraft.client.renderer.texture.TextureMap.func_174943_a(TextureMap.java:91)
      at net.minecraftforge.client.model.ModelLoader.func_177570_a(ModelLoader.java:159)
      at net.minecraft.client.renderer.block.model.ModelManager.func_110549_a(ModelManager.java:28)
      at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110542_a(SimpleReloadableResourceManager.java:121)
      at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:513)
      at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
      at net.minecraft.client.main.Main.main(SourceFile:123)
      at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
      at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
      at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
      at java.lang.reflect.Method.invoke(Method.java:497)
      at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
      at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
      at jp.ngt.rtm.modelpack.RTMResourceManager.func_110536_a(RTMResourceManager.java(modified by fixrtm):72)
      at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110536_a(SimpleReloadableResourceManager.java:65)
      at com.github.tartaricacid.touhoulittlemaid.client.resources.CustomResourcesLoader.loadMaidModelPack(CustomResourcesLoader.java:71)
      at com.github.tartaricacid.touhoulittlemaid.client.resources.CustomResourcesLoader.reloadResources(CustomResourcesLoader.java:53)
      at com.github.tartaricacid.touhoulittlemaid.client.event.ReloadResourceEvent.onTextureStitchEvent(ReloadResourceEvent.java:23)
      at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_828_ReloadResourceEvent_onTextureStitchEvent_Post.invoke(.dynamic)
      at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
      at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
      at net.minecraftforge.client.ForgeHooksClient.onTextureStitchedPost(ForgeHooksClient.java:218)
      at net.minecraft.client.renderer.texture.TextureMap.finishLoading(TextureMap.java:263)
      at net.minecraft.client.renderer.texture.TextureMap.func_110571_b(TextureMap.java:112)
      at net.minecraft.client.renderer.texture.TextureMap.func_174943_a(TextureMap.java:91)
      at net.minecraftforge.client.model.ModelLoader.func_177570_a(ModelLoader.java:159)
      at net.minecraft.client.renderer.block.model.ModelManager.func_110549_a(ModelManager.java:28)
      at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110542_a(SimpleReloadableResourceManager.java:121)
      at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:513)

-- Initialization --
Details:
Stacktrace:
      at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
      at net.minecraft.client.main.Main.main(SourceFile:123)
      at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
      at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
      at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
      at java.lang.reflect.Method.invoke(Method.java:497)
      at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
      at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
      Minecraft Version: 1.12.2
      Operating System: Windows 10 (amd64) version 10.0
      Java Version: 1.8.0_51, Oracle Corporation
      Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
      Memory: [12643729344](tel:12643729344) bytes (12057 MB) / [17179869184](tel:17179869184) bytes (16384 MB) up to [17179869184](tel:17179869184) bytes (16384 MB)
      JVM Flags: 11 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms16G -Xmx16G -XX:MetaspaceSize=1G -XX:+UseG1GC -XX:+UseStringDeduplication -XX:+DisableExplicitGC -XX:+OptimizeStringConcat -XX:+UseTLAB -Xss2G -Xmn2G
      IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
      FML: MCP 9.42 Powered by Forge 14.23.5.2859 106 mods loaded, 106 mods active
      States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

      | State | ID                                | Version           | Source                                          | Signature                                |
      |:----- |:--------------------------------- |:----------------- |:----------------------------------------------- |:---------------------------------------- |
      | LCH   | minecraft                         | 1.12.2            | minecraft.jar                                   | None                                     |
      | LCH   | mcp                               | 9.42              | minecraft.jar                                   | None                                     |
      | LCH   | FML                               | 8.0.99.99         | forge-1.12.2-14.23.5.2859.jar                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
      | LCH   | forge                             | 14.23.5.2859      | forge-1.12.2-14.23.5.2859.jar                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
      | LCH   | dcs_asm                           | 2.1.0             | minecraft.jar                                   | 4cd12b92959105443b7b694fffe0cea9ed004886 |
      | LCH   | otgcore                           | 1.12.2-v9.5-R2    | minecraft.jar                                   | None                                     |
      | LCH   | aether_legacy                     | 1.5.3.2           | aether-1.12.2-v1.5.4.0.jar                      | None                                     |
      | LCH   | atlaslib                          | 1.1.5a            | Atlas-Lib-1.12.2-1.1.5a.jar                     | None                                     |
      | LCH   | quark                             | r1.6-179          | Quark-r1.6-179.jar                              | None                                     |
      | LCH   | autoreglib                        | 1.3-32            | AutoRegLib-1.3-32.jar                           | None                                     |
      | LCH   | baubles                           | 1.5.2             | Baubles-1.12-1.5.2.jar                          | None                                     |
      | LCH   | biomesoplenty                     | 7.0.1.2445        | BiomesOPlenty-1.12.2-7.0.1.2445-universal.jar   | None                                     |
      | LCH   | buildcraftlib                     | 7.99.24.8         | buildcraft-all-7.99.24.8.jar                    | None                                     |
      | LCH   | buildcraftcore                    | 7.99.24.8         | buildcraft-all-7.99.24.8.jar                    | None                                     |
      | LCH   | buildcraftbuilders                | 7.99.24.8         | buildcraft-all-7.99.24.8.jar                    | None                                     |
      | LCH   | buildcrafttransport               | 7.99.24.8         | buildcraft-all-7.99.24.8.jar                    | None                                     |
      | LCH   | buildcraftsilicon                 | 7.99.24.8         | buildcraft-all-7.99.24.8.jar                    | None                                     |
      | LCH   | ic2                               | 2.8.170-ex112     | industrialcraft-2-2.8.170-ex112.jar             | de041f9f6187debbc77034a344134053277aa3b0 |
      | LCH   | buildcraftcompat                  | 7.99.24.8         | buildcraft-all-7.99.24.8.jar                    | None                                     |
      | LCH   | buildcraftenergy                  | 7.99.24.8         | buildcraft-all-7.99.24.8.jar                    | None                                     |
      | LCH   | buildcraftfactory                 | 7.99.24.8         | buildcraft-all-7.99.24.8.jar                    | None                                     |
      | LCH   | buildcraftrobotics                | 7.99.24.8         | buildcraft-all-7.99.24.8.jar                    | None                                     |
      | LCH   | dcs_lib                           | 3.9.3             | HeatAndClimateLib_1.12.2-3.9.3.jar              | 4cd12b92959105443b7b694fffe0cea9ed004886 |
      | LCH   | cavern                            | 2.3.1             | Cavern_1.12.2-v2.3.1.jar                        | None                                     |
      | LCH   | cctweaked                         | 1.89.2            | cc-tweaked-1.12.2-1.89.2.jar                    | None                                     |
      | LCH   | computercraft                     | 1.89.2            | cc-tweaked-1.12.2-1.89.2.jar                    | None                                     |
      | LCH   | ctm                               | MC1.12.2-1.0.2.31 | CTM-MC1.12.2-1.0.2.31.jar                       | None                                     |
      | LCH   | chisel                            | MC1.12.2-1.0.2.45 | Chisel-MC1.12.2-1.0.2.45.jar                    | None                                     |
      | LCH   | cqrepoured                        | 2.6.16B           | Chocolate_Quest_Repoured-1.12.2-2.6.16B.jar     | None                                     |
      | LCH   | codechickenlib                    | 3.2.3.358         | CodeChickenLib-1.12.2-3.2.3.358-universal.jar   | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
      | LCH   | cosmeticarmorreworked             | 1.12.2-v5a        | CosmeticArmorReworked-1.12.2-v5a.jar            | aaaf83332a11df02406e9f266b1b65c1306f0f76 |
      | LCH   | cyclicmagic                       | 1.20.12           | Cyclic-1.12.2-1.20.14.jar                       | 0e5cb559be7d03f3fc18b8cba547d663e25f28af |
      | LCH   | elevatorid                        | 1.3.14            | ElevatorMod-1.12.2-1.3.14.jar                   | None                                     |
      | LCH   | endercore                         | 1.12.2-0.5.78     | EnderCore-1.12.2-0.5.78.jar                     | None                                     |
      | LCH   | thaumcraft                        | 6.1.BETA26        | Thaumcraft-1.12.2-6.1.BETA26.jar                | None                                     |
      | LCH   | enderio                           | 5.3.72            | EnderIO-1.12.2-5.3.72.jar                       | None                                     |
      | LCH   | enderiointegrationtic             | 5.3.72            | EnderIO-1.12.2-5.3.72.jar                       | None                                     |
      | LCH   | enderiobase                       | 5.3.72            | EnderIO-1.12.2-5.3.72.jar                       | None                                     |
      | LCH   | enderioconduits                   | 5.3.72            | EnderIO-1.12.2-5.3.72.jar                       | None                                     |
      | LCH   | enderioconduitsappliedenergistics | 5.3.72            | EnderIO-1.12.2-5.3.72.jar                       | None                                     |
      | LCH   | enderioconduitsopencomputers      | 5.3.72            | EnderIO-1.12.2-5.3.72.jar                       | None                                     |
      | LCH   | enderioconduitsrefinedstorage     | 5.3.72            | EnderIO-1.12.2-5.3.72.jar                       | None                                     |
      | LCH   | enderiointegrationforestry        | 5.3.72            | EnderIO-1.12.2-5.3.72.jar                       | None                                     |
      | LCH   | enderiointegrationticlate         | 5.3.72            | EnderIO-1.12.2-5.3.72.jar                       | None                                     |
      | LCH   | enderioinvpanel                   | 5.3.72            | EnderIO-1.12.2-5.3.72.jar                       | None                                     |
      | LCH   | enderiomachines                   | 5.3.72            | EnderIO-1.12.2-5.3.72.jar                       | None                                     |
      | LCH   | enderiopowertools                 | 5.3.72            | EnderIO-1.12.2-5.3.72.jar                       | None                                     |
      | LCH   | mekanism                          | 1.12.2-9.8.3.390  | Mekanism-1.12.2-9.8.3.390.jar                   | None                                     |
      | LCH   | gasconduits                       | 5.3.72            | EnderIO-conduits-mekanism-1.12.2-5.3.72.jar     | None                                     |
      | LCH   | enderioendergy                    | 5.3.72            | EnderIO-endergy-1.12.2-5.3.72.jar               | None                                     |
      | LCH   | enderiozoo                        | 5.3.72            | EnderIO-zoo-1.12.2-5.3.72.jar                   | None                                     |
      | LCH   | epicfight                         | 1.12.2-2.2.8      | EpicFightMod-1.12.2-2.2.8.jar                   | None                                     |
      | LCH   | flansmod                          | 5.5.2             | Flan's Mod-1.12.2-5.5.2.jar                     | None                                     |
      | LCH   | flansmodapocalypse                | 1.0               | Flan's Mod-1.12.2-5.5.2.jar                     | None                                     |
      | LCH   | forgemultipartcbe                 | 2.6.2.83          | ForgeMultipart-1.12.2-2.6.2.83-universal.jar    | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
      | LCH   | microblockcbe                     | 2.6.2.83          | ForgeMultipart-1.12.2-2.6.2.83-universal.jar    | None                                     |
      | LCH   | minecraftmultipartcbe             | 2.6.2.83          | ForgeMultipart-1.12.2-2.6.2.83-universal.jar    | None                                     |
      | LCH   | geckolib3                         | 3.0.30            | geckolib-forge-1.12.2-3.0.31.jar                | None                                     |
      | LCH   | dcs_climate                       | 3.9.11            | HeatAndClimateMod_1.12.2-3.9.11.jar             | 4cd12b92959105443b7b694fffe0cea9ed004886 |
      | LCH   | llibrary                          | 1.7.20            | llibrary-1.7.20-1.12.2.jar                      | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
      | LCH   | iceandfire                        | 1.9.1             | iceandfire-1.9.1-1.12.2.jar                     | None                                     |
      | LCH   | infinitychest                     | 1.12-1.2.15       | InfinityChest-1.12-1.2.15.jar                   | None                                     |
      | LCH   | lmlibrary                         | 1.1.5             | LMLibrary-1.1.5.jar                             | None                                     |
      | LCH   | lmreengaged                       | 9.3.8.fp.058      | LittleMaidReengaged_FirisPatch-9.3.8.fp.058.jar | None                                     |
      | LCH   | lootcapacitortooltips             | 1.3               | lootcapacitortooltips-1.3.jar                   | None                                     |
      | LCH   | mcheli                            | 1.1.4             | mcheli-1.1.4.jar                                | None                                     |
      | LCH   | mekanismgenerators                | 1.12.2-9.8.3.390  | MekanismGenerators-1.12.2-9.8.3.390.jar         | None                                     |
      | LCH   | mekanismtools                     | 1.12.2-9.8.3.390  | MekanismTools-1.12.2-9.8.3.390.jar              | None                                     |
      | LCH   | harvestcraft                      | 1.12.2zb          | Pam's HarvestCraft 1.12.2zg.jar                 | None                                     |
      | LCH   | mm_lib                            | 2.3.0             | MMLib-2.3.0.jar                                 | None                                     |
      | LCH   | testdummy                         | 1.12              | MmmMmmMmmMmm-1.12-1.14.jar                      | None                                     |
      | LCH   | mowziesmobs                       | 1.5.8             | mowziesmobs-1.5.8.jar                           | None                                     |
      | LCH   | mrtjpcore                         | 2.1.4.43          | MrTJPCore-1.12.2-2.1.4.43-universal.jar         | None                                     |
      | LCH   | ngtlib                            | 2.4.21            | NGTLib2.4.21-38_forge-1.12.2-14.23.2.2611.jar   | None                                     |
      | LCH   | patchouli                         | 1.0-23.6          | Patchouli-1.0-23.6.jar                          | None                                     |
      | LCH   | polishedlib                       | 1.1.1             | PolishedLib-1.12.2-1.1.1.jar                    | None                                     |
      | LCH   | progressivebosses                 | 1.5.4             | ProgressiveBosses-1.5.4-mc1.12.x.jar            | None                                     |
      | LCH   | projectred-core                   | 4.9.4.120         | ProjectRed-1.12.2-4.9.4.120-Base.jar            | None                                     |
      | LCH   | projectred-compat                 | 1.0               | ProjectRed-1.12.2-4.9.4.120-compat.jar          | None                                     |
      | LCH   | projectred-integration            | 4.9.4.120         | ProjectRed-1.12.2-4.9.4.120-integration.jar     | None                                     |
      | LCH   | projectred-transmission           | 4.9.4.120         | ProjectRed-1.12.2-4.9.4.120-integration.jar     | None                                     |
      | LCH   | projectred-fabrication            | 4.9.4.120         | ProjectRed-1.12.2-4.9.4.120-fabrication.jar     | None                                     |
      | LCH   | projectred-illumination           | 4.9.4.120         | ProjectRed-1.12.2-4.9.4.120-lighting.jar        | None                                     |
      | LCH   | projectred-expansion              | 4.9.4.120         | ProjectRed-1.12.2-4.9.4.120-mechanical.jar      | None                                     |
      | LCH   | projectred-relocation             | 4.9.4.120         | ProjectRed-1.12.2-4.9.4.120-mechanical.jar      | None                                     |
      | LCH   | projectred-transportation         | 4.9.4.120         | ProjectRed-1.12.2-4.9.4.120-mechanical.jar      | None                                     |
      | LCH   | projectred-exploration            | 4.9.4.120         | ProjectRed-1.12.2-4.9.4.120-world.jar           | None                                     |
      | LCH   | rail plus                         | 2.0               | Rail Plus-1.12.2-2.0.jar                        | None                                     |
      | LCH   | reachfix                          | 1.0.9             | ReachFix-1.12.2-1.0.9.jar                       | None                                     |
      | LCH   | rtm                               | 2.4.24            | RTM2.4.24-43_forge-1.12.2-14.23.2.2611.jar      | None                                     |
      | LCH   | silentlib                         | 3.0.13            | SilentLib-1.12.2-3.0.14+168.jar                 | None                                     |
      | LCH   | scalinghealth                     | 1.3.37            | ScalingHealth-1.12.2-1.3.42+147.jar             | None                                     |
      | LCH   | shincolle                         | 1.12.2.1.0        | ShinColle-1.12.2.1.0.jar                        | None                                     |
      | LCH   | flammpfeil.slashblade             | mc1.12-r33        | SlashBlade-mc1.12-r33.jar                       | None                                     |
      | LCH   | slashblade_addon                  | 1.6.0             | SJAP-1.6.0.jar                                  | None                                     |
      | LCH   | smallstairs                       | 1.1.0             | SmallStairs-1.12.2-1.1.0.jar                    | None                                     |
      | LCH   | stellarfluidconduits              | 1.12.2-1.0.0      | stellarfluidconduit-1.12.2-1.0.3.jar            | None                                     |
      | LCH   | takumicraft                       | 2.1.0             | takumicraft-2.1.0.jar                           | None                                     |
      | LCH   | hordes                            | 1.5.3a            | The-Hordes-1.12.2-1.5.3a.jar                    | None                                     |
      | LCH   | lastsmith                         | 2.1.8-1.12.2      | TLS-2.1.8-1.12.2.jar                            | None                                     |
      | LCH   | tofucraft                         | 0.1.0.9           | TofuCraftReload-0.1.0.9.jar                     | None                                     |
      | LCH   | touhou_little_maid                | 1.2.5             | touhoulittlemaid-1.12.2-1.2.5-release.jar       | None                                     |
      | LCH   | twilightforest                    | 3.11.1021         | twilightforest-1.12.2-3.11.1021-universal.jar   | None                                     |
      | LCH   | urushi                            | alpha2.33         | Urushi-1.12.2-alpha2.38.jar                     | None                                     |
      | LCH   | immersiveengineering              | 0.12-98           | ImmersiveEngineering-0.12-98.jar                | None                                     |
      | LCH   | fix-rtm                           | 2.0.28            | fixRtm-2.0.28.jar                               | None                                     |

      Loaded coremods (and transformers):
IELoadingPlugin (ImmersiveEngineering-core-0.12-98.jar)
  blusunrize.immersiveengineering.common.asm.IEClassTransformer
FixRtmCorePlugin (fixRtm-2.0.28.jar)
 
MekanismCoremod (Mekanism-1.12.2-9.8.3.390.jar)
  mekanism.coremod.KeybindingMigrationHelper
OTGCorePlugin (OTG-Core.jar)
  com.pg85.otg.forge.asm.excluded.OTGClassTransformer
Quark Plugin (Quark-r1.6-179.jar)
  vazkii.quark.base.asm.ClassTransformer
CQRPlugin (Chocolate_Quest_Repoured-1.12.2-2.6.16B.jar)
  team.cqr.cqrepoured.asm.CQRClassTransformer
iceandfire (iceandfire-1.9.1-1.12.2.jar)
  com.github.alexthe666.iceandfire.patcher.IceAndFireRuntimePatcher
CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
  team.chisel.ctm.client.asm.CTMTransformer
EnderCorePlugin (EnderCore-1.12.2-0.5.78-core.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
  com.enderio.core.common.transform.SimpleMixinPatcher
HookingFixRtmCorePlugin (fixRtm-2.0.28.jar)
  com.anatawa12.fixRtm.asm.hooking.HookingTransformer
llibrary (llibrary-core-1.0.11-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
PatchingFixRtmCorePlugin (fixRtm-2.0.28.jar)
  com.anatawa12.fixRtm.asm.patching.PatchApplier
JarInJarLoaderCoreMod (fixRtm-2.0.28.jar)
  com.anatawa12.fixRtm.jarInJar.JarInJarPatcher
DCASMPlugin (HeatAndClimateLib_1.12.2-3.9.3.jar)
  defeatedcrow.hac.asm.DCMethodTransformer
ReachFixPlugin (ReachFix-1.12.2-1.0.9.jar)
  meldexun.reachfix.asm.ReachFixClassTransformer
TakumiASMCore (takumicraft-2.1.0.jar)
  com.tntmodders.asm.TakumiASMTransformer
      GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 472.12' Renderer: 'NVIDIA GeForce RTX 3060/PCIe/SSE2'
      Ender IO: No known problems detected.
      Authlib is : /C:/Users/yuki1/AppData/Roaming/.minecraft/libraries/com/mojang/authlib/1.5.25/authlib-1.5.25.jar

      !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
      !!!You are looking at the diagnostics information, not at the crash.       !!!
      !!!Scroll up until you see the line with '---- Minecraft Crash Report ----'!!!
      !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

      RTM Model Status: Initialized 0 models, Using 0 models
      I = Initialized, C = Constructed, SMP = SMP includeds

      | model pack | all | I | C | SMP |
      |:---------- |:--- |:- |:- |:--- |

      Patchouli open book context: n/a
      Launched Version: 1.12.2-forge-14.23.5.2859
      LWJGL: 2.9.4
      OpenGL: NVIDIA GeForce RTX 3060/PCIe/SSE2 GL version 4.6.0 NVIDIA 472.12, NVIDIA Corporation
      GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

      Using VBOs: Yes
      Is Modded: Definitely; Client brand changed to 'fml,forge'
      Type: Client (map_client.txt)
      Resource Packs:
      Current Language: 日本語 (日本)
      Profiler Position: N/A (disabled)
      CPU: 12x AMD Ryzen 5 7600 6-Core Processor

**Comment by TartaricAcid** [comment]
1.12.2 is End of support
