### ISSUE TITLE
[Bug] 客户端/本地单机切换女仆工作模式会闪退

### ISSUE THREAD

**Issue by OstiumAxioma** [TartaricAcid/TouhouLittleMaid#583]
### Minecraft Version

- [ ] 1.12.2 (End of support)
- [ ] 1.16.5 (End of support)
- [ ] 1.18.2
- [ ] 1.19.2
- [x] 1.20/1.20.1
- [ ] 1.21/1.21.1

### What happened?

1. 所有功能正常，只有切换工作模式的功能有错误
2. 有机械动力和瓦尔基里以及TAC，大概率冲突的mod
3. 女仆试过没有装备任何东西，出生并喂食蛋糕后直接右键开界面点切换工作模式的按钮，只要按下就会立刻闪退
4. 服务端有的话服务器不会崩溃，但是客户端会直接因为闪退断联
错误报告如下
[crash-2024-10-05_01.47.22-client.txt](https://github.com/user-attachments/files/17265594/crash-2024-10-05_01.47.22-client.txt)
https://paste.ubuntu.com/p/7sPbHWF7dJ/

### Relevant log output

```shell
See https://paste.ubuntu.com/p/7sPbHWF7dJ/
```

**Comment by TartaricAcid** [comment]
是 tacz 的问题，你把 glock 17 这把枪给弄没了

**Comment by OstiumAxioma** [comment]
哦哦，所以是需要把这个魔改过得tacz给恢复成原版的吗？因为1.1.12版本应该已经完全支持tacz了吧

**Comment by OstiumAxioma** [comment]
> 是 tacz 的问题，你把 glock 17 这把枪给弄没了

我试了下删除了整个config中的tacz文件，成功启动游戏后退出再加入了默认枪包，但是还是会闪退，看log里也是提示
java.lang.IllegalArgumentException: Could not found gun id: tacz:glock_17

**Comment by TartaricAcid** [comment]
你在游戏内能找到格洛克17这把枪么，如果不能，那就是你弄坏了默认的枪械包，这既不是 tacz 的问题，也不是女仆模组的问题
