### ISSUE TITLE
[Question] can you tell me what is these text

### ISSUE THREAD

**Issue by liangmoe** [TartaricAcid/TouhouLittleMaid#584]
### Minecraft Version

- [ ] 1.12.2 (End of support)
- [ ] 1.16.5 (End of support)
- [ ] 1.18.2
- [ ] 1.19.2
- [X] 1.20/1.20.1
- [ ] 1.21/1.21.1

### What happened?

When i right click any solid block and right click the maid again there is a flowing text "maid big container" rendered on the block, it looks buggy and i want to know how can i reproduce it with clean instance so i can find the problematic compatiblity problem

![2024-10-06_16 33 50](https://github.com/user-attachments/assets/bba35f75-0061-4f35-a8ce-f3d17764c8ca)

### Contact Details

iank3b@gmail.com

**Comment by TartaricAcid** [comment]
I have never encountered such a problem, and this is the first time I have received similar feedback

I am afraid this is not a problem with the maid mod

**Comment by liangmoe** [comment]
How do you make those text apear ingame with just maid mod? I want to atleast knowing what could i do to let it apear first so i can look into it

**Comment by liangmoe** [comment]
closing as this is not related to touhou maid mod

**Comment by liangmoe** [comment]
okay, it is weird behavior with [Chest Tracker](https://modrinth.com/mod/chest-tracker) mod, go to its config and disable container names fixes it
