### ISSUE TITLE
女仆的弓箭没有伤害

### ISSUE THREAD

**Issue by Coloryr** [TartaricAcid/TouhouLittleMaid#6]
今天build测试了下，发现女仆弓箭没伤害？
![1](https://user-images.githubusercontent.com/26276037/61473753-aa236100-a9b9-11e9-815c-58e9ab25f856.gif)
也有可能是其他mod的锅(不确定)

**Comment by TartaricAcid** [comment]
我这边测试一切正常，无法复现
