### ISSUE TITLE
[Bug] 当周围有多个女仆或玩家在钓鱼时，会出现线连接在一起的情况

### ISSUE THREAD

**Issue by ghost** [TartaricAcid/TouhouLittleMaid#627]
### Minecraft Version

- [ ] 1.12.2 (End of support)
- [ ] 1.16.5 (End of support)
- [ ] 1.18.2
- [ ] 1.19.2
- [ ] 1.20/1.20.1
- [X] 1.21/1.21.1

### What happened?

1. 两个女仆或以上同时进行钓鱼

![huge_2024-12-24_15 16 29](https://github.com/user-attachments/assets/94f8930c-cf9d-496e-8a47-907dfd577ed9)

**Comment by TartaricAcid** [comment]
https://github.com/TartaricAcid/TouhouLittleMaid/commit/853c5208bef02a5d23807d64a09e01eb020ef733

已修复
