### ISSUE TITLE
女仆弓箭伤害问题。

### ISSUE THREAD

**Issue by TuanziRice** [TartaricAcid/TouhouLittleMaid#64]
无意中发现，女仆射出的箭伤害只有4点，即使用力量5的弓射出箭伤害也只有8点。
而如果玩家射击的话未附魔的弓拉满是9点伤害,1/5的几率造成10点伤害。（以上数据来自WIKI）
不知道这是BUG还是特性。

**Comment by TartaricAcid** [comment]
射击方面全部沿用原版骷髅射箭逻辑，拉弓蓄力并非是全满的
