### ISSUE TITLE
农业工艺有准备兼容嘛？

### ISSUE THREAD

**Issue by MontellaGreat** [TartaricAcid/TouhouLittleMaid#65]
刚刚尝试让女仆在作物架上进行种植 然后发现并不支持，种子已经研究解锁
杂草也不会自动去除
943未来会添加兼容农业工艺的功能嘛

**Comment by TartaricAcid** [comment]
所有的模组兼容问题，除非是很严重的 bug 类型的，目前都不会主动做兼容，优先完成基本内容，而后才做兼容考虑，这一点请谨记
