### ISSUE TITLE
一些bug关于mod兼容问题

### ISSUE THREAD

**Issue by NatsuIryou** [TartaricAcid/TouhouLittleMaid#66]
刚才把1.1.2版的mod加到我的1.12.2多mod生存里面，开了个创造档测试了一下，驯服后的女仆会被其他女仆攻击(不管是否驯服)，而且貌似女仆使用剑的时候打不出满伤害，初步推测和animania-1.12.2-1.6.2.jar(更多动物)冲突，因为这个mod里的来亨鸡会攻击女仆，貌似是生物ID冲突？这方面我也不是很了解。

还有一些bug。我同时驯服了LittleMaidR的女仆和THLM的女仆(一只魔理沙)，然后魔理沙无论站着还是坐着都会飞快追着普通女仆，站着的时候还会挥手(看起来没有使用手上的物品)，说的话类似于「がないも(ね)」，原因不明。。。

希望能够早日修复！;p

**Comment by TartaricAcid** [comment]
你用的 LittleMaidR 是哪来的？

**Comment by NatsuIryou** [comment]
> 你用的 LittleMaidR 是哪来的？

curseforge下载的 文件名是LittleMaidReengaged-8.0.1.66-unofficial-1.12.2.jar

**Comment by TartaricAcid** [comment]
curseforge 的 LittleMaidReengaged 问题非常多，我不会对其做任何兼容性修改

**Comment by TartaricAcid** [comment]
女仆使用剑的逻辑全部来自于原版僵尸使用剑的逻辑
原版设定 == 我没有错

**Comment by TartaricAcid** [comment]
反馈的两个问题都没有确切的证据表明是 bug，关闭不予解决
