### ISSUE TITLE
女仆有时会杀死玩家，包括主人

### ISSUE THREAD

**Issue by mcBegins2Snow** [TartaricAcid/TouhouLittleMaid#70]
mod 版本：1-1-2 hotfix
当女仆远程攻击（弹幕和弓箭）时，玩家在走位不当时可能会被女仆杀死，即使是自己驯服的。
参考视频：https://www.bilibili.com/video/av62964669

**Comment by Snownee** [comment]
你自己往上撞，神仙都救不了你

**Comment by TartaricAcid** [comment]
原版弓箭还能射死自己呢_(:з」∠)_，投掷物我已经设计了不伤害投掷者自身了，再往上还能做到不伤害主人……这真的就是抗日神剧里面的包子雷了，自带敌我识别功能了

**Comment by Snownee** [comment]
> 原版弓箭还能射死自己呢_(:з」∠)_，投掷物我已经设计了不伤害投掷者自身了，再往上还能做到不伤害主人……这真的就是抗日神剧里面的包子雷了，自带敌我识别功能了

看他的视频似乎主人会受伤
