### ISSUE TITLE
1.1.3的几个小问题

### ISSUE THREAD

**Issue by Jedidiah-Zhang** [TartaricAcid/TouhouLittleMaid#77]
1. 这个是干嘛用的，前几个版本还有名字。。。
![image](https://user-images.githubusercontent.com/50638143/62940165-8fe87180-be05-11e9-9679-508923585f45.png)

2. 女仆坐在坐垫上时，能否相对于坐垫固定一定的角度，不要视线总跟着玩家了。这样对于一些有方向的坐垫来讲不会太奇怪。当然对于不同坐垫设计一些专有动作就完美了

3. 大于一格的坐垫穿模严重，但是我想不到什么好的解决方法。要修改的话估计得大改

4. 照片在名字上显示女仆的名字。而不是需要鼠标只在它上才显示。

**Comment by Jedidiah-Zhang** [comment]
然后催更手册

**Comment by TartaricAcid** [comment]
1. 还没完成的技能界面（某个地方写错了，居然加上了 key）
2. 视线朝向玩家是故意这么设计的。不同坐垫不同动作太过复杂，因为动画部分是编码，但是椅子部分是软编码且可自定义的，设计上无法做到。
3. 穿模严重？这段话描述太过模糊，未能说清楚什么部分因为什么导致怎样的穿模
4. 在照片上显示女仆的名字？你要知道有些名字可长的吓人，一个小小的格子可塞不下
5. 哪来的手册？

**Comment by Jedidiah-Zhang** [comment]
1. 好的
2. 麻烦就算了
3. 就是坐垫只是贴图，大于一格的坐垫就会导致你可以在坐垫里放方块
4. 我是说照片的名字上显示保存女仆的名字，而不是都叫照片
5. 我记岔了。。

**Comment by Snownee** [comment]
3. 模型是客户端决定的，不能影响服务端的碰撞

**Comment by mcBegins2Snow** [comment]
除了楼主发现的之外，我还发现女仆不能直接走过铁轨，除非架桥或破坏铁轨。
![2019-08-18_16 36 21](https://user-images.githubusercontent.com/37864486/63222169-7fa20f00-c1d6-11e9-9876-3dc9a6c7a1f2.png)
血量上限在更新到1.1.3后仍然是20
![2019-08-18_16 40 29](https://user-images.githubusercontent.com/37864486/63222205-1bcc1600-c1d7-11e9-9eaf-013d4fc61790.png)
![2019-08-18_16 41 33](https://user-images.githubusercontent.com/37864486/63222206-1d95d980-c1d7-11e9-82f4-5e2d22eb9fab.png)

**Comment by TartaricAcid** [comment]
> 我是说照片的名字上显示保存女仆的名字，而不是都叫照片

但是照片的文本提示部分不是显示了女仆的名字么……你这个需求有点奇葩啊

**Comment by TartaricAcid** [comment]
> 女仆不能直接走过铁轨，除非架桥或破坏铁轨。

原版狼也有这样的问题，请向 Mojang 反馈此问题，Mojang 修了我再修（抖机灵 <_<）

> 血量上限在更新到1.1.3后仍然是20

本来就是 20 啊，你还想要多少？

**Comment by mcBegins2Snow** [comment]
楼主40血怎么解释？

**Comment by TartaricAcid** [comment]
雷击后的女仆血量翻倍
