### ISSUE TITLE
一人血书求增强女仆生存能力

### ISSUE THREAD

**Issue by TuanziRice** [TartaricAcid/TouhouLittleMaid#79]
![2019-08-16_20 28 28](https://user-images.githubusercontent.com/53082959/63167697-a2141b00-c064-11e9-847a-28792ced4288.png)
今天打BOSS死了仨女仆= =，主要死因是被我的箭误伤射死的。
能不能让女仆免疫玩家伤害

![2019-08-16_20 25 29](https://user-images.githubusercontent.com/53082959/63167662-84df4c80-c064-11e9-8c75-7890fababf02.png)
妹啊，你再不喂我我要饿死了

![2019-08-16_20 36 01](https://user-images.githubusercontent.com/53082959/63168074-b573b600-c065-11e9-83b3-f61bdeb99457.png)
村民和女仆对比一下发现：
村民种地收获是一排一排种的，走到田的边缘才会打破收获作物，没有遗落的东西
女仆种地是虽然也是一排一排种的，但是会画出S型路线，每次都是打掉前方一格的作物，掉落物掉的到处都是还要跑过去捡。
可不可以让掉落物直接进女仆背包？

**Comment by TuanziRice** [comment]
![2019-08-16_20 33 31](https://user-images.githubusercontent.com/53082959/63168782-af7ed480-c067-11e9-9c2d-3aff949c40b3.png)
补一张女仆种地的图，总是拉下几块
另外能不能加个黑名单，比如说不要毒土豆啥的

**Comment by TartaricAcid** [comment]
> 女仆免疫玩家伤害

完全免疫是不打算做的，但是已经设计了最大伤害

> 女仆种植问题

这个问题很简单，因为甘蔗比较高，所以搜索范围我设计的比较大（即女仆在离方块比较远的距离就可打掉作物，种植作物），但是这样就会出现你所说的两个问题。
这个问题现在面临两难，看你选择哪个：
1. 取消掉种植、收割甘蔗功能，让女仆种地收获更贴近原版村民
2. 保持现状

> 种植黑名单……

这个不算是很要紧的设计，看情况做吧

**Comment by mcBegins2Snow** [comment]
除了楼主发现的之外，我还发现女仆不能直接走过铁轨，除非架桥或破坏铁轨。
![2019-08-18_16 36 21](https://user-images.githubusercontent.com/37864486/63222169-7fa20f00-c1d6-11e9-9876-3dc9a6c7a1f2.png)

**Comment by TuanziRice** [comment]
种植倒是没啥影响，反正女仆也会跑去捡，倒是能不能让女仆背包满了又没地方塞的时候停止工作啊

**Comment by TartaricAcid** [comment]
大部分建议内容已经完成，关闭此 Issues
