### ISSUE TITLE
一些杂七杂八的问题

### ISSUE THREAD

**Issue by TuanziRice** [TartaricAcid/TouhouLittleMaid#8]
1.女仆进行远程攻击的时候，无法越过一格高的地形
![2019-07-19_19 08 05](https://user-images.githubusercontent.com/53082959/61531213-c0ccc500-aa58-11e9-8262-32f2dca05a92.png)
放风筝被围殴

2.是在无护甲时，护甲值显示异常
![2019-07-19_19 10 08](https://user-images.githubusercontent.com/53082959/61531318-13a67c80-aa59-11e9-9481-79aea9943de1.png)

3.由女仆喂食无法增加营养值，并且女仆不会喂药水。

4.女仆在坐下状态收到攻击不会反击

最后希望能让女仆免疫友军伤害，还有一些地形伤害，比如说摔落，火焰，仙人掌什么的
并增加女仆的回血手段，比如说吃糖蛋糕什么的
感觉女仆还是比较脆
以及能够使用其他模组一些简单的枪械法杖什么的
![2019-07-19_19 14 13](https://user-images.githubusercontent.com/53082959/61531570-cb3b8e80-aa59-11e9-8d6c-9bebb64ef1e5.png)

**Comment by TuanziRice** [comment]
另外女仆似乎只能吃到护甲值，无法吃到盔甲的韧性

**Comment by TartaricAcid** [comment]
> 另外女仆似乎只能吃到护甲值，无法吃到盔甲的韧性
我看了下原版玩家的实现，发现没做什么改动啊

**Comment by TuanziRice** [comment]
我做了个简单的测试，利用命令分别制造了护甲20韧性0和护甲0韧性20的装备，使用然后发现韧性并没有起到减免伤害的作用。

**Comment by TakimotoEirlo** [comment]
女仆受伤和littlemaidmob的女仆（以后简称lmm女仆）相比，疗伤还是白糖这种一直氪糖回血的更实用。

**Comment by Block-e2** [comment]
> 我做了个简单的测试，利用命令分别制造了护甲20韧性0和护甲0韧性20的装备，使用然后发现韧性并没有起到减免伤害的作用。

额，其实装备的韧性并没有减少伤害的能力，MC里面韧性只是减少装备耐久的消耗速度

**Comment by lone-wolf-akela** [comment]
> > 我做了个简单的测试，利用命令分别制造了护甲20韧性0和护甲0韧性20的装备，使用然后发现韧性并没有起到减免伤害的作用。
> 
> 额，其实装备的韧性并没有减少伤害的能力，MC里面韧性只是减少装备耐久的消耗速度

根据[wiki](https://minecraft-zh.gamepedia.com/%E7%9B%94%E7%94%B2#.E7.9B.94.E7.94.B2.E9.9F.A7.E6.80.A7)，盔甲韧性是会减少伤害的呀

**Comment by Block-e2** [comment]
> > > 我做了个简单的测试，利用命令分别制造了护甲20韧性0和护甲0韧性20的装备，使用然后发现韧性并没有起到减免伤害的作用。
> > 
> > 
> > 额，其实装备的韧性并没有减少伤害的能力，MC里面韧性只是减少装备耐久的消耗速度
> 
> 根据[wiki](https://minecraft-zh.gamepedia.com/%E7%9B%94%E7%94%B2#.E7.9B.94.E7.94.B2.E9.9F.A7.E6.80.A7)，盔甲韧性是会减少伤害的呀

好像是我之前理解错了……百科上说：每一防御点数减少最多4%伤害；攻击伤害愈高，盔甲能减少的百分点愈少，最低为0.8%。当盔甲韧性增加，高伤害攻击减少的防御量会减少，而如果盔甲韧性到达一个很高的数值（通过使用命令），高伤害攻击减少的防御量是微不足道的。所以如果你想看出韧性的作用就制造护甲20韧性0和护甲20韧性20的装备来比较

**Comment by TartaricAcid** [comment]
这些反馈的问题部分得到了解决，部分是故意这么设计的，还有部分不打算当前解决，关闭此问题反馈
