### ISSUE TITLE
任务活动范围标定，Ticket系统

### ISSUE THREAD

**Issue by Snownee** [TartaricAcid/TouhouLittleMaid#82]
https://github.com/MinecraftForge/MinecraftForge/pull/4891
https://github.com/MinecraftForge/MinecraftForge/pull/5876

**Comment by TartaricAcid** [comment]
看了下，没太理解 ticket 系统是作用是？

**Comment by Snownee** [comment]
这是我之后的计划

**Comment by TartaricAcid** [comment]
划定范围功能已经实现了，ticket 系统后续有时间了研究下
