### ISSUE TITLE
女仆飞行

### ISSUE THREAD

**Issue by GGBIGC** [TartaricAcid/TouhouLittleMaid#89]
如果女仆骑着扫帚飞行的时候能更平稳一点，不会飞一小会就突然掉下去就好了。

**Comment by TartaricAcid** [comment]
原版鹦鹉飞行也有这个问题，对于原版就存在的设定（亦或是问题），目前的处理意见是：“Mojang 修了我就修”

**Comment by GGBIGC** [comment]
哈哈 这么佛性的吗╮( •́ω•̀ )╭



---原始邮件---
发件人: "tartaric_acid"<notifications@github.com&gt;
发送时间: 2019年8月27日(星期二) 下午5:57
收件人: "TartaricAcid/TouhouLittleMaid"<TouhouLittleMaid@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"GGBIGC"<2843316106@qq.com&gt;;
主题: Re: [TartaricAcid/TouhouLittleMaid] 女仆飞行 (#89)



原版鹦鹉飞行也有这个问题，对于原版就存在的设定（亦或是问题），目前的处理意见是：“Mojang 修了我就修”

**Comment by TartaricAcid** [comment]
尽可能复用原版的设计，如无必要不自己造轮子……这个设计理念应该没有错吧……
