### ISSUE TITLE
希望接下来的版本能直接通过release发布

### ISSUE THREAD

**Issue by abc1763613206** [TartaricAcid/TouhouLittleMaid#90]
如题。  

个人觉得这样做的优点一是可以略微对七牛云进行分流，二是用好了它的tag就可以检测版本号等内容。

**Comment by zhou135a** [comment]
赞成 出现bug还方便自己一点_(:з」∠)_

**Comment by TartaricAcid** [comment]
在 Jack 的帮助下用 Jenkins 做了一个自动化集成，你在主仓库界面的 README 部分能找到 Jenkins 地址
