### ISSUE TITLE
希望加大模组兼容力度

### ISSUE THREAD

**Issue by Micywind** [TartaricAcid/TouhouLittleMaid#91]
女仆的武器，工具，防具，无法获得mod特性。比如给女仆量子套，无尽套，无法无敌，匠魂弓无法射击，枪械神秘魔法…………。虽然每个mod都兼容不可能，但是希望能够兼容大多数主流mod。比如工业2，无尽贪婪，匠魂0

**Comment by TartaricAcid** [comment]
这些模组所使用的部分功能未按照原版护甲，武器，工具设定来，严苛来说这不算我的问题。

模组兼容部分目前优先级最低，暂时不予处理。
