### ISSUE TITLE
一些建议

### ISSUE THREAD

**Issue by Ishtar31116** [TartaricAcid/TouhouLittleMaid#94]
1.女仆在待命状态受到较高伤害并着火的时候（比如雷击）会以待命的状态这种形式乱跑，简单的说就是，女仆的待命状态是一个坐姿，她在被雷击并着火这种情况的时候会坐着乱跑。如果觉得我描述不够清楚可以自行用指令雷击女仆试试；
2.魔理沙的扫帚，这个工具比较影响游戏的平衡，扫帚的飞行类似创造模式的飞行，而且扫帚的造价便宜，原版的鞘翅必须在打完末影龙之后找到末地城才能够获得。建议增加耐久，改变合成表；
3.御币，御币发射时候弹幕的位置的问题，御币发射的弹幕就是一个白色光团，在发射出去的瞬间几乎会把屏幕完全占据，会造成屏幕一瞬间闪一下的效果（如果不太清问题建议连续使用御币），连续使用御币会对玩家的眼睛造成一定伤害，建议发射弹幕的位置可以改成弓箭那样，减少闪屏的效果；
4.绀珠之药，绀珠之药在女仆收到致命攻击的时候不会生效；
5.女仆在骑着扫帚飞行时，有旗指物并切换到弹幕模式的状态下，弹幕发射出去的距离很短，无法有效的攻击游戏中的敌对生物，女仆在骑着扫帚的状态下各种行为与一般的时候相比较缓慢，比如攻击敌对生物，收获农作物等；
6.女仆在农场模式，在收获了农作物之后有些时候会优先将背包相应的物品放入放置了交互面板的箱子中，这样会导致一部分的耕地没有被耕种，女仆耕种耕地的优先级应该高于交互面板；
7.女仆不会开关栅栏门，女仆不会从低处通过梯子到达高处；
8.女仆在攻击模式，敌对生物数量多的时候，从发现目标到将敌对生物击杀整个过程比较慢，表现为女仆移动到目标敌对生物的速度比较慢，女仆在home模式关闭情况下从远处移动到玩家身边的速度比这个快多了。女仆在与敌对生物处于同一格的时候，发现目标后头会抽动然后攻击敌对生物（这里是将女仆用于刷怪笼刷怪塔，女仆负责击杀怪物，在这种情况发生的现象）。女仆弹幕模式时被敌对生物贴身弹幕有时候无法攻击到敌对生物；
9.女仆的语音过于频繁，建议减少女仆发出语音的频率，或者某些语音只在特定的行为时才会发出；
10.女仆寻路的AI问题，女仆在锁定一个目标后，会一直锁定这个目标，即使该目标无法到达，表现为，女仆为攻击模式，女仆与敌对生物之间被栅栏或者圆石墙间隔开，女仆无法顺利到达敌对生物在的地方对敌对生物进行攻击，女仆会一直锁定该敌对生物，从该敌对生物转移目标至其它敌对生物的概率较小（其它敌对生物可以与该敌对生物一样和女仆之间有栅栏间隔开，也可以是在女仆可以顺利到达的地方）；女仆在农场模式，女仆会尝试收获（或耕种）无法到达的农作物（或耕地），这个农作物（耕地）可能是被栅栏或者其它东西将女仆与之间隔开来，这种情况下女仆改变目标的概率很小，女仆不改变目标会导致其它成熟的农作物未能收获（或者没有耕地没有被耕种），发生这种情况的时候女仆可以有两种情况，一、女仆没有旗指物，在受到攻击后，女仆会到处乱跑，在女仆停下来的时候有几率改变目标；二、女仆有旗指物，女仆受到攻击的时候也会一直锁定目标，直到死亡（因为这个产生了好多手办。。。），极少数情况下女仆会改变目标；建议，修改这一机制，女仆在长时间未达成目标（击杀敌对生物，收获农作物，种地等）的时候，主动变更目标；或者改变一下home模式，罗盘由设定一个点改为或者增加设定一块区域的功能，区域外的目标自动无视；
11.增加一些新的道具，如魔理沙的八卦炉等每个女仆相关的物品，具体功能可以和已经有的物品相同，比如魔理沙的八卦炉和御币一样能够发射弹幕；
12.可以把新增加的物品增加到香霖堂的店主可交易的物品列表中，比如相机、旗指物。
最后，以上的建议是在游玩Touhou Little Maid 1.1.4 版本预览快照版中所遇到的问题，个别问题可能是旧版存在但是新版可能已经进行修改修复。

**Comment by TartaricAcid** [comment]
> 女仆不会开关栅栏门，女仆不会从低处通过梯子到达高处

如你所见，原版村民也不会开关栅栏门，爬梯子。原版提供的路径算法没有对栅栏门的支持，原版提供的栅栏门并没有 `Open` 和 `Close` 这样的方法。所以想要实现开关栅栏门功能，至少在我这个水平理解下，难度非常大。

> 女仆的语音过于频繁

有配置文件可以改频率

**Comment by Ishtar31116** [comment]
关于女仆的语音方面，试着在游戏里面的模组设定进行了更改，不过好像没有生效，我是在服务器里面进行游戏，应该是要服务器的服务端更改才有效吧，玩家的客户端更改可能是无效的，但是更改女仆是否总是显示帽子却是有效的。当然也可能是我改动的地方和你说的配置文件不同。

**Comment by Ishtar31116** [comment]
另外今天我似乎发现了一个新的问题，女仆（攻击模式）好像不会主动去攻击史莱姆，只有在玩家受到史莱姆攻击的时候才会去攻击史莱姆？

**Comment by TartaricAcid** [comment]
播放声音间隔的逻辑好像是在服务端执行的。
不会攻击史莱姆是因为史莱姆并没有继承 EntityMob 导致的，后续我主动加上

**Comment by Ishtar31116** [comment]
还有一个问题，之前好像忘记写了，女仆不太容易捡到栅栏那一格的掉落物

**Comment by TartaricAcid** [comment]
我把拾取范围设计的比较小，因为后续打算为饰品留下发挥空间

**Comment by TartaricAcid** [comment]
1. 雷击慌乱移动：已解决
2. 扫帚：更改为仅限创造模式玩家骑乘
3. 御币：已经修改生成弹幕位置
4. 绀珠之药：已经修复
5. 女仆在骑着扫帚飞行时：飞行模式仅供玩赏，非主要工作状态
6. 女仆在农场模式：不解决
7. 女仆不会开关栅栏门，女仆不会从低处通过梯子到达高处：原版代码设计问题，无法解决
8. 女仆在攻击模式：不解决
9. 女仆的语音过于频繁：配置文件自行修改
10. 女仆寻路的AI问题：已经解决
11. 增加一些新的道具：在计划中了
12. 新增加的物品增加到可交易的物品列表：有配置文件，自行修改
